/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","de-ch",{title:"Barrierefreiheitinformationen",contents:"Hilfeinhalt. Um den Dialog zu schliessen die Taste ESC dr체cken.",legend:[{name:"Allgemein",items:[{name:"Editorwerkzeugleiste",legend:"Dr체cken Sie ${toolbarFocus} auf der Symbolleiste. Gehen Sie zur n채chsten oder vorherigen Symbolleistengruppe mit TAB und SHIFT+TAB. Gehen Sie zur n채chsten oder vorherigen Symbolleiste auf die Schaltfl채che mit dem RECHTS- oder LINKS-Pfeil. Dr체cken Sie die Leertaste oder Eingabetaste, um die Schaltfl채che in der Symbolleiste aktivieren."},
{name:"Editordialog",legend:"Inside a dialog, press TAB to navigate to the next dialog element, press SHIFT+TAB to move to the previous dialog element, press ENTER to submit the dialog, press ESC to cancel the dialog. When a dialog has multiple tabs, the tab list can be reached either with ALT+F10 or with TAB as part of the dialog tabbing order. With tab list focused, move to the next and previous tab with RIGHT and LEFT ARROW, respectively."},{name:"Editor-Kontextmen체",legend:"D체rcken Sie ${contextMenu} oder die Anwendungstaste um das Kontextmen체 zu 철ffnen. Man kann die Pfeiltasten zum Wechsel benutzen. Mit der Leertaste oder der Enter-Taste kann man den Men체punkt aufrufen. Schliessen Sie das Kontextmen체 mit der ESC-Taste."},
{name:"Editor-Listenbox",legend:"Innerhalb einer Listenbox kann man mit der TAB-Taste oder den Pfeilrunter-Taste den n채chsten Men체eintrag w채hlen. Mit der SHIFT+TAB Tastenkombination oder der Pfeilhoch-Taste gelangt man zum vorherigen Men체punkt. Mit der Leertaste oder Enter kann man den Men체punkt ausw채hlen. Dr체cken Sie ESC zum Verlassen des Men체s."},{name:"Editor-Elementpfadleiste",legend:"Dr체cken Sie ${elementsPathFocus} um sich durch die Pfadleiste zu bewegen. Um zum n채chsten Element zu gelangen dr체cken Sie TAB oder die Pfeilrechts-Taste. Zum vorherigen Element gelangen Sie mit der SHIFT+TAB oder der Pfeillinks-Taste. Dr체cken Sie die Leertaste oder Enter um das Element auszuw채hlen."}]},
{name:"Befehle",items:[{name:"R체ckg채ngig-Befehl",legend:"Dr체cken Sie ${undo}"},{name:"Wiederherstellen-Befehl",legend:"Dr체cken Sie ${redo}"},{name:"Fettschrift-Befehl",legend:"Dr체cken Sie ${bold}"},{name:"Kursiv-Befehl",legend:"Dr체cken Sie ${italic}"},{name:"Unterstreichen-Befehl",legend:"Dr체cken Sie ${underline}"},{name:"Link-Befehl",legend:"Dr체cken Sie ${link}"},{name:"Werkzeugleiste einklappen-Befehl",legend:"Dr체cken Sie ${toolbarCollapse}"},{name:"Zugang bisheriger Fokussierung Raumbefehl ",legend:"Dr체cken Sie ${accessPreviousSpace}  auf den am n채chsten nicht erreichbar Fokus-Abstand vor die Einf체gemarke zugreifen: zwei benachbarte HR-Elemente. Wiederholen Sie die Tastenkombination um entfernte Fokusr채ume zu erreichen. "},
{name:"Zugang n채chster Schwerpunkt Raumbefehl ",legend:"Dr체cken Sie $ { accessNextSpace }, um den n채chsten unerreichbar Fokus Leerzeichen nach dem Cursor zum Beispiel auf: zwei benachbarten HR Elemente. Wiederholen Sie die Tastenkombination zum fernen Fokus Bereiche zu erreichen. "},{name:"Eingabehilfen",legend:"Dr체cken Sie ${a11yHelp}"}]}],backspace:"R체cktaste",tab:"Tab",enter:"Eingabe",shift:"Umschalt",ctrl:"Strg",alt:"Alt",pause:"Pause",capslock:"Feststell",escape:"Escape",pageUp:"Bild auf",pageDown:"Bild ab",
end:"Ende",home:"Pos1",leftArrow:"Linke Pfeiltaste",upArrow:"Obere Pfeiltaste",rightArrow:"Rechte Pfeiltaste",downArrow:"Untere Pfeiltaste",insert:"Einf체gen","delete":"Entfernen",leftWindowKey:"Linke Windowstaste",rightWindowKey:"Rechte Windowstaste",selectKey:"Taste ausw채hlen",numpad0:"Ziffernblock 0",numpad1:"Ziffernblock 1",numpad2:"Ziffernblock 2",numpad3:"Ziffernblock 3",numpad4:"Ziffernblock 4",numpad5:"Ziffernblock 5",numpad6:"Ziffernblock 6",numpad7:"Ziffernblock 7",numpad8:"Ziffernblock 8",
numpad9:"Ziffernblock 9",multiply:"Multiplizieren",add:"Addieren",subtract:"Subtrahieren",decimalPoint:"Punkt",divide:"Dividieren",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Ziffernblock feststellen",scrollLock:"Rollen",semiColon:"Semikolon",equalSign:"Gleichheitszeichen",comma:"Komma",dash:"Bindestrich",period:"Punkt",forwardSlash:"Schr채gstrich",graveAccent:"Gravis",openBracket:"횜ffnende eckige Klammer",backSlash:"R체ckw채rtsgewandter Schr채gstrich",
closeBracket:"Schliessende eckige Klammer",singleQuote:"Einfaches Anf체hrungszeichen"});