/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","fr",{title:"Instructions d'accessibilit챕",contents:"Contenu de l'aide. Pour fermer ce dialogue, appuyez sur la touche 횋CHAP (Echappement).",legend:[{name:"G챕n챕ral",items:[{name:"Barre d'outils de l'챕diteur",legend:"Appuyer sur ${toolbarFocus} pour acc챕der 횪 la barre d'outils. Se d챕placer vers les groupes suivant ou pr챕c챕dent de la barre d'outil avec les touches MAJ et MAJ+TAB. Se d챕placer vers les boutons suivant ou pr챕c챕dent de la barre d'outils avec les touches FL횊CHE DROITE et FL횊CHE GAUCHE. Appuyer sur la barre d'espace ou la touche ENTR횋E pour activer le bouton de barre d'outils."},
{name:"Dialogue de l'챕diteur",legend:"Dans un dialogue, appuyer sur TAB pour aller 횪 l'챕l챕ment suivant du dialogue, appuyer sur MAJ+TAB pour aller 횪 l'챕l챕ment pr챕c챕dent du dialogue, appuyer sur ECHAP pour annuler le dialogue. Quand un dialogue a de multiples onglets, on peut acc챕der 횪 la liste des onglets avec ALT+F10 ou avec TAB. Dans la liste des onglets, se d챕placer vers le suivant ou le pr챕c챕dent avec les FLECHES DROITE et GAUCHE respectivement."},{name:"Menu contextuel de l'챕diteur",legend:"Appuyer sur ${contextMenu} ou entrer le RACCOURCI CLAVIER pour ouvrir le menu contextuel. Puis se d챕placer vers l'option suivante du menu avec les touches TAB ou FL횊CHE BAS. Se d챕placer vers l'option pr챕c챕dente avec les touches  MAJ+TAB ou FL횊CHE HAUT. appuyer sur la BARRE D'ESPACE ou la touche ENTR횋E pour s챕lectionner l'option du menu. Oovrir le sous-menu de l'option courante avec la BARRE D'ESPACE ou les touches ENTR횋E ou FL횊CHE DROITE. Revenir 횪 l'챕l챕ment de menu parent avec les touches 횋CHAP ou FL횊CHE GAUCHE. Fermer le menu contextuel avec 횋CHAP."},
{name:"Zone de liste de l'챕diteur",legend:"Dans la liste en menu d챕roulant, se d챕placer vers l'챕l챕ment suivant de la liste avec les touches TAB ou FL횊CHE BAS. Se d챕placer vers l'챕l챕ment pr챕c챕dent de la liste avec les touches MAJ+TAB ou FL횊CHE HAUT. Appuyer sur la BARRE D'ESPACE ou sur ENTR횋E pour s챕lectionner l'option dans la liste. Appuyer sur 횋CHAP pour fermer le menu d챕roulant."},{name:"Barre d'emplacement des 챕l챕ments de l'챕diteur",legend:"Appuyer sur ${elementsPathFocus} pour naviguer vers la barre d'emplacement des 챕l챕ments de l'챕diteur. Se d챕placer vers le bouton d'챕l챕ment suivant avec les touches TAB ou FL횊CHE DROITE. Se d챕placer vers le bouton d'챕l챕ment pr챕c챕dent avec les touches MAJ+TAB ou FL횊CHE GAUCHE. Appuyer sur la BARRE D'ESPACE ou sur ENTR횋E pour s챕lectionner l'챕l챕ment dans l'챕diteur."}]},
{name:"Commandes",items:[{name:" Annuler la commande",legend:"Appuyer sur ${undo}"},{name:"Refaire la commande",legend:"Appuyer sur ${redo}"},{name:" Commande gras",legend:"Appuyer sur ${bold}"},{name:" Commande italique",legend:"Appuyer sur ${italic}"},{name:" Commande soulign챕",legend:"Appuyer sur ${underline}"},{name:" Commande lien",legend:"Appuyer sur ${link}"},{name:" Commande enrouler la barre d'outils",legend:"Appuyer sur ${toolbarCollapse}"},{name:"Acc챕der 횪 la pr챕c챕dente commande d'espace de mise au point",
legend:"Appuyez sur ${accessPreviousSpace} pour acc챕der 횪 l'espace hors d'atteinte le plus proche avant le caret, par exemple: deux 챕l챕ments HR adjacents. R챕p챕tez la combinaison de touches pour atteindre les espaces de mise au point distants."},{name:"Acc챔s 횪 la prochaine commande de l'espace de mise au point",legend:"Appuyez sur ${accessNextSpace} pour acc챕der au plus proche espace de mise au point hors d'atteinte apr챔s le caret, par exemple: deux 챕l챕ments HR adjacents. r챕p챕tez la combinaison de touches pour atteindre les espace de mise au point distants."},
{name:" Aide Accessibilit챕",legend:"Appuyer sur ${a11yHelp}"}]}],backspace:"Retour arri챔re",tab:"Tabulation",enter:"Entr챕e",shift:"Majuscule",ctrl:"Ctrl",alt:"Alt",pause:"Pause",capslock:"Verr. Maj.",escape:"횋chap",pageUp:"Page sup챕rieure",pageDown:"Page inf챕rieure",end:"Fin",home:"Retour",leftArrow:"Fl챔che gauche",upArrow:"Fl챔che haute",rightArrow:"Fl챔che droite",downArrow:"Fl챔che basse",insert:"Insertion","delete":"Supprimer",leftWindowKey:"Touche Windows gauche",rightWindowKey:"Touche Windows droite",
selectKey:"Touche menu",numpad0:"Pav챕 num챕rique 0",numpad1:"Pav챕 num챕rique 1",numpad2:"Pav챕 num챕rique 2",numpad3:"Pav챕 num챕rique 3",numpad4:"Pav챕 num챕rique 4",numpad5:"Pav챕 num챕rique 5",numpad6:"Pav챕 num챕rique 6",numpad7:"Pav챕 num챕rique 7",numpad8:"Pav챕 num챕rique 8",numpad9:"Pav챕 num챕rique 9",multiply:"Multiplier",add:"Addition",subtract:"Soustraire",decimalPoint:"Point d챕cimal",divide:"Diviser",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",
numLock:"Verrouillage num챕rique",scrollLock:"Arr챗t d챕filement",semiColon:"Point virgule",equalSign:"Signe 챕gal",comma:"Virgule",dash:"Tiret",period:"Point",forwardSlash:"Barre oblique",graveAccent:"Accent grave",openBracket:"Parenth챔se ouvrante",backSlash:"Barre oblique inverse",closeBracket:"Parenth챔se fermante",singleQuote:"Apostrophe"});