/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","hu",{title:"Kiseg챠t흷 utas챠t찼sok",contents:"S첬g처 tartalmak. A p찼rbesz챕dablak bez찼r찼s찼hoz nyomjon ESC-et.",legend:[{name:"횁ltal찼nos",items:[{name:"Szerkeszt흷 Eszk철zt찼r",legend:"Nyomjon ${toolbarFocus} hogy kijel철lje az eszk철zt찼rat. A k철vetkez흷 챕s el흷z흷 eszk철zt찼r csoporthoz a TAB 챕s SHIFT+TAB-al juthat el. A k철vetkez흷 챕s el흷z흷 eszk철zt찼r gombhoz a BAL NY횒L vagy JOBB NY횒L gombbal juthat el. Nyomjon SPACE-t vagy ENTER-t hogy aktiv찼lja az eszk철zt찼r gombot."},{name:"Szerkesz흷 p찼rbesz챕d ablak",
legend:"Inside a dialog, press TAB to navigate to the next dialog element, press SHIFT+TAB to move to the previous dialog element, press ENTER to submit the dialog, press ESC to cancel the dialog. When a dialog has multiple tabs, the tab list can be reached either with ALT+F10 or with TAB as part of the dialog tabbing order. With tab list focused, move to the next and previous tab with RIGHT and LEFT ARROW, respectively."},{name:"Szerkeszt흷 helyi men체",legend:"Nyomjon ${contextMenu}-t vagy ALKALMAZ횁S BILLENTY키T a helyi men체 megnyit찼s찼hoz. Ezut찼n a k철vetkez흷 men체pontra l챕phet a TAB vagy LEFEL횋 NY횒LLAL. Az el흷z흷 opci처t a SHIFT+TAB vagy FELFEL횋 NY횒LLAL 챕rheti el. Nyomjon SPACE-t vagy ENTER-t a men체pont kiv찼laszt찼s찼hoz. A jelenlegi men체pont almen체j챕nek megnyit찼s찼hoz nyomjon SPACE-t vagy ENTER-t, vagy JOBB NYILAT. A f흷men체h철z val처 visszat챕r챕shez nyomjon ESC-et vagy BAL NYILAT. A helyi men체 bez찼r찼sa az ESC billenty킥vel lehets챕ges."},
{name:"Szerkeszt흷 lista",legend:"A list찼n bel체l a k철vetkez흷 elemre a TAB vagy LEFEL횋 NY횒LLAL mozoghat. Az el흷z흷 elem kiv찼laszt찼s찼hoz nyomjon SHIFT+TAB-ot vagy FELFEL횋 NYILAT. Nyomjon SPACE-t vagy ENTER-t az elem kiv찼laszt찼s찼hoz. Az ESC billenty킥 megnyom찼s찼val bez찼rhatja a list찼t."},{name:"Szerkeszt흷 elem utak s찼v",legend:"Nyomj ${elementsPathFocus} hogy kijel철ld a elemek 첬t s찼vj찼t. A k철vetkez흷 elem gombhoz a TAB-al vagy a JOBB NY횒LLAL juthatsz el. Az el흷z흷 gombhoz a SHIFT+TAB vagy BAL NY횒LLAL mehetsz. A SPACE vagy ENTER billenty킥vel kiv찼laszthatod az elemet a szerkeszt흷ben."}]},
{name:"Parancsok",items:[{name:"Parancs visszavon찼sa",legend:"Nyomj ${undo}"},{name:"Parancs megism챕tl챕se",legend:"Nyomjon ${redo}"},{name:"F챕lk철v챕r parancs",legend:"Nyomjon ${bold}"},{name:"D흷lt parancs",legend:"Nyomjon ${italic}"},{name:"Al찼h첬zott parancs",legend:"Nyomjon ${underline}"},{name:"Link parancs",legend:"Nyomjon ${link}"},{name:"Szerkeszt흷s찼v 철sszecsuk찼sa parancs",legend:"Nyomjon ${toolbarCollapse}"},{name:"Hozz찼f챕r챕s az el흷z흷 f처kusz helyhez parancs",legend:"Nyomj ${accessNextSpace} hogy hozz찼f챕rj a legk철zelebbi el챕rhetetlen f처kusz helyhez a hi찼nyjel el흷tt, p챕ld찼ul: k챕t szomsz챕dos HR elemhez. Ism챕teld meg a billenty킥kombin찼ci처t hogy megtal찼ld a t찼volabbi f처kusz helyeket."},
{name:"Hozz찼f챕r챕s a k철vetkez흷 f처kusz helyhez parancs",legend:"Nyomj ${accessNextSpace} hogy hozz찼f챕rj a legk철zelebbi el챕rhetetlen f처kusz helyhez a hi찼nyjel ut찼n, p챕ld찼ul: k챕t szomsz챕dos HR elemhez. Ism챕teld meg a billenty킥kombin찼ci처t hogy megtal찼ld a t찼volabbi f처kusz helyeket."},{name:"Kiseg챠t흷 s첬g처",legend:"Nyomjon ${a11yHelp}"}]}],backspace:"Backspace",tab:"Tab",enter:"Enter",shift:"Shift",ctrl:"Ctrl",alt:"Alt",pause:"Pause",capslock:"Caps Lock",escape:"Escape",pageUp:"Page Up",pageDown:"Page Down",
end:"End",home:"Home",leftArrow:"balra ny챠l",upArrow:"felfel챕 ny챠l",rightArrow:"jobbra ny챠l",downArrow:"lefel챕 ny챠l",insert:"Insert","delete":"Delete",leftWindowKey:"bal Windows-billenty킥",rightWindowKey:"jobb Windows-billenty킥",selectKey:"Billenty킥 v찼laszt찼sa",numpad0:"Sz찼mbillenty킥k 0",numpad1:"Sz찼mbillenty킥k 1",numpad2:"Sz찼mbillenty킥k 2",numpad3:"Sz찼mbillenty킥k 3",numpad4:"Sz찼mbillenty킥k 4",numpad5:"Sz찼mbillenty킥k 5",numpad6:"Sz찼mbillenty킥k 6",numpad7:"Sz찼mbillenty킥k 7",numpad8:"Sz찼mbillenty킥k 8",
numpad9:"Sz찼mbillenty킥k 9",multiply:"Szorz찼s",add:"Hozz찼ad찼s",subtract:"Kivon찼s",decimalPoint:"Tizedespont",divide:"Oszt찼s",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Num Lock",scrollLock:"Scroll Lock",semiColon:"Pontosvessz흷",equalSign:"Egyenl흷s챕gjel",comma:"Vessz흷",dash:"K철t흷jel",period:"Pont",forwardSlash:"Perjel",graveAccent:"Visszafel챕 d흷l흷 챕kezet",openBracket:"Nyit처 sz철gletes z찼r처jel",backSlash:"ford챠tott perjel",closeBracket:"Z찼r처 sz철gletes z찼r처jel",
singleQuote:"szimpla id챕z흷jel"});