/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","km",{title:"Accessibility Instructions",contents:"�옒�왃�옃�왅���왃�뗡엲�웺�옋�왌�옓�윍 �엸�왍�옒�윊�옍�왆�뗡옍�왅�옉�뗡옎�윊�옉�왃�웺�엫�뗡옋�웳�웻 �옝�왋�옒�뗡엯�왊�엯 ESC �윍",legend:[{name:"�옉�왋�옉�웷",items:[{name:"�옔�옍�왃�옔�뗡옧�옍���옔�옂�윂�뗡��옒�윊�옒�옖�왅�옊�왆�뗡옋�왅�옏�옋�윊�옊",legend:"Press ${toolbarFocus} to navigate to the toolbar. Move to the next and previous toolbar group with TAB and SHIFT+TAB. Move to the next and previous toolbar button with RIGHT ARROW or LEFT ARROW. Press SPACE or ENTER to activate the toolbar button."},{name:"�옎�윊�옉�왃�웺�엫�뗡��옒�윊�옒�옖�왅�옊�왆�옋�왅�옏�옋�윊�옊",legend:"Inside a dialog, press TAB to navigate to the next dialog element, press SHIFT+TAB to move to the previous dialog element, press ENTER to submit the dialog, press ESC to cancel the dialog. When a dialog has multiple tabs, the tab list can be reached either with ALT+F10 or with TAB as part of the dialog tabbing order. With tab list focused, move to the next and previous tab with RIGHT and LEFT ARROW, respectively."},
{name:"�옒�웾�왆�옋�왊�옓�옍�옔�왅�옍�옉�옠�윊�옋�����웴�옝�옒�윊�옔�왌�옕",legend:"Press ${contextMenu} or APPLICATION KEY to open context-menu. Then move to next menu option with TAB or DOWN ARROW. Move to previous option with SHIFT+TAB or UP ARROW. Press SPACE or ENTER to select the menu option. Open sub-menu of current option with SPACE or ENTER or RIGHT ARROW. Go back to parent menu item with ESC or LEFT ARROW. Close context menu with ESC."},{name:"�옍�윊�옔�옠�옍�윀�옍�엵�윊�엲�왆�옠�윊�옋�����웴�옝�옒�윊�옔�왌�옕",legend:"Inside a list-box, move to next list item with TAB OR DOWN ARROW. Move to previous list item with SHIFT+TAB or UP ARROW. Press SPACE or ENTER to select the list option. Press ESC to close the list-box."},
{name:"Editor Element Path Bar",legend:"Press ${elementsPathFocus} to navigate to the elements path bar. Move to next element button with TAB or RIGHT ARROW. Move to previous button with SHIFT+TAB or LEFT ARROW. Press SPACE or ENTER to select the element in editor."}]},{name:"�옏�왃���윊�옓�옍�엵�윊�엲�왃",items:[{name:"���왃�옔�뗡옍�엵�윊�엲�왃�뗡옒�왅�옋�옊�윊�옖�왍�옖�왅�엵",legend:"�엯�왊�엯 ${undo}"},{name:"���왃�옔�옍�엵�윊�엲�왃�뗡옊�윊�옖�왍�옖�왅�엵",legend:"�엯�왊�엯 ${redo}"},{name:"���왃�옔�옍�엵�윊�엲�왃�뗡옠���윊�옝�옔�뗡엸�왅�옃",legend:"�엯�왊�엯 ${bold}"},{name:"���왃�옔�옍�엵�윊�엲�왃�뗡옠���윊�옝�옔�뗡옉�윊�옔�웳�옃",legend:"�엯�왊�엯 ${italic}"},{name:"�옏�왃���윊�옓�옍�엵�윊�엲�왃�뗡옍�옋�윊�옉�왃�옃�윀�뗡옏�왆���윊�옔�웶�옒",
legend:"�엯�왊�엯 ${underline}"},{name:"�옏�왃���윊�옓�옍�엵�윊�엲�왃�뗡옃�웺�옂",legend:"�엯�왊�엯 ${link}"},{name:" Toolbar Collapse command",legend:"Press ${toolbarCollapse}"},{name:" Access previous focus space command",legend:"Press ${accessPreviousSpace} to access the closest unreachable focus space before the caret, for example: two adjacent HR elements. Repeat the key combination to reach distant focus spaces."},{name:" Access next focus space command",legend:"Press ${accessNextSpace} to access the closest unreachable focus space after the caret, for example: two adjacent HR elements. Repeat the key combination to reach distant focus spaces."},
{name:"�엲�웺�옋�왌�옓�뗡옏�왆�뗡옑�왃�옏�뗡엫�왃�옓�옝�윊�옔�왌�옕",legend:"�엲�왌�옓 ${a11yHelp}"}]}],backspace:"�옕�왊�옍�옄�옓���윊�옔�웶�옓",tab:"Tab",enter:"Enter",shift:"Shift",ctrl:"Ctrl",alt:"Alt",pause:"�옎�윊�옠�왃��",capslock:"Caps Lock",escape:"�엯�왃���엯�웳�엵",pageUp:"�옉�웺�옏�윇�옔�뗡옕�왍",pageDown:"�옉�웺�옏�윇�옔�뗡��윊�옔�웶�옒",end:"�엯�왊�엫",home:"�옎�윊�옉�웻",leftArrow:"�옏�윊�옔�왌�엵�뗡엱�윊�옖�웳�엫",upArrow:"�옏�윊�옔�왌�엵�뗡옕�왍",rightArrow:"�옏�윊�옔�왌�엵�뗡옝�윊�엸�왃�웺",downArrow:"�옏�윊�옔�왌�엵�뗡��윊�옔�웶�옒",insert:"�옍�엵�윊�엯�왋�옕","delete":"�옕�왊�옍",leftWindowKey:"Left Windows key",rightWindowKey:"Right Windows key",selectKey:"�엲�윊�옔�왍�옝�뗡엩�윊�옔�왃�옍�윀�뗡엯�왊�엯",numpad0:"Numpad 0",numpad1:"Numpad 1",
numpad2:"Numpad 2",numpad3:"Numpad 3",numpad4:"Numpad 4",numpad5:"Numpad 5",numpad6:"Numpad 6",numpad7:"Numpad 7",numpad8:"Numpad 8",numpad9:"Numpad 9",multiply:"�엩�왊�옂",add:"�옍�옋�윊�옄�웴�옒",subtract:"�엸��",decimalPoint:"�엯�웺�옂�왊�엯�옉�옝�옑�왃�엩",divide:"�엯�웴��",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Num Lock",scrollLock:"�옍�왅�옉�뗡옔�웺���왅�옕",semiColon:"�엯�왊�엯�뗡��윊�옍���옝",equalSign:"�옝�엵�윊�엵�왃�뗡옠�왉�옔�웾�왋",comma:"���윊�옍���옝",dash:"Dash",period:"�엯�왊�엯",forwardSlash:"Forward Slash",graveAccent:"Grave Accent",
openBracket:"�옃�엫�윊�����옍�뗡옍�왍��",backSlash:"Backslash",closeBracket:"�옃�엫�윊�����옍�뗡옍�왅�옉",singleQuote:"�옍�옋�윊�옃���윀�뗡옒�왌�옓"});