/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","lv",{title:"Pieejam카bas instrukcija",contents:"Pal카dz카bas saturs. Lai aizv휆rtu ciet 큄o dialogu nospiediet ESC.",legend:[{name:"Galvenais",items:[{name:"Redaktora r카kjosla",legend:"Nospiediet ${toolbarFocus} lai p훮rvietotos uz r카kjoslu. Lai p훮rvietotos uz n훮ko큄o vai iepriek큄휆jo r카kjoslas grupu izmantojiet pogu TAB un SHIFT+TAB. Lai p훮rvietotos uz n훮ko큄o vai iepriek큄휆jo r카kjoslas pogu izmantojiet Kreiso vai Labo bulti흨u. Nospiediet Atstarpi vai ENTER lai aktiviz휆tu r카kjosla pogu."},
{name:"Redaktora dialoga  logs",legend:"Inside a dialog, press TAB to navigate to the next dialog element, press SHIFT+TAB to move to the previous dialog element, press ENTER to submit the dialog, press ESC to cancel the dialog. When a dialog has multiple tabs, the tab list can be reached either with ALT+F10 or with TAB as part of the dialog tabbing order. With tab list focused, move to the next and previous tab with RIGHT and LEFT ARROW, respectively."},{name:"Redaktora satura izv휆le",legend:"Nospiediet ${contextMenu} vai APPLICATION KEY lai atv휆rtu satura izv휆lni. Lai p훮rvietotos uz n훮ko큄o izv휆lnes opciju izmantojiet pogu TAB vai pogu Bulti흨u uz leju. Lai p훮rvietotos uz iepriek큄휆jo opciju izmantojiet  SHIFT+TAB vai pogu Bulti흨a uz aug큄u. Nospiediet SPACE vai ENTER lai izvel휆tos izv휆lnes opciju. Atveriet teko큄aj훮 opcija apak큄izv휆lni ar SAPCE vai ENTER ka ari to var izdar카t ar Labo bulti흨u. Lai atgrieztos atpaka캬 uz sakuma izv휆lni nospiediet ESC vai Kreiso bulti흨u. Lai aizv휆rtu ciet izv휆lnes saturu nospiediet ESC."},
{name:"Redaktora saraksta lauks",legend:"Saraksta lauk훮, lai p훮rvietotos uz n훮ko큄o saraksta elementu nospiediet TAB vai pogu Bulti흨a uz leju. Lai p훮rvietotos uz iepriek큄휆jo saraksta elementu nospiediet SHIFT+TAB vai pogu Bulti흨a uz aug큄u. Nospiediet SPACE vai ENTER lai izv휆l휆tos saraksta opcijas. Nospiediet ESC lai aizv휆rtu saraksta lauku."},{name:"Redaktora elementa ce캬a josla",legend:"Nospiediet ${elementsPathFocus} lai p훮rvietotos uz elementa ce캬a joslu. Lai p훮rvietotos uz n훮ko큄o elementa pogu izmantojiet TAB vai Labo bulti흨u. Lai p훮rvietotos uz iepriek큄휆jo elementa pogu izmantojiet SHIFT+TAB vai Kreiso bulti흨u. Nospiediet SPACE vai ENTER lai izv휆l휆tos elementu redaktor훮."}]},
{name:"Komandas",items:[{name:"Komanda atcelt darb카bu",legend:"Nospiediet ${undo}"},{name:"Komanda atk훮rtot darb카bu",legend:"Nospiediet ${redo}"},{name:"Treknraksta komanda",legend:"Nospiediet ${bold}"},{name:"Kurs카va komanda",legend:"Nospiediet ${italic}"},{name:"Apak큄sv카tras komanda ",legend:"Nospiediet ${underline}"},{name:"Hipersaites komanda",legend:"Nospiediet ${link}"},{name:"R카kjoslas aizv휆r큄anas komanda",legend:"Nospiediet ${toolbarCollapse}"},{name:"Piek캬큰t iepriek큄휆jai fokusa vietas komandai",
legend:"Nospiediet ${accessPreviousSpace} lai piek캬큰tu tuv훮kajai nepieejamajai fokusa vietai pirms kursora. Piem휆ram: diviem blakus eso큄iem l카nijas HR elementiem. Atk훮rtojiet tausti흨u kombin훮ciju lai piek캬큰tu pie t훮l훮k훮m viet훮m."},{name:"Piek캬큰t n훮ko큄훮 fokusa apgabala komandai",legend:"Nospiediet ${accessNextSpace} lai piek캬큰tu tuv훮kajai nepieejamajai fokusa vietai p휆c kursora. Piem휆ram: diviem blakus eso큄iem l카nijas HR elementiem. Atk훮rtojiet tausti흨u kombin훮ciju lai piek캬큰tu pie t훮l훮k훮m viet훮m."},
{name:"Pieejam카bas pal카dz카ba",legend:"Nospiediet ${a11yHelp}"}]}],backspace:"Backspace",tab:"Tab",enter:"Enter",shift:"Shift",ctrl:"Ctrl",alt:"Alt",pause:"Pause",capslock:"Caps Lock",escape:"Escape",pageUp:"Page Up",pageDown:"Page Down",end:"End",home:"Home",leftArrow:"Left Arrow",upArrow:"Up Arrow",rightArrow:"Right Arrow",downArrow:"Down Arrow",insert:"Insert","delete":"Delete",leftWindowKey:"Left Windows key",rightWindowKey:"Right Windows key",selectKey:"Select key",numpad0:"Numpad 0",numpad1:"Numpad 1",
numpad2:"Numpad 2",numpad3:"Numpad 3",numpad4:"Numpad 4",numpad5:"Numpad 5",numpad6:"Numpad 6",numpad7:"Numpad 7",numpad8:"Numpad 8",numpad9:"Numpad 9",multiply:"Multiply",add:"Add",subtract:"Subtract",decimalPoint:"Decimal Point",divide:"Divide",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Num Lock",scrollLock:"Scroll Lock",semiColon:"Semicolon",equalSign:"Equal Sign",comma:"Comma",dash:"Dash",period:"Period",forwardSlash:"Forward Slash",
graveAccent:"Grave Accent",openBracket:"Open Bracket",backSlash:"Backslash",closeBracket:"Close Bracket",singleQuote:"Single Quote"});