/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","pl",{title:"Instrukcje dotycz훳ce dost휌pno힄ci",contents:"Zawarto힄훶 pomocy. Wci힄nij ESC, aby zamkn훳훶 to okno.",legend:[{name:"Informacje og처lne",items:[{name:"Pasek narz휌dzi edytora",legend:"Naci힄nij ${toolbarFocus}, by przej힄훶 do paska narz휌dzi. Przejd탄 do nast휌pnej i poprzedniej grupy narz휌dzi u탉ywaj훳c TAB oraz SHIFT+TAB. Przejd탄 do nast휌pnego i poprzedniego przycisku paska narz휌dzi za pomoc훳 STRZA흟KI W PRAWO lub STRZA흟KI W LEWO. Naci힄nij SPACJ휋 lub ENTER by aktywowa훶 przycisk paska narz휌dzi."},
{name:"Okno dialogowe edytora",legend:"Wewn훳trz okna dialogowego naci힄nij TAB, by przej힄훶 do kolejnego elementu tego okna lub SHIFT+TAB, by przej힄훶 do poprzedniego elementu okna. Naci힄nij ENTER w celu zatwierdzenia opcji okna dialogowego lub ESC w celu anulowania zmian. Je힄li okno dialogowe ma kilka zak흢adek, do listy zak흢adek mo탉na przej힄훶 za pomoc훳 ALT+F10 lub TAB. Gdy lista zak흢adek jest aktywna, mo탉esz przej힄훶 do kolejnej i poprzedniej zak흢adki za pomoc훳 STRZA흟KI W PRAWO i STRZA흟KI W LEWO."},
{name:"Menu kontekstowe edytora",legend:"Wci힄nij ${contextMenu} lub PRZYCISK APLIKACJI aby otworzy훶 menu kontekstowe. Przejd탄 do nast휌pnej pozycji menu wciskaj훳c TAB lub STRZA흟K휋 W D횙흟. Przejd탄 do poprzedniej pozycji menu wciskaj훳c SHIFT + TAB lub STRZA흟K휋 W G횙R휋. Wci힄nij SPACJ휋 lub ENTER aby wygra훶 pozycj휌 menu. Otw처rz pod-menu obecnej pozycji wciskaj훳c SPACJ휋 lub ENTER lub STRZA흟K휋 W PRAWO. Wr처훶 do pozycji nadrz휌dnego menu wciskaj훳c ESC lub STRZA흟K휋 W LEWO. Zamknij menu wciskaj훳c ESC."},{name:"Lista w edytorze",
legend:"Wewn훳trz listy przejd탄 do kolejnego elementu listy za pomoc훳 przycisku TAB lub STRZA흟KI W D횙흟. Przejd탄 do poprzedniego elementu listy za pomoc훳 SHIFT+TAB lub STRZA흟KI W G횙R휋. Naci힄nij SPACJ휋 lub ENTER w celu wybrania opcji z listy. Naci힄nij ESC, by zamkn훳훶 list휌."},{name:"Pasek 힄cie탉ki element처w edytora",legend:"Naci힄nij ${elementsPathFocus} w celu przej힄cia do paska 힄cie탉ki element처w edytora. W celu przej힄cia do kolejnego elementu naci힄nij klawisz TAB lub STRZA흟KI W PRAWO. W celu przej힄cia do poprzedniego elementu naci힄nij klawisze SHIFT+TAB lub STRZA흟KI W LEWO. By wybra훶 element w edytorze, u탉yj klawisza SPACJI lub ENTER."}]},
{name:"Polecenia",items:[{name:"Polecenie Cofnij",legend:"Naci힄nij ${undo}"},{name:"Polecenie Pon처w",legend:"Naci힄nij ${redo}"},{name:"Polecenie Pogrubienie",legend:"Naci힄nij ${bold}"},{name:"Polecenie Kursywa",legend:"Naci힄nij ${italic}"},{name:"Polecenie Podkre힄lenie",legend:"Naci힄nij ${underline}"},{name:"Polecenie Wstaw/ edytuj odno힄nik",legend:"Naci힄nij ${link}"},{name:"Polecenie schowaj pasek narz휌dzi",legend:"Naci힄nij ${toolbarCollapse}"},{name:" Access previous focus space command",legend:"Press ${accessPreviousSpace} to access the closest unreachable focus space before the caret, for example: two adjacent HR elements. Repeat the key combination to reach distant focus spaces."},
{name:" Access next focus space command",legend:"Press ${accessNextSpace} to access the closest unreachable focus space after the caret, for example: two adjacent HR elements. Repeat the key combination to reach distant focus spaces."},{name:"Pomoc dotycz훳ca dost휌pno힄ci",legend:"Naci힄nij ${a11yHelp}"}]}],backspace:"Backspace",tab:"Tab",enter:"Enter",shift:"Shift",ctrl:"Ctrl",alt:"Alt",pause:"Pause",capslock:"Caps Lock",escape:"Escape",pageUp:"Page Up",pageDown:"Page Down",end:"End",home:"Home",leftArrow:"Strza흢ka w lewo",
upArrow:"Strza흢ka w g처r휌",rightArrow:"Strza흢ka w prawo",downArrow:"Strza흢ka w d처흢",insert:"Insert","delete":"Delete",leftWindowKey:"Lewy klawisz Windows",rightWindowKey:"Prawy klawisz Windows",selectKey:"Klawisz wyboru",numpad0:"Klawisz 0 na klawiaturze numerycznej",numpad1:"Klawisz 1 na klawiaturze numerycznej",numpad2:"Klawisz 2 na klawiaturze numerycznej",numpad3:"Klawisz 3 na klawiaturze numerycznej",numpad4:"Klawisz 4 na klawiaturze numerycznej",numpad5:"Klawisz 5 na klawiaturze numerycznej",
numpad6:"Klawisz 6 na klawiaturze numerycznej",numpad7:"Klawisz 7 na klawiaturze numerycznej",numpad8:"Klawisz 8 na klawiaturze numerycznej",numpad9:"Klawisz 9 na klawiaturze numerycznej",multiply:"Przemn처탉",add:"Plus",subtract:"Minus",decimalPoint:"Separator dziesi휌tny",divide:"Podziel",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Num Lock",scrollLock:"Scroll Lock",semiColon:"힃rednik",equalSign:"Znak r처wno힄ci",comma:"Przecinek",dash:"Pauza",
period:"Kropka",forwardSlash:"Uko힄nik prawy",graveAccent:"Akcent s흢aby",openBracket:"Nawias kwadratowy otwieraj훳cy",backSlash:"Uko힄nik lewy",closeBracket:"Nawias kwadratowy zamykaj훳cy",singleQuote:"Apostrof"});