/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","pt-br",{title:"Instru챌천es de Acessibilidade",contents:"Conte첬do da Ajuda. Para fechar este di찼logo pressione ESC.",legend:[{name:"Geral",items:[{name:"Barra de Ferramentas do Editor",legend:"Pressione ${toolbarFocus} para navegar para a barra de ferramentas. Mova para o anterior ou pr처ximo grupo de ferramentas com TAB e SHIFT+TAB. Mova para o anterior ou pr처ximo bot찾o com SETA PARA DIREITA or SETA PARA ESQUERDA. Pressione ESPA횉O ou ENTER para ativar o bot찾o da barra de ferramentas."},
{name:"Di찼logo do Editor",legend:"Dentro de um di찼logo, pressione TAB para navegar para o pr처ximo elemento. Pressione SHIFT+TAB para mover para o elemento anterior. Pressione ENTER ara enviar o di찼logo. pressione ESC para cancelar o di찼logo. Quando um di찼logo tem m첬ltiplas abas, a lista de abas pode ser acessada com ALT+F10 ou TAB, como parte da ordem de tabula챌찾o do di찼logo. Com a lista de abas em foco, mova para a pr처xima aba e para a aba anterior com a SETA DIREITA ou SETA ESQUERDA, respectivamente."},
{name:"Menu de Contexto do Editor",legend:"Pressione ${contextMenu} ou TECLA DE MENU para abrir o menu de contexto, ent찾o mova para a pr처xima op챌찾o com TAB ou SETA PARA BAIXO. Mova para a anterior com SHIFT+TAB ou SETA PARA CIMA. Pressione ESPA횉O ou ENTER para selecionar a op챌찾o do menu. Abra o submenu da op챌찾o atual com ESPA횉O ou ENTER ou SETA PARA DIREITA. Volte para o menu pai com ESC ou SETA PARA ESQUERDA. Feche o menu de contexto com ESC."},{name:"Caixa de Lista do Editor",legend:"Dentro de uma caixa de lista, mova para o pr처ximo item com TAB ou SETA PARA BAIXO. Mova para o item anterior com SHIFT+TAB ou SETA PARA CIMA. Pressione ESPA횉O ou ENTER para selecionar uma op챌찾o na lista. Pressione ESC para fechar a caixa de lista."},
{name:"Barra de Caminho do Elementos do Editor",legend:"Pressione ${elementsPathFocus} para a barra de caminho dos elementos. Mova para o pr처ximo bot찾o de elemento com TAB ou SETA PARA DIREITA. Mova para o bot찾o anterior com SHIFT+TAB ou SETA PARA ESQUERDA. Pressione ESPA횉O ou ENTER para selecionar o elemento no editor."}]},{name:"Comandos",items:[{name:" Comando Desfazer",legend:"Pressione ${undo}"},{name:" Comando Refazer",legend:"Pressione ${redo}"},{name:" Comando Negrito",legend:"Pressione ${bold}"},
{name:" Comando It찼lico",legend:"Pressione ${italic}"},{name:" Comando Sublinhado",legend:"Pressione ${underline}"},{name:" Comando Link",legend:"Pressione ${link}"},{name:" Comando Fechar Barra de Ferramentas",legend:"Pressione ${toolbarCollapse}"},{name:"Acessar o comando anterior de spa챌o de foco",legend:"Pressione ${accessNextSpace} para acessar o espa챌o de foco n찾o alcan챌찼vel mais pr처ximo antes do cursor, por exemplo: dois elementos HR adjacentes. Repita a combina챌찾o de teclas para alcan챌ar espa챌os de foco distantes."},
{name:"Acessar pr처ximo fomando de spa챌o de foco",legend:"Pressione ${accessNextSpace} para acessar o espa챌o de foco n찾o alcan챌찼vel mais pr처ximo ap처s o cursor, por exemplo: dois elementos HR adjacentes. Repita a combina챌찾o de teclas para alcan챌ar espa챌os de foco distantes."},{name:" Ajuda de Acessibilidade",legend:"Pressione ${a11yHelp}"}]}],backspace:"Tecla Backspace",tab:"Tecla Tab",enter:"Enter",shift:"Shift",ctrl:"Ctrl",alt:"Alt",pause:"Pause",capslock:"Caps Lock",escape:"Escape",pageUp:"Page Up",
pageDown:"Page Down",end:"End",home:"Home",leftArrow:"Seta 횪 Esquerda",upArrow:"Seta 횪 Cima",rightArrow:"Seta 횪 Direita",downArrow:"Seta 횪 Baixo",insert:"Insert","delete":"Delete",leftWindowKey:"Tecla do Windows Esquerda",rightWindowKey:"Tecla do Windows Direita",selectKey:"Tecla Selecionar",numpad0:"0 do Teclado Num챕rico",numpad1:"1 do Teclado Num챕rico",numpad2:"2 do Teclado Num챕rico",numpad3:"3 do Teclado Num챕rico",numpad4:"4 do Teclado Num챕rico",numpad5:"5 do Teclado Num챕rico",numpad6:"6 do Teclado Num챕rico",
numpad7:"7 do Teclado Num챕rico",numpad8:"8 do Teclado Num챕rico",numpad9:"9 do Teclado Num챕rico",multiply:"Multiplicar",add:"Mais",subtract:"Subtrair",decimalPoint:"Ponto",divide:"Dividir",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Num Lock",scrollLock:"Scroll Lock",semiColon:"Ponto-e-v챠rgula",equalSign:"Igual",comma:"V챠rgula",dash:"H챠fen",period:"Ponto",forwardSlash:"Barra",graveAccent:"Acento Grave",openBracket:"Abrir Conchetes",
backSlash:"Contra-barra",closeBracket:"Fechar Colchetes",singleQuote:"Aspas Simples"});