/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","pt",{title:"Instru챌천es de acessibilidade",contents:"Conte첬do de ajuda. Use a tecla ESC para fechar esta janela.",legend:[{name:"Geral",items:[{name:"Barra de ferramentas do editor",legend:"Clique em ${toolbarFocus} para navegar para a barra de ferramentas. V찼 para o grupo da barra de ferramentas anterior e seguinte com TAB e SHIFT+TAB. V찼 para o bot찾o da barra de ferramentas anterior com a SETA DIREITA ou ESQUERDA. Pressione ESPA횉O ou ENTER para ativar o bot찾o da barra de ferramentas."},
{name:"Janela do Editor",legend:"Inside a dialog, press TAB to navigate to the next dialog element, press SHIFT+TAB to move to the previous dialog element, press ENTER to submit the dialog, press ESC to cancel the dialog. When a dialog has multiple tabs, the tab list can be reached either with ALT+F10 or with TAB as part of the dialog tabbing order. With tab list focused, move to the next and previous tab with RIGHT and LEFT ARROW, respectively."},{name:"Menu de Contexto do Editor",legend:"Clique em ${contextMenu} ou TECLA APLICA횉횄O para abrir o menu de contexto. Depois v찼 para a op챌찾o do menu seguinte com TAB ou SETA PARA BAIXO. V찼 para a op챌찾o anterior com  SHIFT+TAB ou SETA PARA CIMA. Pressione ESPA횉O ou ENTER para selecionar a op챌찾o do menu.  Abra o submenu da op챌찾o atual com ESPA횉O, ENTER ou SETA DIREITA. GV찼 para o item do menu parente  com ESC ou SETA ESQUERDA. Feche o menu de contexto com ESC."},
{name:"Editor de caixa em lista",legend:"Dentro da caixa da lista, v찼 para o itemda lista seguinte com TAB ou SETA PARA BAIXO. Move V찼 parao item da lista anterior com SHIFT+TAB ou SETA PARA BAIXO. Pressione ESPA횉O ou ENTER para selecionar a op챌찾o da lista. Pressione ESC para fechar a caisa da lista."},{name:"Caminho Barra Elemento Editor",legend:"Clique em ${elementsPathFocus} para navegar para a barra do caminho dos elementos. V찼 para o bot찾o do elemento seguinte com TAB ou SETA DIREITA. V찼 para o bot찾o anterior com SHIFT+TAB ou SETA ESQUERDA. Pressione ESPA횉O ou ENTER para selecionar o elemento no editor."}]},
{name:"Comandos",items:[{name:"Comando de Anular",legend:"Carregar ${undo}"},{name:"Comando de Refazer",legend:"Pressione ${redo}"},{name:"Comando de Negrito",legend:"Pressione ${bold}"},{name:"Comando de It찼lico",legend:"Pressione ${italic}"},{name:"Comando de Sublinhado",legend:"Pressione ${underline}"},{name:"Comando de Hiperliga챌찾o",legend:"Pressione ${link}"},{name:"Comando de Ocultar Barra de Ferramentas",legend:"Pressione ${toolbarCollapse}"},{name:"Acesso comando do espa챌o focus anterior",
legend:"Clique em ${accessPreviousSpace} para aceder ao espa챌o do focos inalcan챌찼vel mais perto antes do sinal de omiss찾o, por exemplo: dois elementos HR adjacentes. Repetir a combina챌찾o da chave para alcan챌ar os espa챌os dos focos distantes."},{name:"Acesso comando do espa챌o focus seguinte",legend:"Pressione ${accessNextSpace} para aceder ao espa챌o do focos inalcan챌찼vel mais perto depois do sinal de omiss찾o, por exemplo: dois elementos HR adjacentes. Repetir a combina챌찾o da chave para alcan챌ar os espa챌os dos focos distantes."},
{name:"Ajuda a acessibilidade",legend:"Pressione ${a11yHelp}"}]}],backspace:"Backspace",tab:"Tab",enter:"Enter",shift:"Shift",ctrl:"Ctrl",alt:"Alt",pause:"Pausa",capslock:"Mai첬sculas",escape:"Esc",pageUp:"Page Up",pageDown:"Page Down",end:"Fim",home:"Entrada",leftArrow:"Seta esquerda",upArrow:"Seta para cima",rightArrow:"Seta direita",downArrow:"Seta para baixo",insert:"Inserir","delete":"Eliminar",leftWindowKey:"Left Windows key",rightWindowKey:"Right Windows key",selectKey:"Select key",numpad0:"Numpad 0",
numpad1:"Numpad 1",numpad2:"Numpad 2",numpad3:"Numpad 3",numpad4:"Numpad 4",numpad5:"Numpad 5",numpad6:"Numpad 6",numpad7:"Numpad 7",numpad8:"Numpad 8",numpad9:"Numpad 9",multiply:"Multiplicar",add:"Adicionar",subtract:"Subtrair",decimalPoint:"Decimal Point",divide:"Divide",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Num Lock",scrollLock:"Scroll Lock",semiColon:"Semicolon",equalSign:"Equal Sign",comma:"V챠rgula",dash:"Dash",period:"Period",
forwardSlash:"Forward Slash",graveAccent:"Acento grave",openBracket:"Open Bracket",backSlash:"Backslash",closeBracket:"Close Bracket",singleQuote:"Single Quote"});