/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","sk",{title:"In큄trukcie pr챠stupnosti",contents:"Pomocn첵 obsah. Pre zatvorenie tohto okna, stla훾te ESC.",legend:[{name:"V큄eobecne",items:[{name:"Li큄ta n찼strojov editora",legend:"Stla훾te ${toolbarFocus} pre navig찼ciu na li큄tu n찼strojov. Medzi 휁al큄ou a predch찼dzaj첬cou li큄tou n찼strojov sa pohybujete s TAB a SHIFT+TAB. Medzi 휁al큄챠m a predch찼dzaj첬cim tla훾idlom na li큄te n찼strojov sa pohybujete s pravou 큄챠pkou a 컁avou 큄챠pkou. Stla훾te medzern챠k alebo ENTER pre aktiv찼ciu tla훾idla li큄ty n찼strojov."},
{name:"Editorov첵 dial처g",legend:"Inside a dialog, press TAB to navigate to the next dialog element, press SHIFT+TAB to move to the previous dialog element, press ENTER to submit the dialog, press ESC to cancel the dialog. When a dialog has multiple tabs, the tab list can be reached either with ALT+F10 or with TAB as part of the dialog tabbing order. With tab list focused, move to the next and previous tab with RIGHT and LEFT ARROW, respectively."},{name:"Editorov챕 kontextov챕 menu",legend:"Stla훾te ${contextMenu} alebo APPLICATION KEY pre otvorenie kontextov챕ho menu. Potom sa pres첬vajte na 휁al큄ie mo탑nosti menu s TAB alebo dolnou 큄챠pkou. Presunte sa k predch찼dzaj첬cej mo탑nosti s SHIFT+TAB alebo hornou 큄챠pkou. Stla훾te medzern챠k alebo ENTER pre v첵ber mo탑nosti menu. Otvorte pod-menu danej mo탑nosti s medzern챠kom, alebo ENTER, alebo pravou 큄챠pkou. Vr찼큐te sa sp채큐 do polo탑ky rodi훾ovsk챕ho menu s ESC alebo 컁avou 큄챠pkou. Zatvorte kontextov챕 menu s ESC."},
{name:"Editorov box zoznamu",legend:"V boxe zoznamu, presu흫te sa na 휁al큄iu polo탑ku v zozname s TAB alebo dolnou 큄챠pkou. Presu흫te sa k predch찼dzaj첬cej polo탑ke v zozname so SHIFT+TAB alebo hornou 큄챠pkou. Stla훾te medzern챠k alebo ENTER pre v첵ber mo탑nosti zoznamu. Stla훾te ESC pre zatvorenie boxu zoznamu."},{name:"Editorove p찼smo cesty prvku",legend:"Stla훾te ${elementsPathFocus} pre navigovanie na p찼smo cesty elementu. Presu흫te sa na tla훾idlo 휁al큄ieho prvku s TAB alebo pravou 큄챠pkou. Presu흫te sa k predch찼dzaj첬cemu tla훾idlu s SHIFT+TAB alebo 컁avou 큄챠pkou. Stla훾te medzern챠k alebo ENTER pre v첵ber prvku v editore."}]},
{name:"Pr챠kazy",items:[{name:"Vr찼ti큐 pr챠kazy",legend:"Stla훾te ${undo}"},{name:"Nanovo vr찼ti큐 pr챠kaz",legend:"Stla훾te ${redo}"},{name:"Pr챠kaz na stu훾nenie",legend:"Stla훾te ${bold}"},{name:"Pr챠kaz na kurz챠vu",legend:"Stla훾te ${italic}"},{name:"Pr챠kaz na pod훾iarknutie",legend:"Stla훾te ${underline}"},{name:"Pr챠kaz na odkaz",legend:"Stla훾te ${link}"},{name:"Pr챠kaz na zbalenie li큄ty n찼strojov",legend:"Stla훾te ${toolbarCollapse}"},{name:"Prejs큐 na predch찼dzaj첬cu zamerate컁n첬 medzeru pr챠kazu",legend:"Stla훾te ${accessPreviousSpace} pre pr챠stup na najbli탑큄ie nedosiahnute컁n챕 zamerate컁n챕 medzery pred vsuvkuo. Napr챠klad: dve za sebou id첬ce horizont찼lne 훾iary. Opakujte kombin찼ciu kl찼vesov pre dosiahnutie vzdialen첵ch zamerate컁n첵ch medzier."},
{name:"Prejs큐 na 휁al큄챠 ",legend:"Stla훾te ${accessNextSpace} pre pr챠stup na najbli탑큄ie nedosiahnute컁n챕 zamerate컁n챕 medzery po vsuvke. Napr챠klad: dve za sebou id첬ce horizont찼lne 훾iary. Opakujte kombin찼ciu kl찼vesov pre dosiahnutie vzdialen첵ch zamerate컁n첵ch medzier."},{name:"Pomoc pr챠stupnosti",legend:"Stla훾te ${a11yHelp}"}]}],backspace:"Backspace",tab:"Tab",enter:"Enter",shift:"Shift",ctrl:"Ctrl",alt:"Alt",pause:"Pause",capslock:"Caps Lock",escape:"Escape",pageUp:"Str찼nka hore",pageDown:"Str찼nka dole",
end:"End",home:"Home",leftArrow:"힋챠pka na컁avo",upArrow:"힋챠pka hore",rightArrow:"힋챠pka napravo",downArrow:"힋챠pka dole",insert:"Insert","delete":"Delete",leftWindowKey:"캭av챕 Windows tla훾idlo",rightWindowKey:"Prav챕 Windows tla훾idlo",selectKey:"Tla훾idlo Select",numpad0:"Numpad 0",numpad1:"Numpad 1",numpad2:"Numpad 2",numpad3:"Numpad 3",numpad4:"Numpad 4",numpad5:"Numpad 5",numpad6:"Numpad 6",numpad7:"Numpad 7",numpad8:"Numpad 8",numpad9:"Numpad 9",multiply:"N찼sobenie",add:"S훾챠tanie",subtract:"Od훾챠tanie",
decimalPoint:"Desatinn찼 훾iarka",divide:"Delenie",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Num Lock",scrollLock:"Scroll Lock",semiColon:"Bodko훾iarka",equalSign:"Rovn찼 sa",comma:"훻iarka",dash:"Pom캤훾ka",period:"Bodka",forwardSlash:"Lom챠tko",graveAccent:"Zd척raz흫ovanie pr챠zvuku",openBracket:"Hranat찼 z찼tvorka otv찼racia",backSlash:"Backslash",closeBracket:"Hranat찼 z찼tvorka zatv찼racia",singleQuote:"Jednoduch챕 첬vodzovky"});