/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","sv",{title:"Hj채lpmedelsinstruktioner",contents:"Hj채lpinneh책ll. F철r att st채nga denna dialogruta trycker du p책 ESC.",legend:[{name:"Allm채nt",items:[{name:"Editor verktygsf채lt",legend:"Tryck p책 ${toolbarFocus} f철r att navigera till verktygsf채ltet. Flytta till n채sta och f철reg책ende verktygsf채ltsgrupp med TAB och SHIFT+TAB. Flytta till n채sta och f철reg책ende knapp i verktygsf채ltet med H횜GERPIL eller V횆NSTERPIL. Tryck SPACE eller ENTER f철r att aktivera knappen i verktygsf채ltet."},
{name:"Dialogeditor",legend:"Inuti en dialogruta, tryck TAB f철r att navigera till n채sta f채lt i dialogrutan, tryck SKIFT+TAB f철r att flytta till f철reg책ende f채lt, tryck ENTER f철r att skicka. Du avbryter och st채nger dialogen med ESC. F철r dialogrutor som har flera flikar, tryck ALT+F10 eller TAB f철r att navigera till fliklistan. med fliklistan vald flytta till n채sta och f철reg책ende flik med H횜GER- eller V횆NSTERPIL."},{name:"Editor f철r inneh책llsmeny",legend:"Tryck p책 $ {contextMenu} eller PROGRAMTANGENTEN f철r att 철ppna snabbmenyn. Flytta sedan till n채sta menyalternativ med TAB eller NEDPIL. Flytta till f철reg책ende alternativ med SHIFT + TABB eller UPPIL. Tryck Space eller ENTER f철r att v채lja menyalternativ. 횜ppna undermeny av nuvarande alternativ med SPACE eller ENTER eller H횜GERPIL. G책 tillbaka till 철verordnade menyalternativ med ESC eller V횆NSTERPIL. St채ng snabbmenyn med ESC."},
{name:"Editor f철r list-box",legend:"Inuti en list-box, g책 till n채sta listobjekt med TAB eller NEDPIL. Flytta till f철reg책ende listobjekt med SHIFT+TAB eller UPPIL. Tryck SPACE eller ENTER f철r att v채lja listan alternativet. Tryck ESC f철r att st채nga list-boxen."},{name:"Editor f철r elementens s철kv채g",legend:"Tryck p책 ${elementsPathFocus} f철r att navigera till verktygsf채ltet f철r elementens s철kv채gar. Flytta till n채sta elementknapp med TAB eller H횜GERPIL. Flytta till f철reg책ende knapp med SKIFT+TAB eller V횆NSTERPIL. Tryck SPACE eller ENTER f철r att v채lja element i redigeraren."}]},
{name:"Kommandon",items:[{name:"횇ngra kommando",legend:"Tryck p책 ${undo}"},{name:"G철r om kommando",legend:"Tryck p책 ${redo}"},{name:"Kommandot fet stil",legend:"Tryck p책 ${bold}"},{name:"Kommandot kursiv",legend:"Tryck p책 ${italic}"},{name:"Kommandot understruken",legend:"Tryck p책 ${underline}"},{name:"Kommandot l채nk",legend:"Tryck p책 ${link}"},{name:"Verktygsf채lt D철lj kommandot",legend:"Tryck p책 ${toolbarCollapse}"},{name:"G책 till f철reg책ende fokus plats",legend:"Tryck p책 ${accessPreviousSpace} f철r att g책 till n채rmast on책bara utrymme f철re mark철ren, exempel: tv책 intilliggande HR element. Repetera tangentkombinationen f철r att g책 till n채sta."},
{name:"Tillg책 n채sta fokuskommandots utrymme",legend:"Tryck ${accessNextSpace} p책 f철r att komma 책t den n채rmaste on책bar fokus utrymme efter cirkumflex, till exempel: tv책 intilliggande HR element. Upprepa tangentkombinationen f철r att n책 avl채gsna fokus utrymmen."},{name:"Hj채lp om tillg채nglighet",legend:"Tryck ${a11yHelp}"}]}],backspace:"Backsteg",tab:"Tab",enter:"Retur",shift:"Skift",ctrl:"Ctrl",alt:"Alt",pause:"Paus",capslock:"Caps lock",escape:"Escape",pageUp:"Sida Up",pageDown:"Sida Ned",end:"Slut",
home:"Hem",leftArrow:"V채nsterpil",upArrow:"Uppil",rightArrow:"H철gerpil",downArrow:"Ned책tpil",insert:"Infoga","delete":"Radera",leftWindowKey:"V채nster Windowstangent",rightWindowKey:"H철ger Windowstangent",selectKey:"V채lj tangent",numpad0:"Nummer 0",numpad1:"Nummer 1",numpad2:"Nummer 2",numpad3:"Nummer 3",numpad4:"Nummer 4",numpad5:"Nummer 5",numpad6:"Nummer 6",numpad7:"Nummer 7",numpad8:"Nummer 8",numpad9:"Nummer 9",multiply:"Multiplicera",add:"Addera",subtract:"Minus",decimalPoint:"Decimalpunkt",
divide:"Dividera",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Num Lock",scrollLock:"Scroll Lock",semiColon:"Semikolon",equalSign:"Lika med tecken",comma:"Komma",dash:"Minus",period:"Punkt",forwardSlash:"Snedstreck fram책t",graveAccent:"Accent",openBracket:"횜ppningsparentes",backSlash:"Snedstreck bak책t",closeBracket:"Slutparentes",singleQuote:"Enkelt Citattecken"});