/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.38
 * Generated at: 2016-11-04 06:37:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.lecture;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.min.domain.MyQuestion;
import java.util.List;
import com.min.domain.Lecture;
import java.util.HashMap;

public final class player_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/lecture/../inc/header.jsp", Long.valueOf(1478237670045L));
    _jspx_dependants.put("/inc/modal.jsp", Long.valueOf(1478217816985L));
    _jspx_dependants.put("/lecture/../inc/footer.jsp", Long.valueOf(1478227754930L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.min.domain.MyQuestion");
    _jspx_imports_classes.add("com.min.domain.Lecture");
    _jspx_imports_classes.add("java.util.HashMap");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	Lecture lecture = (Lecture) request.getAttribute("lecture");
	HashMap<String, String> lectureValues = (HashMap) request.getAttribute("lecturevalues");

	List<MyQuestion> questionList = (List) request.getAttribute("questionList");

	String title = request.getParameter("title");
	int lecture_id = Integer.parseInt(request.getParameter("lecture_id"));
	int lectureNum = Integer.parseInt(request.getParameter("lectureNum"));

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<!-- <link rel=\"stylesheet\" type=\"text/css\" href=\"css/hyeon_style.css\"> -->\r\n");
      out.write("<!-- 합쳐지고 최소화된 최신 CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- Carousel Theme -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/style.css\">\r\n");
      out.write("\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!-- The Modal -->\r\n");
      out.write("<div id=\"loginModal\" class=\"modal\">\r\n");
      out.write("\t<!-- Modal content -->\r\n");
      out.write("\t<div class=\"modal-content\">\r\n");
      out.write("\t\t<div id=\"naver_id_login\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("<header>\r\n");
      out.write("\t<div class=\"navbar-wrapper\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("        <nav class=\"navbar navbar-static-top\">\r\n");
      out.write("          <div class=\"container\">\r\n");
      out.write("            <div class=\"navbar-header\">\r\n");
      out.write("              <button type=\"button\" class=\"navbar-toggle collapsed\" data-toggle=\"collapse\" data-target=\"#navbar\" aria-expanded=\"false\" aria-controls=\"navbar\">\r\n");
      out.write("                <span class=\"sr-only\">Toggle navigation</span>\r\n");
      out.write("                <span class=\"icon-bar\"></span>\r\n");
      out.write("                <span class=\"icon-bar\"></span>\r\n");
      out.write("                <span class=\"icon-bar\"></span>\r\n");
      out.write("              </button>\r\n");
      out.write("              <a class=\"navbar-brand\" href=\"#\"><img alt=\"logo\" src=\"/data/img/logo.png\" ></a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"navbar\" class=\"navbar-collapse collapse\">\r\n");
      out.write("              <ul class=\"nav navbar-nav\">\r\n");
      out.write("                <li><a href=\"/lecture/index.do\">온라인 강의</a></li>\r\n");
      out.write("                <li><a href=\"#\">실전 프로젝트</a></li>\r\n");
      out.write("                <li class=\"dropdown\">\r\n");
      out.write("                  <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" role=\"button\" aria-expanded=\"false\">커뮤니티<span class=\"caret\"></span></a>\r\n");
      out.write("                  <ul class=\"dropdown-menu\" role=\"menu\">\r\n");
      out.write("                    <li><a href=\"#\">공지사항</a></li>\r\n");
      out.write("                    <li><a href=\"#\">민쌤 엿보기</a></li>\r\n");
      out.write("                    <li><a href=\"#\">과제 게시판</a></li>\r\n");
      out.write("                    <li><a href=\"#\">프로젝트 경연</a></li>\r\n");
      out.write("                    <li><a href=\"#\">IT 블로그</a></li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                \r\n");
      out.write("             \t</ul>\r\n");
      out.write("\t\t\t\t<ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#contact\">고객센터</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a id=\"btnLogin\">로그인</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </nav>\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</header>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container marketing\" style=\"margin-top: 60px;\">\r\n");
      out.write("\t<form enctype=\"multipart/form-data\" name=\"form1\" method=post>\r\n");
      out.write("\t\t<section>\r\n");
      out.write("\t\t\t<h1>\r\n");
      out.write("\t\t\t\t<span class=\"label label-default\">");
      out.print(title);
      out.write(' ');
      out.print(lectureNum);
      out.write("강</span>\r\n");
      out.write("\t\t\t</h1>\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\t\t<section>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<iframe name=\"player\" id=\"player\"\r\n");
      out.write("\t\t\t\t\tsrc=\"");
      out.print(lecture.getLink());
      out.write("?fullscreen=1&autoplay=1&loop=0'\"\r\n");
      out.write("\t\t\t\t\twidth=\"100%\" height=\"500px\" frameborder=\"0\" webkitallowfullscreen\r\n");
      out.write("\t\t\t\t\tmozallowfullscreen allowfullscreen hidefocus=\"true\"></iframe>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\t\t<section>\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-3\" style=\"margin-bottom: 20px;\">\r\n");
      out.write("\t\t\t\t\t<a href=\"/data/file/lec/");
      out.print(lecture.getLecturefile());
      out.write("\">자료 다운 받는\r\n");
      out.write("\t\t\t\t\t\t곳</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-3\" style=\"margin-bottom: 20px;\">\r\n");
      out.write("\t\t\t\t\t<input type=\"file\" name=\"lectureFile\" placeholder=\"과제 첨부하는 곳\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-3\" style=\"margin-bottom: 20px;\">\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" value=\"등록\" id=\"registHomework\" name=\"myFile\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\t\t<section>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<input type=\"text\" size=\"115\" id=\"content\" name=\"content\"\r\n");
      out.write("\t\t\t\t\tplaceholder=\"강사님께 드릴 질문을 입력하세요\"> <input type=\"button\"\r\n");
      out.write("\t\t\t\t\tvalue=\"등록\" id=\"sendQuestion\"> <input type=\"hidden\"\r\n");
      out.write("\t\t\t\t\tid=\"lecture_id\" value=\"");
      out.print(lecture_id);
      out.write("\"> <input\r\n");
      out.write("\t\t\t\t\ttype=\"hidden\" id=\"member_id\" value=\"1\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\t\t<section>\r\n");
      out.write("\t\t\t<h3>\r\n");
      out.write("\t\t\t\t<span class=\"label label-default\">나의 질문들</span>\r\n");
      out.write("\t\t\t</h3>\r\n");
      out.write("\t\t\t<ul id=\"showQList\">\r\n");
      out.write("\t\t\t\t");

					for (int a = 0; a < questionList.size(); a++) {
				
      out.write("\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t");

						MyQuestion myQuestion = questionList.get(a);
							int myQuestion_id = myQuestion.getMyquestion_id();
							String content = myQuestion.getContent();
							String replyer = myQuestion.getReplyer();
							String reply = myQuestion.getReply();
					
      out.write("\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<h3>나의 질문내용</h3>\r\n");
      out.write("\t\t\t\t\t\t<p>");
      out.print(content);
      out.write("</p>\r\n");
      out.write("\t\t\t\t\t</div> ");

 	if (replyer == null) {
 
      out.write("\r\n");
      out.write("\t\t\t\t\t<div style=\"display: none;\">\r\n");
      out.write("\t\t\t\t\t\t");

							} else {
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div style=\"display: block;\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3>답변</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<p id=\"reply_");
      out.print(myQuestion_id);
      out.write('"');
      out.write('>');
      out.print(reply);
      out.write("</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div> ");

 	}
 
      out.write("\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\t</form>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\t<footer class=\"footer-basic-centered\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<p class=\"footer-company-motto\">The company motto.</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<p class=\"footer-links\">\r\n");
      out.write("\t\t\t\t<a href=\"#\">Home</a>\r\n");
      out.write("\t\t\t\t·\r\n");
      out.write("\t\t\t\t<a href=\"#\">Blog</a>\r\n");
      out.write("\t\t\t\t·\r\n");
      out.write("\t\t\t\t<a href=\"#\">Pricing</a>\r\n");
      out.write("\t\t\t\t·\r\n");
      out.write("\t\t\t\t<a href=\"#\">About</a>\r\n");
      out.write("\t\t\t\t·\r\n");
      out.write("\t\t\t\t<a href=\"#\">Faq</a>\r\n");
      out.write("\t\t\t\t·\r\n");
      out.write("\t\t\t\t<a href=\"#\">Contact</a>\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<p class=\"footer-company-name\">Team 4p &copy; 2016</p>\r\n");
      out.write("\r\n");
      out.write("\t\t</footer>\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://static.nid.naver.com/js/naverLogin_implicit-1.0.2.js\" charset=\"utf-8\"></script>\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"https://player.vimeo.com/api/player.js\"></script>\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js\"></script>\r\n");
      out.write("<!-- naver login api script -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://static.nid.naver.com/js/naverLogin_implicit-1.0.2.js\"></script>\r\n");
      out.write("<!-- custom script -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"../js/hyeon_script.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"../js/lecture.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
