/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.38
 * Generated at: 2016-11-02 04:47:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.sds.domain.Board;
import com.sds.common.board.PagingManager;
import java.util.List;

public final class list_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.sds.domain.Board");
    _jspx_imports_classes.add("com.sds.common.board.PagingManager");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	List<Board> list = (List) request.getAttribute("list");
	PagingManager pm = (PagingManager) request.getAttribute("pm");

	out.print("게시물 갯수는 " + list.size());

      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Untitled Document</title>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("<style>\r\n");
      out.write("#box {\r\n");
      out.write("\tborder: 1px solid #CCCCCC\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#title {\r\n");
      out.write("\tfont-size: 9pt;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("\tcolor: #7F7F7F;\r\n");
      out.write("\t돋움\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#category {\r\n");
      out.write("\tfont-size: 9pt;\r\n");
      out.write("\tcolor: #7F7F7F;\r\n");
      out.write("\t돋움\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#keyword {\r\n");
      out.write("\twidth: 80px;\r\n");
      out.write("\theight: 17px;\r\n");
      out.write("\tfont-size: 9pt;\r\n");
      out.write("\tborder-left: 1px solid #333333;\r\n");
      out.write("\tborder-top: 1px solid #333333;\r\n");
      out.write("\tborder-right: 1px solid #333333;\r\n");
      out.write("\tborder-bottom: 1px solid #333333;\r\n");
      out.write("\tcolor: #7F7F7F;\r\n");
      out.write("\t돋움\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#paging {\r\n");
      out.write("\tfont-size: 9pt;\r\n");
      out.write("\tcolor: #7F7F7F;\r\n");
      out.write("\t돋움\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#list td {\r\n");
      out.write("\tfont-size: 9pt;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#copyright {\r\n");
      out.write("\tfont-size: 9pt;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a {\r\n");
      out.write("\ttext-decoration: none\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("img {\r\n");
      out.write("\tborder: 0px\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<table id=\"box\" align=\"center\" width=\"603\" border=\"0\" cellpadding=\"0\"\r\n");
      out.write("\t\tcellspacing=\"0\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td colspan=\"5\"><img src=\"/images/ceil.gif\" width=\"603\"\r\n");
      out.write("\t\t\t\theight=\"25\"></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td height=\"2\" colspan=\"5\" bgcolor=\"#6395FA\"><img\r\n");
      out.write("\t\t\t\tsrc=\"/images/line_01.gif\"></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr id=\"title\" align=\"center\">\r\n");
      out.write("\t\t\t<td width=\"50\" height=\"20\">번호</td>\r\n");
      out.write("\t\t\t<td width=\"303\" height=\"20\">제목</td>\r\n");
      out.write("\t\t\t<td width=\"100\" height=\"20\">글쓴이</td>\r\n");
      out.write("\t\t\t<td width=\"100\" height=\"20\">날짜</td>\r\n");
      out.write("\t\t\t<td width=\"50\" height=\"20\">조회수</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td height=\"1\" colspan=\"5\" bgcolor=\"#CCCCCC\"></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td colspan=\"5\" id=\"list\">\r\n");
      out.write("\t\t\t\t<table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("\t\t\t\t\t");

						int curPos = pm.getCurPos();
						int num = pm.getNum();
					
      out.write("\r\n");
      out.write("\t\t\t\t\t");

						for (int i = 1; i <= pm.getPageSize(); i++) {
					
      out.write("\r\n");
      out.write("\t\t\t\t\t");

						if (num < 1)
								break;
					
      out.write("\r\n");
      out.write("\t\t\t\t\t");

						Board board = list.get(curPos++);
					
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr align=\"center\" height=\"20px\"\r\n");
      out.write("\t\t\t\t\t\tonMouseOver=\"this.style.background='#FFFF99'\"\r\n");
      out.write("\t\t\t\t\t\tonMouseOut=\"this.style.background=''\">\r\n");
      out.write("\t\t\t\t\t\t<td width=\"50\">");
      out.print(num--);
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"303\"><a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"/board/detail.do?board_id=");
      out.print(board.getBoard_id());
      out.write('"');
      out.write('>');
      out.print(board.getTitle());
      out.write("</a></td>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"100\">");
      out.print(board.getWriter());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"100\">");
      out.print(board.getRegdate().substring(0, 10));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"50\">");
      out.print(board.getHit());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td height=\"1\" colspan=\"5\" background=\"/images/line_dot.gif\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t");

						}
					
      out.write("\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td id=\"paging\" height=\"20\" colspan=\"5\" align=\"center\">[1][2][3][4][5][6][7][8][9][10]</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td height=\"20\" colspan=\"5\" align=\"right\" style=\"padding-right: 2px;\">\r\n");
      out.write("\t\t\t\t<table width=\"160\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"70\"><select name=\"select\" id=\"category\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<option>제목</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option>내용</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option>글쓴이</option>\r\n");
      out.write("\t\t\t\t\t\t</select></td>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"80\"><input name=\"textfield\" id=\"keyword\"\r\n");
      out.write("\t\t\t\t\t\t\ttype=\"text\" size=\"15\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td><img src=\"/images/search_btn.gif\" width=\"32\" height=\"17\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td height=\"30\" colspan=\"5\" align=\"right\" style=\"padding-right: 2px;\"><a\r\n");
      out.write("\t\t\t\thref=\"write.jsp\"><img src=\"/images/write_btin.gif\" width=\"61\"\r\n");
      out.write("\t\t\t\t\theight=\"20\" border=\"0\"></a></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td height=\"1\" colspan=\"5\" bgcolor=\"#CCCCCC\"></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td height=\"20\" colspan=\"5\" align=\"center\" id=\"copyright\">Copyright\r\n");
      out.write("\t\t\t\tzino All Rights Reserved</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
