/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("specialchar","es",{euro:"S챠mbolo de euro",lsquo:"Comilla simple izquierda",rsquo:"Comilla simple derecha",ldquo:"Comilla doble izquierda",rdquo:"Comilla doble derecha",ndash:"Gui처n corto",mdash:"Gui처n medio largo",iexcl:"Signo de admiraci처n invertido",cent:"S챠mbolo centavo",pound:"S챠mbolo libra",curren:"S챠mbolo moneda",yen:"S챠mbolo yen",brvbar:"Barra vertical rota",sect:"S챠mbolo secci처n",uml:"Di챕resis",copy:"Signo de derechos de autor",ordf:"Indicador ordinal femenino",laquo:"Abre comillas angulares",
not:"Signo negaci처n",reg:"Signo de marca registrada",macr:"Gui처n alto",deg:"Signo de grado",sup2:"Super챠ndice dos",sup3:"Super챠ndice tres",acute:"Acento agudo",micro:"Signo micro",para:"Signo de pi",middot:"Punto medio",cedil:"Cedilla",sup1:"Super챠ndice uno",ordm:"Indicador orginal masculino",raquo:"Cierra comillas angulares",frac14:"Fracci처n ordinaria de un quarto",frac12:"Fracci처n ordinaria de una mitad",frac34:"Fracci처n ordinaria de tres cuartos",iquest:"Signo de interrogaci처n invertido",Agrave:"Letra A latina may첬scula con acento grave",
Aacute:"Letra A latina  may첬scula con acento agudo",Acirc:"Letra A latina may첬scula con acento circunflejo",Atilde:"Letra A latina may첬scula con tilde",Auml:"Letra A latina may첬scula con di챕resis",Aring:"Letra A latina may첬scula con aro arriba",AElig:"Letra 횈 latina may첬scula",Ccedil:"Letra C latina may첬scula con cedilla",Egrave:"Letra E latina may첬scula con acento grave",Eacute:"Letra E latina may첬scula con acento agudo",Ecirc:"Letra E latina may첬scula con acento circunflejo",Euml:"Letra E latina may첬scula con di챕resis",
Igrave:"Letra I latina may첬scula con acento grave",Iacute:"Letra I latina may첬scula con acento agudo",Icirc:"Letra I latina may첬scula con acento circunflejo",Iuml:"Letra I latina may첬scula con di챕resis",ETH:"Letra Eth latina may첬scula",Ntilde:"Letra N latina may첬scula con tilde",Ograve:"Letra O latina may첬scula con acento grave",Oacute:"Letra O latina may첬scula con acento agudo",Ocirc:"Letra O latina may첬scula con acento circunflejo",Otilde:"Letra O latina may첬scula con tilde",Ouml:"Letra O latina may첬scula con di챕resis",
times:"Signo de multiplicaci처n",Oslash:"Letra O latina may첬scula con barra inclinada",Ugrave:"Letra U latina may첬scula con acento grave",Uacute:"Letra U latina may첬scula con acento agudo",Ucirc:"Letra U latina may첬scula con acento circunflejo",Uuml:"Letra U latina may첬scula con di챕resis",Yacute:"Letra Y latina may첬scula con acento agudo",THORN:"Letra Thorn latina may첬scula",szlig:"Letra s latina fuerte peque챰a",agrave:"Letra a latina peque챰a con acento grave",aacute:"Letra a latina peque챰a con acento agudo",
acirc:"Letra a latina peque챰a con acento circunflejo",atilde:"Letra a latina peque챰a con tilde",auml:"Letra a latina peque챰a con di챕resis",aring:"Letra a latina peque챰a con aro arriba",aelig:"Letra 챈 latina peque챰a",ccedil:"Letra c latina peque챰a con cedilla",egrave:"Letra e latina peque챰a con acento grave",eacute:"Letra e latina peque챰a con acento agudo",ecirc:"Letra e latina peque챰a con acento circunflejo",euml:"Letra e latina peque챰a con di챕resis",igrave:"Letra i latina peque챰a con acento grave",
iacute:"Letra i latina peque챰a con acento agudo",icirc:"Letra i latina peque챰a con acento circunflejo",iuml:"Letra i latina peque챰a con di챕resis",eth:"Letra eth latina peque챰a",ntilde:"Letra n latina peque챰a con tilde",ograve:"Letra o latina peque챰a con acento grave",oacute:"Letra o latina peque챰a con acento agudo",ocirc:"Letra o latina peque챰a con acento circunflejo",otilde:"Letra o latina peque챰a con tilde",ouml:"Letra o latina peque챰a con di챕resis",divide:"Signo de divisi처n",oslash:"Letra o latina min첬scula con barra inclinada",
ugrave:"Letra u latina peque챰a con acento grave",uacute:"Letra u latina peque챰a con acento agudo",ucirc:"Letra u latina peque챰a con acento circunflejo",uuml:"Letra u latina peque챰a con di챕resis",yacute:"Letra u latina peque챰a con acento agudo",thorn:"Letra thorn latina min첬scula",yuml:"Letra y latina peque챰a con di챕resis",OElig:"Diptongo OE latino en may첬scula",oelig:"Diptongo oe latino en min첬scula",372:"Letra W latina may첬scula con acento circunflejo",374:"Letra Y latina may첬scula con acento circunflejo",
373:"Letra w latina peque챰a con acento circunflejo",375:"Letra y latina peque챰a con acento circunflejo",sbquo:"Comilla simple baja-9",8219:"Comilla simple alta invertida-9",bdquo:"Comillas dobles bajas-9",hellip:"Puntos suspensivos horizontales",trade:"Signo de marca registrada",9658:"Apuntador negro apuntando a la derecha",bull:"Vi챰eta",rarr:"Flecha a la derecha",rArr:"Flecha doble a la derecha",hArr:"Flecha izquierda derecha doble",diams:"Diamante negro",asymp:"Casi igual a"});