/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("specialchar","fr-ca",{euro:"Symbole Euro",lsquo:"Guillemet simple ouvrant",rsquo:"Guillemet simple fermant",ldquo:"Guillemet double ouvrant",rdquo:"Guillemet double fermant",ndash:"Tiret haut",mdash:"Tiret",iexcl:"Point d'exclamation invers챕",cent:"Symbole de cent",pound:"Symbole de Livre Sterling",curren:"Symbole mon챕taire",yen:"Symbole du Yen",brvbar:"Barre scind챕e",sect:"Symbole de section",uml:"Tr챕ma",copy:"Symbole de copyright",ordf:"Indicateur ordinal f챕minin",laquo:"Guillemet fran챌ais ouvrant",
not:"Indicateur de n챕gation",reg:"Symbole de marque d챕pos챕e",macr:"Macron",deg:"Degr챕",sup2:"Exposant 2",sup3:"Exposant 3",acute:"Accent aig체e",micro:"Symbole micro",para:"Paragraphe",middot:"Point m챕dian",cedil:"C챕dille",sup1:"Exposant 1",ordm:"Indicateur ordinal masculin",raquo:"Guillemet fran챌ais fermant",frac14:"Un quart",frac12:"Une demi",frac34:"Trois quart",iquest:"Point d'interrogation invers챕",Agrave:"A accent grave",Aacute:"A accent aig체e",Acirc:"A circonflexe",Atilde:"A tilde",Auml:"A tr챕ma",
Aring:"A avec un rond au dessus",AElig:"횈 majuscule",Ccedil:"C c챕dille",Egrave:"E accent grave",Eacute:"E accent aig체e",Ecirc:"E accent circonflexe",Euml:"E tr챕ma",Igrave:"I accent grave",Iacute:"I accent aig체e",Icirc:"I accent circonflexe",Iuml:"I tr챕ma",ETH:"Lettre majuscule islandaise ED",Ntilde:"N tilde",Ograve:"O accent grave",Oacute:"O accent aig체e",Ocirc:"O accent circonflexe",Otilde:"O tilde",Ouml:"O tr챕ma",times:"Symbole de multiplication",Oslash:"O barr챕",Ugrave:"U accent grave",Uacute:"U accent aig체e",
Ucirc:"U accent circonflexe",Uuml:"U tr챕ma",Yacute:"Y accent aig체e",THORN:"Lettre islandaise Thorn majuscule",szlig:"Lettre minuscule allemande s dur",agrave:"a accent grave",aacute:"a accent aig체e",acirc:"a accent circonflexe",atilde:"a tilde",auml:"a tr챕ma",aring:"a avec un cercle au dessus",aelig:"챈",ccedil:"c c챕dille",egrave:"e accent grave",eacute:"e accent aig체e",ecirc:"e accent circonflexe",euml:"e tr챕ma",igrave:"i accent grave",iacute:"i accent aig체e",icirc:"i accent circonflexe",iuml:"i tr챕ma",
eth:"Lettre minuscule islandaise ED",ntilde:"n tilde",ograve:"o accent grave",oacute:"o accent aig체e",ocirc:"O accent circonflexe",otilde:"O tilde",ouml:"O tr챕ma",divide:"Symbole de division",oslash:"o barr챕",ugrave:"u accent grave",uacute:"u accent aig체e",ucirc:"u accent circonflexe",uuml:"u tr챕ma",yacute:"y accent aig체e",thorn:"Lettre islandaise thorn minuscule",yuml:"y tr챕ma",OElig:"ligature majuscule latine 흸",oelig:"ligature minuscule latine 흹",372:"W accent circonflexe",374:"Y accent circonflexe",
373:"w accent circonflexe",375:"y accent circonflexe",sbquo:"Guillemet simple fermant",8219:"Guillemet-virgule sup챕rieur culbut챕",bdquo:"Guillemet-virgule double inf챕rieur",hellip:"Points de suspension",trade:"Symbole de marque d챕pos챕e",9658:"Fl챔che noire pointant vers la droite",bull:"Puce",rarr:"Fl챔che vers la droite",rArr:"Fl챔che double vers la droite",hArr:"Fl챔che double vers la gauche",diams:"Carreau",asymp:"Presque 챕gal"});