/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("specialchar","hu",{euro:"Eur처 jel",lsquo:"Bal szimpla id챕z흷jel",rsquo:"Jobb szimpla id챕z흷jel",ldquo:"Bal dupla id챕z흷jel",rdquo:"Jobb dupla id챕z흷jel",ndash:"R철vid gondolatjel",mdash:"Hossz첬 gondolatjel",iexcl:"Ford챠tott felki찼lt처jel",cent:"Cent jel",pound:"Font jel",curren:"Valuta jel",yen:"Yen jel",brvbar:"Hossz첬 kett흷spont",sect:"Paragrafus jel",uml:"Kett흷s hangz처 jel",copy:"Szerz흷i jog jel",ordf:"N흷i sorrend mutat처ja",laquo:"Balra mutat처 duplany챠l",not:"Felt챕teles k철t흷jel",
reg:"Bejegyzett v챕djegy jele",macr:"Hossz첬s찼gi jel",deg:"Fok jel",sup2:"N챕gyzeten jel",sup3:"K철b철n jel",acute:"횋les 챕kezet",micro:"Mikro-jel",para:"Bekezd챕s jel",middot:"K철z챕p pont",cedil:"C챕dille",sup1:"Els흷n jel",ordm:"F챕rfi sorrend mutat처ja",raquo:"Jobbra mutat처 duplany챠l",frac14:"Egy negyed jel",frac12:"Egy ketted jel",frac34:"H찼rom negyed jel",iquest:"Ford챠tott k챕rd흷jel",Agrave:"Latin nagy A ford챠tott 챕kezettel",Aacute:"Latin nagy A norm찼l 챕kezettel",Acirc:"Latin nagy A hajtott 챕kezettel",Atilde:"Latin nagy A hull찼mjellel",
Auml:"Latin nagy A kett흷spont 챕kezettel",Aring:"Latin nagy A gy킥r킥 챕kezettel",AElig:"Latin nagy 횈 bet킥",Ccedil:"Latin nagy C cedill찼val",Egrave:"Latin nagy E ford챠tott 챕kezettel",Eacute:"Latin nagy E norm찼l 챕kezettel",Ecirc:"Latin nagy E hajtott 챕kezettel",Euml:"Latin nagy E dupla kett흷spont 챕kezettel",Igrave:"Latin nagy I ford챠tott 챕kezettel",Iacute:"Latin nagy I norm찼l 챕kezettel",Icirc:"Latin nagy I hajtott 챕kezettel",Iuml:"Latin nagy I kett흷spont 챕kezettel",ETH:"Latin nagy Eth bet킥",Ntilde:"Latin nagy N hull찼mjellel",
Ograve:"Latin nagy O ford챠tott 챕kezettel",Oacute:"Latin nagy O norm찼l 챕kezettel",Ocirc:"Latin nagy O hajtott 챕kezettel",Otilde:"Latin nagy O hull찼mjellel",Ouml:"Latin nagy O kett흷spont 챕kezettel",times:"Szorz찼s jel",Oslash:"Latin O bet킥 찼th첬z찼ssal",Ugrave:"Latin nagy U ford챠tott 챕kezettel",Uacute:"Latin nagy U norm찼l 챕kezettel",Ucirc:"Latin nagy U hajtott 챕kezettel",Uuml:"Latin nagy U kett흷spont 챕kezettel",Yacute:"Latin nagy Y norm찼l 챕kezettel",THORN:"Latin nagy Thorn bet킥",szlig:"Latin kis s bet킥",
agrave:"Latin kis a ford챠tott 챕kezettel",aacute:"Latin kis a norm찼l 챕kezettel",acirc:"Latin kis a hajtott 챕kezettel",atilde:"Latin kis a hull찼mjellel",auml:"Latin kis a kett흷spont 챕kezettel",aring:"Latin kis a gy킥r킥 챕kezettel",aelig:"Latin kis 챈 bet킥",ccedil:"Latin kis c cedill찼val",egrave:"Latin kis e ford챠tott 챕kezettel",eacute:"Latin kis e norm찼l 챕kezettel",ecirc:"Latin kis e hajtott 챕kezettel",euml:"Latin kis e dupla kett흷spont 챕kezettel",igrave:"Latin kis i ford챠tott 챕kezettel",iacute:"Latin kis i norm찼l 챕kezettel",
icirc:"Latin kis i hajtott 챕kezettel",iuml:"Latin kis i kett흷spont 챕kezettel",eth:"Latin kis eth bet킥",ntilde:"Latin kis n hull찼mjellel",ograve:"Latin kis o ford챠tott 챕kezettel",oacute:"Latin kis o norm찼l 챕kezettel",ocirc:"Latin kis o hajtott 챕kezettel",otilde:"Latin kis o hull찼mjellel",ouml:"Latin kis o kett흷spont 챕kezettel",divide:"Oszt찼sjel",oslash:"Latin kis o bet킥 찼th첬z찼ssal",ugrave:"Latin kis u ford챠tott 챕kezettel",uacute:"Latin kis u norm찼l 챕kezettel",ucirc:"Latin kis u hajtott 챕kezettel",
uuml:"Latin kis u kett흷spont 챕kezettel",yacute:"Latin kis y norm찼l 챕kezettel",thorn:"Latin kis thorn jel",yuml:"Latin kis y kett흷spont 챕kezettel",OElig:"Latin nagy OE-jel",oelig:"Latin kis oe-jel",372:"Latin nagy W hajtott 챕kezettel",374:"Latin nagy Y hajtott 챕kezettel",373:"Latin kis w hajtott 챕kezettel",375:"Latin kis y hajtott 챕kezettel",sbquo:"Nyit처 nyomdai szimpla id챕z흷jel",8219:"Z찼r처 nyomdai z찼r처 id챕z흷jel",bdquo:"Nyit처 nyomdai dupla id챕z흷jel",hellip:"H찼rom pont",trade:"Kereskedelmi v챕djegy jele",
9658:"Jobbra mutat처 fekete mutat처",bull:"Goly처",rarr:"Jobbra mutat처 ny챠l",rArr:"Jobbra mutat처 duplany챠l",hArr:"Bal-jobb duplany챠l",diams:"Fekete gy챕m찼nt jel",asymp:"Majdnem egyenl흷 jel"});