/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("specialchar","pl",{euro:"Znak euro",lsquo:"Cudzys흢처w pojedynczy otwieraj훳cy",rsquo:"Cudzys흢처w pojedynczy zamykaj훳cy",ldquo:"Cudzys흢처w apostrofowy otwieraj훳cy",rdquo:"Cudzys흢처w apostrofowy zamykaj훳cy",ndash:"P처흢pauza",mdash:"Pauza",iexcl:"Odwr처cony wykrzyknik",cent:"Znak centa",pound:"Znak funta",curren:"Znak waluty",yen:"Znak jena",brvbar:"Przerwana pionowa kreska",sect:"Paragraf",uml:"Diereza",copy:"Znak praw autorskich",ordf:"Wska탄nik rodzaju 탉e흦skiego liczebnika porz훳dkowego",
laquo:"Lewy cudzys흢처w ostrok훳tny",not:"Znak negacji",reg:"Zastrze탉ony znak towarowy",macr:"Makron",deg:"Znak stopnia",sup2:"Druga pot휌ga",sup3:"Trzecia pot휌ga",acute:"Akcent ostry",micro:"Znak mikro",para:"Znak akapitu",middot:"Kropka 힄rodkowa",cedil:"Cedylla",sup1:"Pierwsza pot휌ga",ordm:"Wska탄nik rodzaju m휌skiego liczebnika porz훳dkowego",raquo:"Prawy cudzys흢처w ostrok훳tny",frac14:"U흢amek zwyk흢y jedna czwarta",frac12:"U흢amek zwyk흢y jedna druga",frac34:"U흢amek zwyk흢y trzy czwarte",iquest:"Odwr처cony znak zapytania",
Agrave:"Wielka litera A z akcentem ci휌탉kim",Aacute:"Wielka litera A z akcentem ostrym",Acirc:"Wielka litera A z akcentem przeci훳g흢ym",Atilde:"Wielka litera A z tyld훳",Auml:"Wielka litera A z dierez훳",Aring:"Wielka litera A z k처흢kiem",AElig:"Wielka ligatura 횈",Ccedil:"Wielka litera C z cedyll훳",Egrave:"Wielka litera E z akcentem ci휌탉kim",Eacute:"Wielka litera E z akcentem ostrym",Ecirc:"Wielka litera E z akcentem przeci훳g흢ym",Euml:"Wielka litera E z dierez훳",Igrave:"Wielka litera I z akcentem ci휌탉kim",
Iacute:"Wielka litera I z akcentem ostrym",Icirc:"Wielka litera I z akcentem przeci훳g흢ym",Iuml:"Wielka litera I z dierez훳",ETH:"Wielka litera Eth",Ntilde:"Wielka litera N z tyld훳",Ograve:"Wielka litera O z akcentem ci휌탉kim",Oacute:"Wielka litera O z akcentem ostrym",Ocirc:"Wielka litera O z akcentem przeci훳g흢ym",Otilde:"Wielka litera O z tyld훳",Ouml:"Wielka litera O z dierez훳",times:"Znak mno탉enia wektorowego",Oslash:"Wielka litera O z przekre힄leniem",Ugrave:"Wielka litera U z akcentem ci휌탉kim",Uacute:"Wielka litera U z akcentem ostrym",
Ucirc:"Wielka litera U z akcentem przeci훳g흢ym",Uuml:"Wielka litera U z dierez훳",Yacute:"Wielka litera Y z akcentem ostrym",THORN:"Wielka litera Thorn",szlig:"Ma흢a litera ostre s (eszet)",agrave:"Ma흢a litera a z akcentem ci휌탉kim",aacute:"Ma흢a litera a z akcentem ostrym",acirc:"Ma흢a litera a z akcentem przeci훳g흢ym",atilde:"Ma흢a litera a z tyld훳",auml:"Ma흢a litera a z dierez훳",aring:"Ma흢a litera a z k처흢kiem",aelig:"Ma흢a ligatura 챈",ccedil:"Ma흢a litera c z cedyll훳",egrave:"Ma흢a litera e z akcentem ci휌탉kim",
eacute:"Ma흢a litera e z akcentem ostrym",ecirc:"Ma흢a litera e z akcentem przeci훳g흢ym",euml:"Ma흢a litera e z dierez훳",igrave:"Ma흢a litera i z akcentem ci휌탉kim",iacute:"Ma흢a litera i z akcentem ostrym",icirc:"Ma흢a litera i z akcentem przeci훳g흢ym",iuml:"Ma흢a litera i z dierez훳",eth:"Ma흢a litera eth",ntilde:"Ma흢a litera n z tyld훳",ograve:"Ma흢a litera o z akcentem ci휌탉kim",oacute:"Ma흢a litera o z akcentem ostrym",ocirc:"Ma흢a litera o z akcentem przeci훳g흢ym",otilde:"Ma흢a litera o z tyld훳",ouml:"Ma흢a litera o z dierez훳",
divide:"Anglosaski znak dzielenia",oslash:"Ma흢a litera o z przekre힄leniem",ugrave:"Ma흢a litera u z akcentem ci휌탉kim",uacute:"Ma흢a litera u z akcentem ostrym",ucirc:"Ma흢a litera u z akcentem przeci훳g흢ym",uuml:"Ma흢a litera u z dierez훳",yacute:"Ma흢a litera y z akcentem ostrym",thorn:"Ma흢a litera thorn",yuml:"Ma흢a litera y z dierez훳",OElig:"Wielka ligatura OE",oelig:"Ma흢a ligatura oe",372:"Wielka litera W z akcentem przeci훳g흢ym",374:"Wielka litera Y z akcentem przeci훳g흢ym",373:"Ma흢a litera w z akcentem przeci훳g흢ym",
375:"Ma흢a litera y z akcentem przeci훳g흢ym",sbquo:"Pojedynczy apostrof dolny",8219:"Pojedynczy apostrof g처rny",bdquo:"Podw처jny apostrof dolny",hellip:"Wielokropek",trade:"Znak towarowy",9658:"Czarny wska탄nik wskazuj훳cy w prawo",bull:"Punktor",rarr:"Strza흢ka w prawo",rArr:"Podw처jna strza흢ka w prawo",hArr:"Podw처jna strza흢ka obustronna",diams:"Czarny znak karo",asymp:"Znak prawie r처wne"});