/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("specialchar","pt",{euro:"S챠mbolo do Euro",lsquo:"Aspa esquerda simples",rsquo:"Aspa direita simples",ldquo:"Aspa esquerda dupla",rdquo:"Aspa direita dupla",ndash:"Travess찾o Simples",mdash:"Travess찾o Longo",iexcl:"Ponto de exclama챌찾o invertido",cent:"S챠mbolo do C챗ntimo",pound:"S챠mbolo da Libra",curren:"S챠mbolo de Moeda",yen:"S챠mbolo do Iene",brvbar:"Barra quebrada",sect:"S챠mbolo de Sec챌찾o",uml:"Trema",copy:"S챠mbolo dos Direitos de Autor",ordf:"Indicador ordinal feminino",
laquo:"Aspa esquerda 창ngulo duplo",not:"N찾o S챠mbolo",reg:"S챠mbolo de Registado",macr:"M찼cron",deg:"S챠mbolo de Grau",sup2:"Expoente 2",sup3:"Expoente 3",acute:"Acento agudo",micro:"S챠mbolo de Micro",para:"S챠mbolo de Par찼grafo",middot:"Ponto do Meio",cedil:"Cedilha",sup1:"Expoente 1",ordm:"Indicador ordinal masculino",raquo:"Aspas 창ngulo duplo pra Direita",frac14:"Fra챌찾o vulgar 1/4",frac12:"Fra챌찾o vulgar 1/2",frac34:"Fra챌찾o vulgar 3/4",iquest:"Ponto de interroga챌찾o invertido",Agrave:"Letra mai첬scula latina A com acento grave",
Aacute:"Letra mai첬scula latina A com acento agudo",Acirc:"Letra mai첬scula latina A com circunflexo",Atilde:"Letra mai첬scula latina A com til",Auml:"Letra mai첬scula latina A com trema",Aring:"Letra mai첬scula latina A com sinal diacr챠tico",AElig:"Letra mai첬scula latina 횈",Ccedil:"Letra mai첬scula latina C com cedilha",Egrave:"Letra mai첬scula latina E com acento grave",Eacute:"Letra mai첬scula latina E com acento agudo",Ecirc:"Letra mai첬scula latina E com circunflexo",Euml:"Letra mai첬scula latina E com trema",
Igrave:"Letra mai첬scula latina I com acento grave",Iacute:"Letra mai첬scula latina I com acento agudo",Icirc:"Letra mai첬scula latina I com cincunflexo",Iuml:"Letra mai첬scula latina I com trema",ETH:"Letra mai첬scula latina Eth (횖챨)",Ntilde:"Letra mai첬scula latina N com til",Ograve:"Letra mai첬scula latina O com acento grave",Oacute:"Letra mai첬scula latina O com acento agudo",Ocirc:"Letra mai첬scula latina I com circunflexo",Otilde:"Letra mai첬scula latina O com til",Ouml:"Letra mai첬scula latina O com trema",
times:"S챠mbolo de multiplica챌찾o",Oslash:"Letra mai첬scula O com barra",Ugrave:"Letra mai첬scula latina U com acento grave",Uacute:"Letra mai첬scula latina U com acento agudo",Ucirc:"Letra mai첬scula latina U com circunflexo",Uuml:"Letra mai첬scula latina E com trema",Yacute:"Letra mai첬scula latina Y com acento agudo",THORN:"Letra mai첬scula latina R첬nico",szlig:"Letra min첬scula latina s forte",agrave:"Letra min첬scula latina a com acento grave",aacute:"Letra min첬scula latina a com acento agudo",acirc:"Letra min첬scula latina a com circunflexo",
atilde:"Letra min첬scula latina a com til",auml:"Letra min첬scula latina a com trema",aring:"Letra min첬scula latina a com sinal diacr챠tico",aelig:"Letra min첬scula latina 챈",ccedil:"Letra min첬scula latina c com cedilha",egrave:"Letra min첬scula latina e com acento grave",eacute:"Letra min첬scula latina e com acento agudo",ecirc:"Letra min첬scula latina e com circunflexo",euml:"Letra min첬scula latina e com trema",igrave:"Letra min첬scula latina i com acento grave",iacute:"Letra min첬scula latina i com acento agudo",
icirc:"Letra min첬scula latina i com circunflexo",iuml:"Letra pequena latina i com trema",eth:"Letra min첬scula latina eth",ntilde:"Letra min첬scula latina n com til",ograve:"Letra min첬scula latina o com acento grave",oacute:"Letra min첬scula latina o com acento agudo",ocirc:"Letra min첬scula latina o com circunflexo",otilde:"Letra min첬scula latina o com til",ouml:"Letra min첬scula latina o com trema",divide:"S챠mbolo de divis찾o",oslash:"Letra min첬scula latina o com barra",ugrave:"Letra min첬scula latina u com acento grave",
uacute:"Letra min첬scula latina u com acento agudo",ucirc:"Letra min첬scula latina u com circunflexo",uuml:"Letra min첬scula latina u com trema",yacute:"Letra min첬scula latina y com acento agudo",thorn:"Letra min첬scula latina R첬nico",yuml:"Letra min첬scula latina y com trema",OElig:"Ligadura mai첬scula latina OE",oelig:"Ligadura min첬scula latina oe",372:"Letra mai첬scula latina W com circunflexo",374:"Letra mai첬scula latina Y com circunflexo",373:"Letra min첬scula latina w com circunflexo",375:"Letra min첬scula latina y com circunflexo",
sbquo:"Aspa Simples inferior-9",8219:"Aspa Simples superior invertida-9",bdquo:"Aspa duplas inferior-9",hellip:"Elipse Horizontal ",trade:"S챠mbolo de Marca Registada",9658:"Ponteiro preto direito",bull:"Marca",rarr:"Seta para a direita",rArr:"Seta dupla para a direita",hArr:"Seta dupla direita esquerda",diams:"Naipe diamante preto",asymp:"Quase igual a "});