/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("specialchar","vi",{euro:"K첵 hi沼뇎 Euro",lsquo:"D梳쪀 ngo梳톍 휃퉤n tr찼i",rsquo:"D梳쪀 ngo梳톍 휃퉤n ph梳즜",ldquo:"D梳쪀 ngo梳톍 휃척i tr찼i",rdquo:"D梳쪀 ngo梳톍 휃척i ph梳즜",ndash:"G梳죅h ngang ti梳퓆g anh",mdash:"G梳죅h ngang Em",iexcl:"Chuy沼긪 휃沼뷼 d梳쪀 ch梳쩷 than",cent:"K첵 t沼� ti沼걆 M沼�",pound:"K첵 t沼� ti沼걆 Anh",curren:"K첵 t沼� ti沼걆 t沼�",yen:"K첵 t沼� ti沼걆 Y챗n Nh梳춗",brvbar:"Thanh h沼뢮g",sect:"K첵 t沼� khu v沼켧",uml:"D梳쪀 t찼ch 휃척i",copy:"K첵 t沼� b梳즢 quy沼걆",ordf:"Ph梳쬷 ch沼� th沼� gi沼몁g c찼i",laquo:"Ch沼뛫 d梳쪀 ngo梳톍 휃척i tr찼i",not:"Kh척ng c처 k첵 t沼�",
reg:"K첵 t沼� 휃훱ng k첵",macr:"D梳쪀 nguy챗n 창m d횪i",deg:"K첵 t沼� 휃沼�",sup2:"Ch沼� tr沼밿 l챗n tr챗n d梳죒g 2",sup3:"Ch沼� tr沼밿 l챗n tr챗n d梳죒g 3",acute:"D梳쪀 tr沼뛫g 창m",micro:"K첵 t沼� micro",para:"K첵 t沼� 휃o梳죒 v훱n",middot:"D梳쪀 ch梳쩷 tr챵n",cedil:"D梳쪀 m처c l튼沼쌻",sup1:"K첵 t沼� tr沼밿 l챗n c梳쩺 1",ordm:"K첵 t沼� bi沼긳 hi沼뇆 gi沼몁g 휃沼켧",raquo:"Ch沼뛫 d梳쪀 ngo梳톍 휃척i ph梳즜",frac14:"T沼� l沼� m沼셳 ph梳쬷 t튼",frac12:"T沼� l沼� m沼셳 n沼춁",frac34:"T沼� l沼� ba ph梳쬷 t튼",iquest:"Chuy沼긪 휃沼뷼 d梳쪀 ch梳쩷 h沼뢩",Agrave:"K첵 t沼� la-tinh vi梳퓍 hoa A v沼쌻 d梳쪀 huy沼걆",Aacute:"K첵 t沼� la-tinh vi梳퓍 hoa A v沼쌻 d梳쪀 s梳칌",
Acirc:"K첵 t沼� la-tinh vi梳퓍 hoa A v沼쌻 d梳쪀 m크",Atilde:"K첵 t沼� la-tinh vi梳퓍 hoa A v沼쌻 d梳쪀 ng찾",Auml:"K첵 t沼� la-tinh vi梳퓍 hoa A v沼쌻 d梳쪀 hai ch梳쩷 tr챗n 휃梳쬾",Aring:"K첵 t沼� la-tinh vi梳퓍 hoa A v沼쌻 bi沼긳 t튼沼즢g v챵ng tr챵n tr챗n 휃梳쬾",AElig:"K첵 t沼� la-tinh vi梳퓍 hoa c沼쬪 횈",Ccedil:"K첵 t沼� la-tinh vi梳퓍 hoa C v沼쌻 d梳쪀 m처c b챗n d튼沼쌻",Egrave:"K첵 t沼� la-tinh vi梳퓍 hoa E v沼쌻 d梳쪀 huy沼걆",Eacute:"K첵 t沼� la-tinh vi梳퓍 hoa E v沼쌻 d梳쪀 s梳칌",Ecirc:"K첵 t沼� la-tinh vi梳퓍 hoa E v沼쌻 d梳쪀 m크",Euml:"K첵 t沼� la-tinh vi梳퓍 hoa E v沼쌻 d梳쪀 hai ch梳쩷 tr챗n 휃梳쬾",
Igrave:"K첵 t沼� la-tinh vi梳퓍 hoa I v沼쌻 d梳쪀 huy沼걆",Iacute:"K첵 t沼� la-tinh vi梳퓍 hoa I v沼쌻 d梳쪀 s梳칌",Icirc:"K첵 t沼� la-tinh vi梳퓍 hoa I v沼쌻 d梳쪀 m크",Iuml:"K첵 t沼� la-tinh vi梳퓍 hoa I v沼쌻 d梳쪀 hai ch梳쩷 tr챗n 휃梳쬾",ETH:"Vi梳퓍 hoa c沼쬪 k첵 t沼� Eth",Ntilde:"K첵 t沼� la-tinh vi梳퓍 hoa N v沼쌻 d梳쪀 ng찾",Ograve:"K첵 t沼� la-tinh vi梳퓍 hoa O v沼쌻 d梳쪀 huy沼걆",Oacute:"K첵 t沼� la-tinh vi梳퓍 hoa O v沼쌻 d梳쪀 s梳칌",Ocirc:"K첵 t沼� la-tinh vi梳퓍 hoa O v沼쌻 d梳쪀 m크",Otilde:"K첵 t沼� la-tinh vi梳퓍 hoa O v沼쌻 d梳쪀 ng찾",Ouml:"K첵 t沼� la-tinh vi梳퓍 hoa O v沼쌻 d梳쪀 hai ch梳쩷 tr챗n 휃梳쬾",
times:"K첵 t沼� ph챕p to찼n nh창n",Oslash:"K첵 t沼� la-tinh vi梳퓍 hoa A v沼쌻 d梳쪀 ng찾 xu沼몁g",Ugrave:"K첵 t沼� la-tinh vi梳퓍 hoa U v沼쌻 d梳쪀 huy沼걆",Uacute:"K첵 t沼� la-tinh vi梳퓍 hoa U v沼쌻 d梳쪀 s梳칌",Ucirc:"K첵 t沼� la-tinh vi梳퓍 hoa U v沼쌻 d梳쪀 m크",Uuml:"K첵 t沼� la-tinh vi梳퓍 hoa U v沼쌻 d梳쪀 hai ch梳쩷 tr챗n 휃梳쬾",Yacute:"K첵 t沼� la-tinh vi梳퓍 hoa Y v沼쌻 d梳쪀 s梳칌",THORN:"Ph梳쬷 vi梳퓍 hoa c沼쬪 k첵 t沼� Thorn",szlig:"K첵 t沼� vi梳퓍 nh沼� la-tinh c沼쬪 ch沼� s",agrave:"K첵 t沼� la-tinh th튼沼쓓g v沼쌻 d梳쪀 huy沼걆",aacute:"K첵 t沼� la-tinh th튼沼쓓g v沼쌻 d梳쪀 s梳칌",acirc:"K첵 t沼� la-tinh th튼沼쓓g v沼쌻 d梳쪀 m크",
atilde:"K첵 t沼� la-tinh th튼沼쓓g v沼쌻 d梳쪀 ng찾",auml:"K첵 t沼� la-tinh th튼沼쓓g v沼쌻 d梳쪀 hai ch梳쩷 tr챗n 휃梳쬾",aring:"K첵 t沼� la-tinh vi梳퓍 th튼沼쓓g v沼쌻 bi沼긳 t튼沼즢g v챵ng tr챵n tr챗n 휃梳쬾",aelig:"K첵 t沼� la-tinh vi梳퓍 th튼沼쓓g c沼쬪 챈",ccedil:"K첵 t沼� la-tinh vi梳퓍 th튼沼쓓g c沼쬪 c v沼쌻 d梳쪀 m처c b챗n d튼沼쌻",egrave:"K첵 t沼� la-tinh vi梳퓍 th튼沼쓓g e v沼쌻 d梳쪀 huy沼걆",eacute:"K첵 t沼� la-tinh vi梳퓍 th튼沼쓓g e v沼쌻 d梳쪀 s梳칌",ecirc:"K첵 t沼� la-tinh vi梳퓍 th튼沼쓓g e v沼쌻 d梳쪀 m크",euml:"K첵 t沼� la-tinh vi梳퓍 th튼沼쓓g e v沼쌻 d梳쪀 hai ch梳쩷 tr챗n 휃梳쬾",igrave:"K첵 t沼� la-tinh vi梳퓍 th튼沼쓓g i v沼쌻 d梳쪀 huy沼걆",
iacute:"K첵 t沼� la-tinh vi梳퓍 th튼沼쓓g i v沼쌻 d梳쪀 s梳칌",icirc:"K첵 t沼� la-tinh vi梳퓍 th튼沼쓓g i v沼쌻 d梳쪀 m크",iuml:"K첵 t沼� la-tinh vi梳퓍 th튼沼쓓g i v沼쌻 d梳쪀 hai ch梳쩷 tr챗n 휃梳쬾",eth:"K첵 t沼� la-tinh vi梳퓍 th튼沼쓓g c沼쬪 eth",ntilde:"K첵 t沼� la-tinh vi梳퓍 th튼沼쓓g n v沼쌻 d梳쪀 ng찾",ograve:"K첵 t沼� la-tinh vi梳퓍 th튼沼쓓g o v沼쌻 d梳쪀 huy沼걆",oacute:"K첵 t沼� la-tinh vi梳퓍 th튼沼쓓g o v沼쌻 d梳쪀 s梳칌",ocirc:"K첵 t沼� la-tinh vi梳퓍 th튼沼쓓g o v沼쌻 d梳쪀 m크",otilde:"K첵 t沼� la-tinh vi梳퓍 th튼沼쓓g o v沼쌻 d梳쪀 ng찾",ouml:"K첵 t沼� la-tinh vi梳퓍 th튼沼쓓g o v沼쌻 d梳쪀 hai ch梳쩷 tr챗n 휃梳쬾",
divide:"K첵 hi沼뇎 ph챕p t챠nh chia",oslash:"K첵 t沼� la-tinh vi梳퓍 th튼沼쓓g o v沼쌻 d梳쪀 ng찾",ugrave:"K첵 t沼� la-tinh vi梳퓍 th튼沼쓓g u v沼쌻 d梳쪀 huy沼걆",uacute:"K첵 t沼� la-tinh vi梳퓍 th튼沼쓓g u v沼쌻 d梳쪀 s梳칌",ucirc:"K첵 t沼� la-tinh vi梳퓍 th튼沼쓓g u v沼쌻 d梳쪀 m크",uuml:"K첵 t沼� la-tinh vi梳퓍 th튼沼쓓g u v沼쌻 d梳쪀 hai ch梳쩷 tr챗n 휃梳쬾",yacute:"K첵 t沼� la-tinh vi梳퓍 th튼沼쓓g y v沼쌻 d梳쪀 s梳칌",thorn:"K첵 t沼� la-tinh vi梳퓍 th튼沼쓓g c沼쬪 ch沼� thorn",yuml:"K첵 t沼� la-tinh vi梳퓍 th튼沼쓓g y v沼쌻 d梳쪀 hai ch梳쩷 tr챗n 휃梳쬾",OElig:"K첵 t沼� la-tinh vi梳퓍 hoa g梳죅h n沼멼 OE",oelig:"K첵 t沼� la-tinh vi梳퓍 th튼沼쓓g g梳죅h n沼멼 OE",
372:"K첵 t沼� la-tinh vi梳퓍 hoa W v沼쌻 d梳쪀 m크",374:"K첵 t沼� la-tinh vi梳퓍 hoa Y v沼쌻 d梳쪀 m크",373:"K첵 t沼� la-tinh vi梳퓍 th튼沼쓓g w v沼쌻 d梳쪀 m크",375:"K첵 t沼� la-tinh vi梳퓍 th튼沼쓓g y v沼쌻 d梳쪀 m크",sbquo:"D梳쪀 ngo梳톍 휃퉤n th梳쩺 s沼�-9",8219:"D梳쪀 ngo梳톍 휃퉤n 휃梳즣 ng튼沼즓 s沼�-9",bdquo:"G梳쩺 휃척i d梳쪀 ngo梳톍 휃퉤n s沼�-9",hellip:"T칫nh d튼沼즓 chi沼걏 ngang",trade:"K첵 t沼� th튼퉤ng hi沼뇎",9658:"K첵 t沼� tr沼� v沼� h튼沼썀g b챗n ph梳즜 m횪u 휃en",bull:"K첵 hi沼뇎",rarr:"M크i t챗n h튼沼썀g b챗n ph梳즜",rArr:"M크i t챗n h튼沼썀g b챗n ph梳즜 d梳죒g 휃척i",hArr:"M크i t챗n h튼沼썀g b챗n tr찼i d梳죒g 휃척i",diams:"K첵 hi沼뇎 h챙nh thoi",
asymp:"G梳쬷 b梳켷g v沼쌻"});