/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("specialchar","gl",{euro:"S챠mbolo do euro",lsquo:"Comi챰a simple esquerda",rsquo:"Comi챰a simple dereita",ldquo:"Comi챰as dobres esquerda",rdquo:"Comi챰as dobres dereita",ndash:"Gui처n",mdash:"Raia",iexcl:"Signo de admiraci처n invertido",cent:"S챠mbolo do centavo",pound:"S챠mbolo da libra",curren:"S챠mbolo de moeda",yen:"S챠mbolo do yen",brvbar:"Barra vertical rota",sect:"S챠mbolo de secci처n",uml:"Di챕rese",copy:"S챠mbolo de dereitos de autor챠a",ordf:"Indicador ordinal feminino",laquo:"Comi챰as latinas, apertura",
not:"Signo negaci처n",reg:"S챠mbolo de marca rexistrada",macr:"Gui처n alto",deg:"Signo de grao",sup2:"Super챠ndice dous",sup3:"Super챠ndice tres",acute:"Acento agudo",micro:"Signo de micro",para:"Signo de pi",middot:"Punto medio",cedil:"Cedilla",sup1:"Super챠ndice un",ordm:"Indicador ordinal masculino",raquo:"Comi챰as latinas, peche",frac14:"Fracci처n ordinaria de un cuarto",frac12:"Fracci처n ordinaria de un medio",frac34:"Fracci처n ordinaria de tres cuartos",iquest:"Signo de interrogaci처n invertido",Agrave:"Letra A latina mai첬scula con acento grave",
Aacute:"Letra A latina mai첬scula con acento agudo",Acirc:"Letra A latina mai첬scula con acento circunflexo",Atilde:"Letra A latina mai첬scula con til",Auml:"Letra A latina mai첬scula con di챕rese",Aring:"Letra A latina mai첬scula con aro enriba",AElig:"Letra 횈 latina mai첬scula",Ccedil:"Letra C latina mai첬scula con cedilla",Egrave:"Letra E latina mai첬scula con acento grave",Eacute:"Letra E latina mai첬scula con acento agudo",Ecirc:"Letra E latina mai첬scula con acento circunflexo",Euml:"Letra E latina mai첬scula con di챕rese",
Igrave:"Letra I latina mai첬scula con acento grave",Iacute:"Letra I latina mai첬scula con acento agudo",Icirc:"Letra I latina mai첬scula con acento circunflexo",Iuml:"Letra I latina mai첬scula con di챕rese",ETH:"Letra Ed latina mai첬scula",Ntilde:"Letra N latina mai첬scula con til",Ograve:"Letra O latina mai첬scula con acento grave",Oacute:"Letra O latina mai첬scula con acento agudo",Ocirc:"Letra O latina mai첬scula con acento circunflexo",Otilde:"Letra O latina mai첬scula con til",Ouml:"Letra O latina mai첬scula con di챕rese",
times:"Signo de multiplicaci처n",Oslash:"Letra O latina mai첬scula con barra transversal",Ugrave:"Letra U latina mai첬scula con acento grave",Uacute:"Letra U latina mai첬scula con acento agudo",Ucirc:"Letra U latina mai첬scula con acento circunflexo",Uuml:"Letra U latina mai첬scula con di챕rese",Yacute:"Letra Y latina mai첬scula con acento agudo",THORN:"Letra Thorn latina mai첬scula",szlig:"Letra s latina forte min첬scula",agrave:"Letra a latina min첬scula con acento grave",aacute:"Letra a latina min첬scula con acento agudo",
acirc:"Letra a latina min첬scula con acento circunflexo",atilde:"Letra a latina min첬scula con til",auml:"Letra a latina min첬scula con di챕rese",aring:"Letra a latina min첬scula con aro enriba",aelig:"Letra 챈 latina min첬scula",ccedil:"Letra c latina min첬scula con cedilla",egrave:"Letra e latina min첬scula con acento grave",eacute:"Letra e latina min첬scula con acento agudo",ecirc:"Letra e latina min첬scula con acento circunflexo",euml:"Letra e latina min첬scula con di챕rese",igrave:"Letra i latina min첬scula con acento grave",
iacute:"Letra i latina min첬scula con acento agudo",icirc:"Letra i latina min첬scula con acento circunflexo",iuml:"Letra i latina min첬scula con di챕rese",eth:"Letra ed latina min첬scula",ntilde:"Letra n latina min첬scula con til",ograve:"Letra o latina min첬scula con acento grave",oacute:"Letra o latina min첬scula con acento agudo",ocirc:"Letra o latina min첬scula con acento circunflexo",otilde:"Letra o latina min첬scula con til",ouml:"Letra o latina min첬scula con di챕rese",divide:"Signo de divisi처n",oslash:"Letra o latina min첬scula con barra transversal",
ugrave:"Letra u latina min첬scula con acento grave",uacute:"Letra u latina min첬scula con acento agudo",ucirc:"Letra u latina min첬scula con acento circunflexo",uuml:"Letra u latina min첬scula con di챕rese",yacute:"Letra y latina min첬scula con acento agudo",thorn:"Letra Thorn latina min첬scula",yuml:"Letra y latina min첬scula con di챕rese",OElig:"Ligadura OE latina mai첬scula",oelig:"Ligadura oe latina min첬scula",372:"Letra W latina mai첬scula con acento circunflexo",374:"Letra Y latina mai첬scula con acento circunflexo",
373:"Letra w latina min첬scula con acento circunflexo",375:"Letra y latina min첬scula con acento circunflexo",sbquo:"Comi챰a simple baixa, de apertura",8219:"Comi챰a simple alta, de peche",bdquo:"Comi챰as dobres baixas, de apertura",hellip:"Elipse, puntos suspensivos",trade:"Signo de marca rexistrada",9658:"Apuntador negro apuntando 찼 dereita",bull:"Vi챰eta",rarr:"Frecha 찼 dereita",rArr:"Frecha dobre 찼 dereita",hArr:"Frecha dobre da esquerda 찼 dereita",diams:"Diamante negro",asymp:"Case igual a"});