/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("specialchar","he",{euro:"�쇬뺈ⓚ�",lsquo:"遼�쇬왰� 屢�쇬샳뺈� �쇬쀗쇬� 漏�왰먚쑿�",rsquo:"遼�쇬왰� 屢�쇬샳뺈� �쇬쀗쇬� �쇬왰졫�",ldquo:"遼�쇬왰� 屢�쇬샳뺈� �쎰ㅧ뺈� 漏�왰먚쑿�",rdquo:"遼�쇬왰� 屢�쇬샳뺈� �쎰ㅧ뺈� �쇬왰졫�",ndash:"樓�� �왰ㅧⓚ쇬� 樓屢淚",mdash:"樓�� �왰ㅧⓚ쇬� �먚ⓚ뺈�",iexcl:"遼�쇬왰� 樓淚�쇬먚� �붨ㅧ뺈�",cent:"遼�졫�",pound:"壘�먚뺈졫�",curren:"�왰샳뫷�",yen:"�쇬�",brvbar:"樓�� 漏�뫷뺈�",sect:"遼�쇬왰� �왰㎓샳�",uml:"漏瘻�� �졫㎓뺈볊뺈� �먚뺈ㅧ㎓쇬뺈� (Diaeresis)",copy:"遼�쇬왰� �뽛쎰뺈쇬뺈� �쇬뺈┹ⓚ쇬� (Copyright)",ordf:"遼�쇬왰� �먚뺈ⓚ볊쇬졫먚쑿� �졫㎓뫷�",laquo:"遼�쇬왰� 屢�쇬샳뺈� �뽛뺈뺈쇬� �쎰ㅧ뺈쑿� �쑿⒦왰먚�",not:"遼�쇬왰� 漏�쑿쇬쑿� �왰ぷ왰샳�",reg:"遼�쇬왰� 淚漏�뺈�",
macr:"�왰㎓ⓚ뺈� (�붨믕쇬� �먚ⓚ뺈쎰�)",deg:"�왰↙쑿뺈�",sup2:"2 �뫷쎰ぷ쇬� 鬧�쇬쑿�",sup3:"3 �뫷쎰ぷ쇬� 鬧�쇬쑿�",acute:"遼�쇬왰� �볊믕뺈� (Acute)",micro:"�왰쇬㎓ⓚ�",para:"遼�쇬왰뺈� 壘遼樓��",middot:"�졫㎓뺈볊� �먚왰┹↙쇬�",cedil:"遼�볊쇬쑿쇬�",sup1:"1 �뫷쎰ぷ쇬� 鬧�쇬쑿�",ordm:"遼�쇬왰� �먚뺈ⓚ볊쇬졫먚쑿� �뽛쎰ⓚ�",raquo:"遼�쇬왰� 屢�쇬샳뺈� �뽛뺈뺈쇬� �쎰ㅧ뺈쑿� �쑿쇬왰쇬�",frac14:"淚�뫷� �뫷⒦뫷� 壘漏�뺈�",frac12:"�쀗┹� �뫷⒦뫷� 壘漏�뺈�",frac34:"漏�쑿뺈⒦� 淚�뫷↙쇬� �뫷⒦뫷� 壘漏�뺈�",iquest:"遼�쇬왰� 漏�먚쑿� �붨ㅧ뺈�",Agrave:"�먚뺈� �쑿샳쇬졫쇬� A 鬧�� �믕ⓚ� (Grave)",Aacute:"Latin capital letter A with acute accent",Acirc:"Latin capital letter A with circumflex",Atilde:"Latin capital letter A with tilde",
Auml:"Latin capital letter A with diaeresis",Aring:"Latin capital letter A with ring above",AElig:"�먚뺈� �쑿샳쇬졫쇬� 횈 �믕볊뺈쑿�",Ccedil:"Latin capital letter C with cedilla",Egrave:"�먚뺈� �쑿샳쇬졫쇬� E 鬧�� �믕ⓚ� (Grave)",Eacute:"Latin capital letter E with acute accent",Ecirc:"Latin capital letter E with circumflex",Euml:"Latin capital letter E with diaeresis",Igrave:"�먚뺈� �쑿샳쇬졫쇬� I 鬧�� �믕ⓚ� (Grave)",Iacute:"Latin capital letter I with acute accent",Icirc:"Latin capital letter I with circumflex",Iuml:"Latin capital letter I with diaeresis",
ETH:"�먚뺈� �쑿샳쇬졫쇬� Eth �믕볊뺈쑿�",Ntilde:"Latin capital letter N with tilde",Ograve:"�먚뺈� �쑿샳쇬졫쇬� O 鬧�� �믕ⓚ� (Grave)",Oacute:"Latin capital letter O with acute accent",Ocirc:"Latin capital letter O with circumflex",Otilde:"Latin capital letter O with tilde",Ouml:"Latin capital letter O with diaeresis",times:"遼�쇬왰� �쎰ㅧ�",Oslash:"Latin capital letter O with stroke",Ugrave:"�먚뺈� �쑿샳쇬졫쇬� U 鬧�� �믕ⓚ� (Grave)",Uacute:"Latin capital letter U with acute accent",Ucirc:"Latin capital letter U with circumflex",Uuml:"Latin capital letter U with diaeresis",
Yacute:"Latin capital letter Y with acute accent",THORN:"�먚뺈� �쑿샳쇬졫쇬� Thorn �믕볊뺈쑿�",szlig:"�먚뺈� �쑿샳쇬졫쇬� s �쀗볊� 樓�샳졫�",agrave:"�먚뺈� �쑿샳쇬졫쇬� a 鬧�� �믕ⓚ� (Grave)",aacute:"Latin small letter a with acute accent",acirc:"Latin small letter a with circumflex",atilde:"Latin small letter a with tilde",auml:"Latin small letter a with diaeresis",aring:"Latin small letter a with ring above",aelig:"�먚뺈� �쑿샳쇬졫쇬� 챈 樓�샳졫�",ccedil:"Latin small letter c with cedilla",egrave:"�먚뺈� �쑿샳쇬졫쇬� e 鬧�� �믕ⓚ� (Grave)",eacute:"Latin small letter e with acute accent",
ecirc:"Latin small letter e with circumflex",euml:"Latin small letter e with diaeresis",igrave:"�먚뺈� �쑿샳쇬졫쇬� i 鬧�� �믕ⓚ� (Grave)",iacute:"Latin small letter i with acute accent",icirc:"Latin small letter i with circumflex",iuml:"Latin small letter i with diaeresis",eth:"�먚뺈� �쑿샳쇬졫쇬� eth 樓�샳졫�",ntilde:"Latin small letter n with tilde",ograve:"�먚뺈� �쑿샳쇬졫쇬� o 鬧�� �믕ⓚ� (Grave)",oacute:"Latin small letter o with acute accent",ocirc:"Latin small letter o with circumflex",otilde:"Latin small letter o with tilde",ouml:"Latin small letter o with diaeresis",
divide:"遼�쇬왰� �쀗쑿뺈㎓�",oslash:"Latin small letter o with stroke",ugrave:"�먚뺈� �쑿샳쇬졫쇬� u 鬧�� �믕ⓚ� (Grave)",uacute:"Latin small letter u with acute accent",ucirc:"Latin small letter u with circumflex",uuml:"Latin small letter u with diaeresis",yacute:"Latin small letter y with acute accent",thorn:"�먚뺈� �쑿샳쇬졫쇬� thorn 樓�샳졫�",yuml:"Latin small letter y with diaeresis",OElig:"Latin capital ligature OE",oelig:"Latin small ligature oe",372:"Latin capital letter W with circumflex",374:"Latin capital letter Y with circumflex",
373:"Latin small letter w with circumflex",375:"Latin small letter y with circumflex",sbquo:"遼�쇬왰� 屢�쇬샳뺈� �졫왰뺈� �쇬쀗쇬�",8219:"遼�쇬왰� 屢�쇬샳뺈�",bdquo:"遼�쇬왰� 屢�쇬샳뺈� �졫왰뺈� �쎰ㅧ뺈�",hellip:"漏�쑿뺈� �졫㎓뺈볊뺈�",trade:"遼�쇬왰� �샳ⓚ쇬쇬볊왰먚ⓚ�",9658:"遼�왰� 漏�쀗뺈� �쑿┹� �쇬왰쇬�",bull:"瘻�뫷쑿쇬� (淚漏�쇬왰�)",rarr:"�쀗� �쑿쇬왰쇬�",rArr:"�쀗� �쎰ㅧ뺈� �쑿쇬왰쇬�",hArr:"�쀗� �쎰ㅧ뺈� �쑿쇬왰쇬� �뺈⒦왰먚�",diams:"�쇬붨쑿뺈� �왰쑿�",asymp:"�쎰왰↙� 漏�뺈뺈�"});