/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("specialchar","sl",{euro:"Evro znak",lsquo:"Levi enojni narekovaj",rsquo:"Desni enojni narekovaj",ldquo:"Levi dvojni narekovaj",rdquo:"Desni dvojni narekovaj",ndash:"En pomi큄ljaj",mdash:"Em pomi큄ljaj",iexcl:"Obrnjen klicaj",cent:"Cent znak",pound:"Funt znak",curren:"Znak valute",yen:"Jen znak",brvbar:"Zlomljena 훾rta",sect:"Znak oddelka",uml:"Diaeresis",copy:"Znak avtorskih pravic",ordf:"탐enski zaporedni kazalnik",laquo:"Levi obrnjen dvojni kotni narekovaj",not:"Ne znak",reg:"Registrirani znak",
macr:"Macron",deg:"Znak stopinj",sup2:"Nadpisano dva",sup3:"Nadpisano tri",acute:"Ostrivec",micro:"Mikro znak",para:"Pilcrow znak",middot:"Sredinska pika",cedil:"Cedilla",sup1:"Nadpisano ena",ordm:"Mo큄ki zaporedni kazalnik",raquo:"Desno obrnjen dvojni kotni narekovaj",frac14:"Ena 훾etrtina",frac12:"Ena polovica",frac34:"Tri 훾etrtine",iquest:"Obrnjen vpra큄aj",Agrave:"Velika latinska 훾rka A s krativcem",Aacute:"Velika latinska 훾rka A z ostrivcem",Acirc:"Velika latinska 훾rka A s stre큄ico",Atilde:"Velika latinska 훾rka A z tildo",
Auml:"Velika latinska 훾rka A z diaeresis-om",Aring:"Velika latinska 훾rka A z obro훾em",AElig:"Velika latinska 훾rka 횈",Ccedil:"Velika latinska 훾rka C s cedillo",Egrave:"Velika latinska 훾rka E s krativcem",Eacute:"Velika latinska 훾rka E z ostrivcem",Ecirc:"Velika latinska 훾rka E s stre큄ico",Euml:"Velika latinska 훾rka E z diaeresis-om",Igrave:"Velika latinska 훾rka I s krativcem",Iacute:"Velika latinska 훾rka I z ostrivcem",Icirc:"Velika latinska 훾rka I s stre큄ico",Iuml:"Velika latinska 훾rka I z diaeresis-om",
ETH:"Velika latinska 훾rka Eth",Ntilde:"Velika latinska 훾rka N s tildo",Ograve:"Velika latinska 훾rka O s krativcem",Oacute:"Velika latinska 훾rka O z ostrivcem",Ocirc:"Velika latinska 훾rka O s stre큄ico",Otilde:"Velika latinska 훾rka O s tildo",Ouml:"Velika latinska 훾rka O z diaeresis-om",times:"Znak za mno탑enje",Oslash:"Velika pre훾rtana latinska 훾rka O",Ugrave:"Velika latinska 훾rka U s krativcem",Uacute:"Velika latinska 훾rka U z ostrivcem",Ucirc:"Velika latinska 훾rka U s stre큄ico",Uuml:"Velika latinska 훾rka U z diaeresis-om",
Yacute:"Velika latinska 훾rka Y z ostrivcem",THORN:"Velika latinska 훾rka Thorn",szlig:"Mala ostra latinska 훾rka s",agrave:"Mala latinska 훾rka a s krativcem",aacute:"Mala latinska 훾rka a z ostrivcem",acirc:"Mala latinska 훾rka a s stre큄ico",atilde:"Mala latinska 훾rka a s tildo",auml:"Mala latinska 훾rka a z diaeresis-om",aring:"Mala latinska 훾rka a z obro훾em",aelig:"Mala latinska 훾rka 챈",ccedil:"Mala latinska 훾rka c s cedillo",egrave:"Mala latinska 훾rka e s krativcem",eacute:"Mala latinska 훾rka e z ostrivcem",
ecirc:"Mala latinska 훾rka e s stre큄ico",euml:"Mala latinska 훾rka e z diaeresis-om",igrave:"Mala latinska 훾rka i s krativcem",iacute:"Mala latinska 훾rka i z ostrivcem",icirc:"Mala latinska 훾rka i s stre큄ico",iuml:"Mala latinska 훾rka i z diaeresis-om",eth:"Mala latinska 훾rka eth",ntilde:"Mala latinska 훾rka n s tildo",ograve:"Mala latinska 훾rka o s krativcem",oacute:"Mala latinska 훾rka o z ostrivcem",ocirc:"Mala latinska 훾rka o s stre큄ico",otilde:"Mala latinska 훾rka o s tildo",ouml:"Mala latinska 훾rka o z diaeresis-om",
divide:"Znak za deljenje",oslash:"Mala pre훾rtana latinska 훾rka o",ugrave:"Mala latinska 훾rka u s krativcem",uacute:"Mala latinska 훾rka u z ostrivcem",ucirc:"Mala latinska 훾rka u s stre큄ico",uuml:"Mala latinska 훾rka u z diaeresis-om",yacute:"Mala latinska 훾rka y z ostrivcem",thorn:"Mala latinska 훾rka thorn",yuml:"Mala latinska 훾rka y z diaeresis-om",OElig:"Velika latinska ligatura OE",oelig:"Mala latinska ligatura oe",372:"Velika latinska 훾rka W s stre큄ico",374:"Velika latinska 훾rka Y s stre큄ico",
373:"Mala latinska 훾rka w s stre큄ico",375:"Mala latinska 훾rka y s stre큄ico",sbquo:"Enojni nizki-9 narekovaj",8219:"Enojni visoki-obrnjen-9 narekovaj",bdquo:"Dvojni nizki-9 narekovaj",hellip:"Horizontalni izpust",trade:"Znak blagovne znamke",9658:"훻rni desno-usmerjen kazalec",bull:"Krogla",rarr:"Desno-usmerjena pu큄훾ica",rArr:"Desno-usmerjena dvojna pu큄훾ica",hArr:"Leva in desna dvojna pu큄훾ica",diams:"훻rna kara",asymp:"Skoraj enako"});