/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("specialchar","sq",{euro:"Shenja e Euros",lsquo:"Thonj챘za majtas me nj챘 vi",rsquo:"Thonj챘za djathtas me nj챘 vi",ldquo:"Thonj챘za majtas",rdquo:"Thonj챘za djathtas",ndash:"En viza lidh챘se",mdash:"Em viza lidh챘se",iexcl:"Pik챘챌udit챘se e p챘rmbysur",cent:"Shenja e Centit",pound:"Shejna e Funtit",curren:"Shenja e valut챘s",yen:"Shenja e Jenit",brvbar:"Viza e k챘putur",sect:"Shenja e pjes챘s",uml:"Diaeresis",copy:"Shenja e t챘 drejtave t챘 kopjimit",ordf:"Feminine ordinal indicator",laquo:"Left-pointing double angle quotation mark",
not:"Nuk ka shenj챘",reg:"Shenja e t챘 regjistruarit",macr:"Macron",deg:"Shenja e shkall챘s",sup2:"Super-skripta dy",sup3:"Super-skripta tre",acute:"Theks i mpreht챘",micro:"Shjenja e Mikros",para:"Pilcrow sign",middot:"Pika e Mesme",cedil:"Hark n챘n shkronja",sup1:"Super-skripta nj챘",ordm:"Masculine ordinal indicator",raquo:"Right-pointing double angle quotation mark",frac14:"Thyesa nj챘 t챘 katrat",frac12:"Thyesa nj챘 t챘 dytat",frac34:"Thyesa tre t챘 katrat",iquest:"Pik챘pyetje e p챘rmbysur",Agrave:"Shkronja e madhe latine A me theks t챘 r챘nd챘",
Aacute:"Shkronja e madhe latine A me theks akute",Acirc:"Shkronja e madhe latine A me theks lakor",Atilde:"Shkronja e madhe latine A me tild챘",Auml:"Shkronja e madhe latine A me dy pika",Aring:"Shkronja e madhe latine A me unaz챘 mbi",AElig:"Shkronja e madhe latine 횈",Ccedil:"Shkronja e madhe latine C me hark posht챘",Egrave:"Shkronja e madhe latine E me theks t챘 r챘nd챘",Eacute:"Shkronja e madhe latine E me theks akute",Ecirc:"Shkronja e madhe latine E me theks lakor",Euml:"Shkronja e madhe latine E me dy pika",
Igrave:"Shkronja e madhe latine I me theks t챘 r챘nd챘",Iacute:"Shkronja e madhe latine I me theks akute",Icirc:"Shkronja e madhe latine I me theks lakor",Iuml:"Shkronja e madhe latine I me dy pika",ETH:"Shkronja e madhe latine Eth",Ntilde:"Shkronja e madhe latine N me tild챘",Ograve:"Shkronja e madhe latine O me theks t챘 r챘nd챘",Oacute:"Shkronja e madhe latine O me theks akute",Ocirc:"Shkronja e madhe latine O me theks lakor",Otilde:"Shkronja e madhe latine O me tild챘",Ouml:"Shkronja e madhe latine O me dy pika",
times:"Shenja e shum챘zimit",Oslash:"Shkronja e madhe latine O me viz챘 n챘 mes",Ugrave:"Shkronja e madhe latine U me theks t챘 r챘nd챘",Uacute:"Shkronja e madhe latine U me theks akute",Ucirc:"Shkronja e madhe latine U me theks lakor",Uuml:"Shkronja e madhe latine U me dy pika",Yacute:"Shkronja e madhe latine Y me theks akute",THORN:"Shkronja e madhe latine Thorn",szlig:"Shkronja e vog챘 latine s e mpreht챘",agrave:"Shkronja e vog챘 latine a me theks t챘 r챘nd챘",aacute:"Shkronja e vog챘 latine a me theks t챘 mpreht챘",
acirc:"Shkronja e vog챘l latine a me theks lakor",atilde:"Shkronja e vog챘l latine a me tild챘",auml:"Shkronja e vog챘l latine a me dy pika",aring:"Shkronja e vog챘 latine a me unaz챘 mbi",aelig:"Shkronja e vog챘 latine 챈",ccedil:"Shkronja e vog챘l latine c me hark posht챘",egrave:"Shkronja e vog챘 latine e me theks t챘 r챘nd챘",eacute:"Shkronja e vog챘 latine e me theks t챘 mpreht챘",ecirc:"Shkronja e vog챘l latine e me theks lakor",euml:"Shkronja e vog챘l latine e me dy pika",igrave:"Shkronja e vog챘 latine i me theks t챘 r챘nd챘",
iacute:"Shkronja e vog챘 latine i me theks t챘 mpreht챘",icirc:"Shkronja e vog챘l latine i me theks lakor",iuml:"Shkronja e vog챘l latine i me dy pika",eth:"Shkronja e vog챘 latine eth",ntilde:"Shkronja e vog챘l latine n me tild챘",ograve:"Shkronja e vog챘 latine o me theks t챘 r챘nd챘",oacute:"Shkronja e vog챘 latine o me theks t챘 mpreht챘",ocirc:"Shkronja e vog챘l latine o me theks lakor",otilde:"Shkronja e vog챘l latine o me tild챘",ouml:"Shkronja e vog챘l latine o me dy pika",divide:"Shenja ndar챘se",oslash:"Shkronja e vog챘l latine o me viz챘 n챘 mes",
ugrave:"Shkronja e vog챘 latine u me theks t챘 r챘nd챘",uacute:"Shkronja e vog챘 latine u me theks t챘 mpreht챘",ucirc:"Shkronja e vog챘l latine u me theks lakor",uuml:"Shkronja e vog챘l latine u me dy pika",yacute:"Shkronja e vog챘 latine y me theks t챘 mpreht챘",thorn:"Shkronja e vog챘l latine thorn",yuml:"Shkronja e vog챘l latine y me dy pika",OElig:"Shkronja e madhe e bashkuar latine OE",oelig:"Shkronja e vog챘l e bashkuar latine oe",372:"Shkronja e madhe latine W me theks lakor",374:"Shkronja e madhe latine Y me theks lakor",
373:"Shkronja e vog챘l latine w me theks lakor",375:"Shkronja e vog챘l latine y me theks lakor",sbquo:"Single low-9 quotation mark",8219:"Single high-reversed-9 quotation mark",bdquo:"Double low-9 quotation mark",hellip:"Horizontal ellipsis",trade:"Shenja e Simbolit Tregtar챘",9658:"Black right-pointing pointer",bull:"Pulla",rarr:"Shigjeta djathtas",rArr:"Shenja t챘 dyfishta djathtas",hArr:"Shigjeta e dyfish챘 majtas-djathtas",diams:"Black diamond suit",asymp:"Gati e barabar me"});