/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.38
 * Generated at: 2016-11-04 03:50:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin.inc;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

	String menuName = (String)request.getParameter("menu_name");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<!--\r\n");
      out.write("This is a starter template page. Use this page to start your new project from\r\n");
      out.write("scratch. This page gets rid of all links and provides the needed markup only.\r\n");
      out.write("-->\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("  <title>Min Admin</title>\r\n");
      out.write("  <!-- Tell the browser to be responsive to screen width -->\r\n");
      out.write("  <meta content=\"width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no\" name=\"viewport\">\r\n");
      out.write("  <!-- Bootstrap 3.3.6 -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"../resources/bootstrap/css/bootstrap.min.css\">\r\n");
      out.write("  <!-- Font Awesome -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css\">\r\n");
      out.write("  <!-- Ionicons -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css\">\r\n");
      out.write("    <!-- DataTables -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"../resources/plugins/datatables/dataTables.bootstrap.css\">\r\n");
      out.write("  <!-- Theme style -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"../resources/dist/css/AdminLTE.min.css\">\r\n");
      out.write("  <!-- iCheck -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"../resources/plugins/iCheck/flat/blue.css\">\r\n");
      out.write("  <!-- AdminLTE Skins. We have chosen the skin-blue for this starter\r\n");
      out.write("        page. However, you can choose any other skin. Make sure you\r\n");
      out.write("        apply the skin class to the body tag so the changes take effect.\r\n");
      out.write("  -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"../resources/dist/css/skins/skin-blue.min.css\">\r\n");
      out.write("\r\n");
      out.write("  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->\r\n");
      out.write("  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->\r\n");
      out.write("  <!--[if lt IE 9]>\r\n");
      out.write("  <script src=\"https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js\"></script>\r\n");
      out.write("  <script src=\"https://oss.maxcdn.com/respond/1.4.2/respond.min.js\"></script>\r\n");
      out.write("  <![endif]-->\r\n");
      out.write("</head>\r\n");
      out.write("<!--\r\n");
      out.write("BODY TAG OPTIONS:\r\n");
      out.write("=================\r\n");
      out.write("Apply one or more of the following classes to get the\r\n");
      out.write("desired effect\r\n");
      out.write("|---------------------------------------------------------|\r\n");
      out.write("| SKINS         | skin-blue                               |\r\n");
      out.write("|               | skin-black                              |\r\n");
      out.write("|               | skin-purple                             |\r\n");
      out.write("|               | skin-yellow                             |\r\n");
      out.write("|               | skin-red                                |\r\n");
      out.write("|               | skin-green                              |\r\n");
      out.write("|---------------------------------------------------------|\r\n");
      out.write("|LAYOUT OPTIONS | fixed                                   |\r\n");
      out.write("|               | layout-boxed                            |\r\n");
      out.write("|               | layout-top-nav                          |\r\n");
      out.write("|               | sidebar-collapse                        |\r\n");
      out.write("|               | sidebar-mini                            |\r\n");
      out.write("|---------------------------------------------------------|\r\n");
      out.write("-->\r\n");
      out.write("<body class=\"hold-transition skin-blue sidebar-mini\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <!-- Main Header -->\r\n");
      out.write("  <header class=\"main-header\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Logo -->\r\n");
      out.write("    <a href=\"index2.html\" class=\"logo\">\r\n");
      out.write("      <!-- mini logo for sidebar mini 50x50 pixels -->\r\n");
      out.write("      <span class=\"logo-mini\"><b>MS</b>A</span>\r\n");
      out.write("      <!-- logo for regular state and mobile devices -->\r\n");
      out.write("      <span class=\"logo-lg\"><b>MS</b>Admin</span>\r\n");
      out.write("    </a>\r\n");
      out.write("\r\n");
      out.write("    <!-- Header Navbar -->\r\n");
      out.write("    <nav class=\"navbar navbar-static-top\" role=\"navigation\">\r\n");
      out.write("      <!-- Sidebar toggle button-->\r\n");
      out.write("      <a href=\"#\" class=\"sidebar-toggle\" data-toggle=\"offcanvas\" role=\"button\">\r\n");
      out.write("        <span class=\"sr-only\">Toggle navigation</span>\r\n");
      out.write("      </a>\r\n");
      out.write("      <!-- Navbar Right Menu -->\r\n");
      out.write("      <div class=\"navbar-custom-menu\">\r\n");
      out.write("        <ul class=\"nav navbar-nav\">\r\n");
      out.write("          <!-- Messages: style can be found in dropdown.less-->\r\n");
      out.write("          <li class=\"dropdown messages-menu\">\r\n");
      out.write("          <!-- Notifications Menu -->\r\n");
      out.write("          <li class=\"dropdown notifications-menu\">\r\n");
      out.write("            <!-- Menu toggle button -->\r\n");
      out.write("            <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">\r\n");
      out.write("              <i class=\"fa fa-bell-o\"></i>\r\n");
      out.write("              <span class=\"label label-warning\">10</span>\r\n");
      out.write("            </a>\r\n");
      out.write("            <ul class=\"dropdown-menu\">\r\n");
      out.write("              <li class=\"header\">You have 10 notifications</li>\r\n");
      out.write("              <li>\r\n");
      out.write("                <!-- Inner Menu: contains the notifications -->\r\n");
      out.write("                <ul class=\"menu\">\r\n");
      out.write("                  <li><!-- start notification -->\r\n");
      out.write("                    <a href=\"#\">\r\n");
      out.write("                      <i class=\"fa fa-users text-aqua\"></i> 5 new members joined today\r\n");
      out.write("                    </a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <!-- end notification -->\r\n");
      out.write("                </ul>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"footer\"><a href=\"#\">View all</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </li>\r\n");
      out.write("          <!-- User Account Menu -->\r\n");
      out.write("          <li class=\"dropdown user user-menu\">\r\n");
      out.write("            <!-- Menu Toggle Button -->\r\n");
      out.write("            <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" >\r\n");
      out.write("              <!-- The user image in the navbar-->\r\n");
      out.write("              <img src=\"../resources/dist/img/user2-160x160.jpg\" class=\"user-image\" alt=\"User Image\">\r\n");
      out.write("              <!-- hidden-xs hides the username on small devices so only the image appears. -->\r\n");
      out.write("              <span class=\"hidden-xs\">User Name</span>\r\n");
      out.write("            </a>\r\n");
      out.write("            <ul class=\"dropdown-menu\">\r\n");
      out.write("              <!-- The user image in the menu -->\r\n");
      out.write("              <li class=\"user-header\">\r\n");
      out.write("                <img src=\"../resources/dist/img/user2-160x160.jpg\" class=\"img-circle\" alt=\"User Image\">\r\n");
      out.write("\r\n");
      out.write("                <p>\r\n");
      out.write("                  Alexander Pierce - Web Developer\r\n");
      out.write("                  <small>Member since Nov. 2012</small>\r\n");
      out.write("                </p>\r\n");
      out.write("              </li>\r\n");
      out.write("              \r\n");
      out.write("              <!-- Menu Footer-->\r\n");
      out.write("              <li class=\"user-footer\">\r\n");
      out.write("                <div class=\"pull-left\">\r\n");
      out.write("                  <a href=\"#\" class=\"btn btn-default btn-flat\">Profile</a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"pull-right\">\r\n");
      out.write("                  <a href=\"#\" class=\"btn btn-default btn-flat\">Sign out</a>\r\n");
      out.write("                </div>\r\n");
      out.write("              </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("  </header>\r\n");
      out.write("  <!-- Left side column. contains the logo and sidebar -->\r\n");
      out.write("  <aside class=\"main-sidebar\">\r\n");
      out.write("\r\n");
      out.write("    <!-- sidebar: style can be found in sidebar.less -->\r\n");
      out.write("    <section class=\"sidebar\">\r\n");
      out.write("\r\n");
      out.write("      <!-- Sidebar Menu -->\r\n");
      out.write("      <ul class=\"sidebar-menu\">\r\n");
      out.write("      \t");
if(menuName.equals("dash_board")){
      out.write("\r\n");
      out.write("      \t<li class=\"active\">\r\n");
      out.write("      \t");
}else{ 
      out.write("\r\n");
      out.write("      \t<li class=\"\">\r\n");
      out.write("      \t");
} 
      out.write("\r\n");
      out.write("      \t<a href=\"dash_board.jsp\"><i class=\"fa fa-dashboard\"></i> <span>알림판</span></a></li>\r\n");
      out.write("      \t");
if(menuName.equals("main")){
      out.write("\r\n");
      out.write("      \t<li class=\"treeview active\">\r\n");
      out.write("      \t");
}else{ 
      out.write("\r\n");
      out.write("      \t<li class=\"treeview\">\r\n");
      out.write("      \t");
} 
      out.write("\r\n");
      out.write("          <a href=\"#\"><i class=\"fa fa-home\"></i> <span>메인</span>\r\n");
      out.write("            <span class=\"pull-right-container\">\r\n");
      out.write("              <i class=\"fa fa-angle-left pull-right\"></i>\r\n");
      out.write("            </span>\r\n");
      out.write("          </a>\r\n");
      out.write("          <ul class=\"treeview-menu\">\r\n");
      out.write("            <li><a href=\"main_package.jsp\">패캐지 상품</a></li>\r\n");
      out.write("            <li><a href=\"main_theory.jsp\">이론 상품</a></li>\r\n");
      out.write("            <li><a href=\"main_project.jsp\">프로젝트 상품</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("        ");
if(menuName.equals("lecture")){
      out.write("\r\n");
      out.write("      \t<li class=\"treeview active\">\r\n");
      out.write("      \t");
}else{ 
      out.write("\r\n");
      out.write("      \t<li class=\"treeview\">\r\n");
      out.write("      \t");
} 
      out.write("\r\n");
      out.write("          <a href=\"#\"><i class=\"fa fa-youtube-play\"></i> <span>강의</span>\r\n");
      out.write("            <span class=\"pull-right-container\">\r\n");
      out.write("              <i class=\"fa fa-angle-left pull-right\"></i>\r\n");
      out.write("            </span>\r\n");
      out.write("          </a>\r\n");
      out.write("          <ul class=\"treeview-menu\">\r\n");
      out.write("            <li><a href=\"/admin/listleccat.do\">모든 카테고리</a></li>\r\n");
      out.write("            <li><a href=\"lecture_category_insert.jsp\">카테고리 추가</a></li>\r\n");
      out.write("            <li><a href=\"/admin/listlec.do?select=0\">모든 강의</a></li>\r\n");
      out.write("            <li><a href=\"/admin/insertlec.do\">강의 올리기</a></li>\r\n");
      out.write("            <li><a href=\"lecture_question.jsp\">질문</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("        ");
if(menuName.equals("post")){
      out.write("\r\n");
      out.write("      \t<li class=\"treeview active\">\r\n");
      out.write("      \t");
}else{ 
      out.write("\r\n");
      out.write("      \t<li class=\"treeview\">\r\n");
      out.write("      \t");
} 
      out.write("\r\n");
      out.write("          <a href=\"#\"><i class=\"fa fa-pencil\"></i> <span>글</span>\r\n");
      out.write("            <span class=\"pull-right-container\">\r\n");
      out.write("              <i class=\"fa fa-angle-left pull-right\"></i>\r\n");
      out.write("            </span>\r\n");
      out.write("          </a>\r\n");
      out.write("          <ul class=\"treeview-menu\">\r\n");
      out.write("            <li><a href=\"post_category.jsp\">카테고리</a></li>\r\n");
      out.write("            <li><a href=\"post_all.jsp\">모든 글</a></li>\r\n");
      out.write("            <li><a href=\"post_insert.jsp\">새 글쓰기</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("        ");
if(menuName.equals("file")){
      out.write("\r\n");
      out.write("      \t<li class=\"treeview active\">\r\n");
      out.write("      \t");
}else{ 
      out.write("\r\n");
      out.write("      \t<li class=\"treeview\">\r\n");
      out.write("      \t");
} 
      out.write("\r\n");
      out.write("          <a href=\"#\"><i class=\"fa fa-file\"></i> <span>파일</span>\r\n");
      out.write("            <span class=\"pull-right-container\">\r\n");
      out.write("              <i class=\"fa fa-angle-left pull-right\"></i>\r\n");
      out.write("            </span>\r\n");
      out.write("          </a>\r\n");
      out.write("          <ul class=\"treeview-menu\">\r\n");
      out.write("            <li><a href=\"file_picture.jsp\">사진</a></li>\r\n");
      out.write("            <li><a href=\"file_homework.jsp\">과제</a></li>\r\n");
      out.write("            <li><a href=\"file_insert.jsp\">파일 올리기</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("        ");
if(menuName.equals("comments")){
      out.write("\r\n");
      out.write("      \t<li class=\"active\">\r\n");
      out.write("      \t");
}else{ 
      out.write("\r\n");
      out.write("      \t<li class=\"\">\r\n");
      out.write("      \t");
} 
      out.write("\r\n");
      out.write("        <a href=\"comments.jsp\"><i class=\"fa fa-comments\"></i> <span>댓글</span></a></li>\r\n");
      out.write("        ");
if(menuName.equals("user")){
      out.write("\r\n");
      out.write("      \t<li class=\"treeview active\">\r\n");
      out.write("      \t");
}else{ 
      out.write("\r\n");
      out.write("      \t<li class=\"treeview\">\r\n");
      out.write("      \t");
} 
      out.write("\r\n");
      out.write("          <a href=\"#\"><i class=\"fa fa-users\"></i> <span>사용자</span>\r\n");
      out.write("            <span class=\"pull-right-container\">\r\n");
      out.write("              <i class=\"fa fa-angle-left pull-right\"></i>\r\n");
      out.write("            </span>\r\n");
      out.write("          </a>\r\n");
      out.write("          <ul class=\"treeview-menu\">\r\n");
      out.write("            <li><a href=\"/admin/listuser.do?select=0\">모든 사용자</a></li>\r\n");
      out.write("            <li><a href=\"user_payment.jsp\">결제 대기 중인 사용자</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("        ");
if(menuName.equals("admin")){
      out.write("\r\n");
      out.write("      \t<li class=\"treeview active\">\r\n");
      out.write("      \t");
}else{ 
      out.write("\r\n");
      out.write("      \t<li class=\"treeview\">\r\n");
      out.write("      \t");
} 
      out.write("\r\n");
      out.write("          <a href=\"#\"><i class=\"fa fa-lock\"></i> <span>관리자</span>\r\n");
      out.write("            <span class=\"pull-right-container\">\r\n");
      out.write("              <i class=\"fa fa-angle-left pull-right\"></i>\r\n");
      out.write("            </span>\r\n");
      out.write("          </a>\r\n");
      out.write("          <ul class=\"treeview-menu\">\r\n");
      out.write("            <li><a href=\"admin_all.jsp\">모든 관리자</a></li>\r\n");
      out.write("            <li><a href=\"admin_profile.jsp\">나의 프로필</a></li>\r\n");
      out.write("            <li><a href=\"admin_insert.jsp\">관리자 추가</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("      </ul>\r\n");
      out.write("      <!-- /.sidebar-menu -->\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- /.sidebar -->\r\n");
      out.write("  </aside>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
