/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.38
 * Generated at: 2016-11-04 05:39:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.min.domain.LectureCategory;
import java.util.List;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/inc/footer_main.jsp", Long.valueOf(1478234704875L));
    _jspx_dependants.put("/inc/header_main.jsp", Long.valueOf(1478237130424L));
    _jspx_dependants.put("/inc/modal.jsp", Long.valueOf(1478217816985L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.min.domain.LectureCategory");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	List listLecCat = (List)request.getAttribute("listLecCat");

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<!-- <link rel=\"stylesheet\" type=\"text/css\" href=\"css/hyeon_style.css\"> -->\r\n");
      out.write("<!-- 합쳐지고 최소화된 최신 CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- Carousel Theme -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/style_main.css\">\r\n");
      out.write("\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!-- The Modal -->\r\n");
      out.write("<div id=\"loginModal\" class=\"modal\">\r\n");
      out.write("\t<!-- Modal content -->\r\n");
      out.write("\t<div class=\"modal-content\">\r\n");
      out.write("\t\t<div id=\"naver_id_login\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("<header>\r\n");
      out.write("\t<div class=\"navbar-wrapper\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("        <nav class=\"navbar navbar-static-top\">\r\n");
      out.write("          <div class=\"container\">\r\n");
      out.write("            <div class=\"navbar-header\">\r\n");
      out.write("              <button type=\"button\" class=\"navbar-toggle collapsed\" data-toggle=\"collapse\" data-target=\"#navbar\" aria-expanded=\"false\" aria-controls=\"navbar\">\r\n");
      out.write("                <span class=\"sr-only\">Toggle navigation</span>\r\n");
      out.write("                <span class=\"icon-bar\"></span>\r\n");
      out.write("                <span class=\"icon-bar\"></span>\r\n");
      out.write("                <span class=\"icon-bar\"></span>\r\n");
      out.write("              </button>\r\n");
      out.write("              <a class=\"navbar-brand\" href=\"#\"><img alt=\"logo\" src=\"/data/img/logo.png\" ></a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"navbar\" class=\"navbar-collapse collapse\">\r\n");
      out.write("              <ul class=\"nav navbar-nav\">\r\n");
      out.write("                <li><a href=\"/lecture/index.do\">온라인 강의</a></li>\r\n");
      out.write("                <li><a href=\"#\">실전 프로젝트</a></li>\r\n");
      out.write("                <li class=\"dropdown\">\r\n");
      out.write("                  <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" role=\"button\" aria-expanded=\"false\">커뮤니티<span class=\"caret\"></span></a>\r\n");
      out.write("                  <ul class=\"dropdown-menu\" role=\"menu\">\r\n");
      out.write("                    <li><a href=\"#\">공지사항</a></li>\r\n");
      out.write("                    <li><a href=\"#\">민쌤 엿보기</a></li>\r\n");
      out.write("                    <li><a href=\"#\">과제 게시판</a></li>\r\n");
      out.write("                    <li><a href=\"#\">프로젝트 경연</a></li>\r\n");
      out.write("                    <li><a href=\"#\">IT 블로그</a></li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                \r\n");
      out.write("             \t</ul>\r\n");
      out.write("\t\t\t\t<ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#contact\">고객센터</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a id=\"btnLogin\">로그인</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </nav>\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <!-- Carousel\r\n");
      out.write("    ================================================== -->\r\n");
      out.write("    <div id=\"myCarousel\" class=\"carousel slide\" data-ride=\"carousel\">\r\n");
      out.write("      <!-- Indicators -->\r\n");
      out.write("      <ol class=\"carousel-indicators\">\r\n");
      out.write("        <li data-target=\"#myCarousel\" data-slide-to=\"0\" class=\"active\"></li>\r\n");
      out.write("        <li data-target=\"#myCarousel\" data-slide-to=\"1\"></li>\r\n");
      out.write("        <li data-target=\"#myCarousel\" data-slide-to=\"2\"></li>\r\n");
      out.write("      </ol>\r\n");
      out.write("      <div class=\"carousel-inner\" role=\"listbox\">\r\n");
      out.write("        <div class=\"item active\">\r\n");
      out.write("          <img class=\"first-slide\" src=\"http://cfile5.uf.tistory.com/image/27750E4C5741FC630B817B\" alt=\"First slide\">\r\n");
      out.write("          <div class=\"container\">\r\n");
      out.write("            <div class=\"carousel-caption\">\r\n");
      out.write("              <!-- \r\n");
      out.write("              <h1>Example headline.</h1>\r\n");
      out.write("              <p>Note: If you're viewing this page via a <code>file://</code> URL, the \"next\" and \"previous\" Glyphicon buttons on the left and right might not load/display properly due to web browser security rules.</p>\r\n");
      out.write("              <p><a class=\"btn btn-lg btn-primary\" href=\"#\" role=\"button\">Sign up today</a></p>\r\n");
      out.write("              -->\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"item\">\r\n");
      out.write("          <img class=\"second-slide\" src=\"http://cfile26.uf.tistory.com/image/26138341560173C2072B7B\" alt=\"Second slide\">\r\n");
      out.write("          <div class=\"container\">\r\n");
      out.write("            <div class=\"carousel-caption\">\r\n");
      out.write("              <!-- \r\n");
      out.write("              <h1>Another example headline.</h1>\r\n");
      out.write("              <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>\r\n");
      out.write("              <p><a class=\"btn btn-lg btn-primary\" href=\"#\" role=\"button\">Learn more</a></p>\r\n");
      out.write("              -->\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"item\">\r\n");
      out.write("          <img class=\"third-slide\" src=\"http://www6.pcmag.com/media/images/506605-ios-10-generic.jpg?thumb=y&width=740&height=426\" alt=\"Third slide\">\r\n");
      out.write("          <div class=\"container\">\r\n");
      out.write("            <div class=\"carousel-caption\">\r\n");
      out.write("              <!-- \r\n");
      out.write("              <h1>One more for good measure.</h1>\r\n");
      out.write("              <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>\r\n");
      out.write("              <p><a class=\"btn btn-lg btn-primary\" href=\"#\" role=\"button\">Browse gallery</a></p>\r\n");
      out.write("              -->\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <a class=\"left carousel-control\" href=\"#myCarousel\" role=\"button\" data-slide=\"prev\">\r\n");
      out.write("        <span class=\"glyphicon glyphicon-chevron-left\" aria-hidden=\"true\"></span>\r\n");
      out.write("        <span class=\"sr-only\">Previous</span>\r\n");
      out.write("      </a>\r\n");
      out.write("      <a class=\"right carousel-control\" href=\"#myCarousel\" role=\"button\" data-slide=\"next\">\r\n");
      out.write("        <span class=\"glyphicon glyphicon-chevron-right\" aria-hidden=\"true\"></span>\r\n");
      out.write("        <span class=\"sr-only\">Next</span>\r\n");
      out.write("      </a>\r\n");
      out.write("    </div><!-- /.carousel -->\t\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("<!-- Marketing messaging and featurettes\r\n");
      out.write("    ================================================== -->\r\n");
      out.write("<!-- Wrap the rest of the page in another container to center all the content. -->\r\n");
      out.write("\r\n");
      out.write("<div class=\"container marketing\">\r\n");
      out.write("\r\n");
      out.write("\t<!-- Three columns of text below the carousel -->\r\n");
      out.write("\t<section>\r\n");
      out.write("\t<h2 style=\"margin-top: 0; margin-bottom: 20px; font-weight: 900;\">패키지 동영상 강의</h2>\r\n");
      out.write("\t<div class=\"row\">\r\n");
      out.write("\t\t<div class=\"col-md-3\" style=\"margin-bottom: 30px;\">\r\n");
      out.write("\t\t\t<img class=\"thumbnail\"\r\n");
      out.write("\t\t\t\tsrc=\"http://www.justexam.in/assets/blog/comments/default.jpg\"\r\n");
      out.write("\t\t\t\twidth=\"100%\" height=\"100%\" style=\"cursor:pointer;\">\r\n");
      out.write("\t\t\t<h3 style=\"text-align: center; cursor:pointer;\">Heading</h3>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- /.col-lg-4 -->\r\n");
      out.write("\t\t<div class=\"col-md-3\" style=\"margin-bottom: 30px;\">\r\n");
      out.write("\t\t\t<img class=\"thumbnail\"\r\n");
      out.write("\t\t\t\tsrc=\"http://www.justexam.in/assets/blog/comments/default.jpg\"\r\n");
      out.write("\t\t\t\twidth=\"100%\" height=\"100%\" style=\"cursor:pointer;\">\r\n");
      out.write("\t\t\t<h3 style=\"text-align: center; cursor:pointer;\">Heading</h3>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- /.col-lg-4 -->\r\n");
      out.write("\t\t<div class=\"col-md-3\" style=\"margin-bottom: 30px;\">\r\n");
      out.write("\t\t\t<img class=\"thumbnail\"\r\n");
      out.write("\t\t\t\tsrc=\"http://www.justexam.in/assets/blog/comments/default.jpg\"\r\n");
      out.write("\t\t\t\twidth=\"100%\" height=\"100%\" style=\"cursor:pointer;\">\r\n");
      out.write("\t\t\t<h3 style=\"text-align: center; cursor:pointer;\">Heading</h3>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- /.col-lg-4 -->\t\r\n");
      out.write("\t\t<div class=\"col-md-3\" style=\"margin-bottom: 30px;\">\r\n");
      out.write("\t\t\t<img class=\"thumbnail\"\r\n");
      out.write("\t\t\t\tsrc=\"http://www.justexam.in/assets/blog/comments/default.jpg\"\r\n");
      out.write("\t\t\t\twidth=\"100%\" height=\"100%\" style=\"cursor:pointer;\">\r\n");
      out.write("\t\t\t<h3 style=\"text-align: center; cursor:pointer;\">Heading</h3>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- /.col-lg-4 -->\t\r\n");
      out.write("\t</div><!-- /.row -->\r\n");
      out.write("\t</section>\r\n");
      out.write("\t\r\n");
      out.write("\t<section>\r\n");
      out.write("\t<h2 style=\"margin-bottom: 20px; font-weight: 900;\">이론 동영상 강의</h2>\r\n");
      out.write("\t<div class=\"row\">\r\n");
      out.write("\t\t");
for(int i=0; i<listLecCat.size(); ++i){
      out.write("\r\n");
      out.write("\t\t");
LectureCategory lectureCategory = (LectureCategory)listLecCat.get(i); 
      out.write("\r\n");
      out.write("\t\t");
if(lectureCategory.getSort()==1) continue; 
      out.write("\r\n");
      out.write("\t\t<div class=\"col-md-3\" style=\"margin-bottom: 30px;\">\r\n");
      out.write("\t\t\t<img class=\"thumbnail\"\r\n");
      out.write("\t\t\t\tsrc=\"/data/img/lec_cat/");
      out.print(lectureCategory.getSummaryimg());
      out.write("\"\r\n");
      out.write("\t\t\t\twidth=\"100%\" height=\"100%\" style=\"cursor:pointer;\">\r\n");
      out.write("\t\t\t<h3 style=\"text-align: center; cursor:pointer;\">");
      out.print(lectureCategory.getTitle());
      out.write("</h3>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t");
}
      out.write("\r\n");
      out.write("\t</div><!-- /.row -->\r\n");
      out.write("\t</section>\r\n");
      out.write("\t\r\n");
      out.write("\t<section>\r\n");
      out.write("\t<h2 style=\"margin-bottom: 20px; font-weight: 900;\">프로젝트 동영상 강의</h2>\r\n");
      out.write("\t<div class=\"row\">\r\n");
      out.write("\t\t");
for(int i=0; i<listLecCat.size(); ++i){
      out.write("\r\n");
      out.write("\t\t");
LectureCategory lectureCategory = (LectureCategory)listLecCat.get(i); 
      out.write("\r\n");
      out.write("\t\t");
if(lectureCategory.getSort()==0) continue; 
      out.write("\r\n");
      out.write("\t\t<div class=\"col-md-3\" style=\"margin-bottom: 30px;\">\r\n");
      out.write("\t\t\t<img class=\"thumbnail\"\r\n");
      out.write("\t\t\t\tsrc=\"/data/img/lec_cat/");
      out.print(lectureCategory.getSummaryimg());
      out.write("\"\r\n");
      out.write("\t\t\t\twidth=\"100%\" height=\"100%\" style=\"cursor:pointer;\">\r\n");
      out.write("\t\t\t<h3 style=\"text-align: center; cursor:pointer;\">");
      out.print(lectureCategory.getTitle());
      out.write("</h3>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t");
}
      out.write("\r\n");
      out.write("\t</div><!-- /.row -->\r\n");
      out.write("\t</section>\r\n");
      out.write("\t\r\n");
      out.write("\t<section>\r\n");
      out.write("\t<h2 style=\"margin-bottom: 20px; font-weight: 900;\">커뮤니티</h2>\r\n");
      out.write("\t<div class=\"row\">\r\n");
      out.write("\t\t<div class=\"col-md-6\" style=\"margin-bottom: 20px;\">\r\n");
      out.write("\t\t\t<div class=\"list-group\">\r\n");
      out.write("\t\t\t\t<a href=\"#\" class=\"list-group-item active\">공지사항</a>\r\n");
      out.write("\t\t\t\t<a href=\"#\" class=\"list-group-item\">Dapibus ac facilisis in</a>\r\n");
      out.write("\t\t\t\t<a href=\"#\" class=\"list-group-item\">Dapibus ac facilisis in</a>\r\n");
      out.write("\t\t\t\t<a href=\"#\" class=\"list-group-item\">Morbi leo risus</a> \r\n");
      out.write("\t\t\t\t<a href=\"#\" class=\"list-group-item\">Porta ac consectetur ac</a>\r\n");
      out.write("\t\t\t\t<a href=\"#\" class=\"list-group-item\">Vestibulum at eros</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"col-md-6\" style=\"margin-bottom: 20px;\">\r\n");
      out.write("\t\t\t<div class=\"list-group\">\r\n");
      out.write("\t\t\t\t<a href=\"#\" class=\"list-group-item active\">민쌤 엿보기</a>\r\n");
      out.write("\t\t\t\t<a href=\"#\" class=\"list-group-item\">Dapibus ac facilisis in</a>\r\n");
      out.write("\t\t\t\t<a href=\"#\" class=\"list-group-item\">Dapibus ac facilisis in</a>\r\n");
      out.write("\t\t\t\t<a href=\"#\" class=\"list-group-item\">Morbi leo risus</a> \r\n");
      out.write("\t\t\t\t<a href=\"#\" class=\"list-group-item\">Porta ac consectetur ac</a>\r\n");
      out.write("\t\t\t\t<a href=\"#\" class=\"list-group-item\">Vestibulum at eros</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"col-md-6\" style=\"margin-bottom: 20px;\">\r\n");
      out.write("\t\t\t<div class=\"list-group\">\r\n");
      out.write("\t\t\t\t<a href=\"#\" class=\"list-group-item active\">프로젝트 경연</a>\r\n");
      out.write("\t\t\t\t<a href=\"#\" class=\"list-group-item\">Dapibus ac facilisis in</a>\r\n");
      out.write("\t\t\t\t<a href=\"#\" class=\"list-group-item\">Dapibus ac facilisis in</a>\r\n");
      out.write("\t\t\t\t<a href=\"#\" class=\"list-group-item\">Morbi leo risus</a> \r\n");
      out.write("\t\t\t\t<a href=\"#\" class=\"list-group-item\">Porta ac consectetur ac</a>\r\n");
      out.write("\t\t\t\t<a href=\"#\" class=\"list-group-item\">Vestibulum at eros</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"col-md-6\" style=\"margin-bottom: 20px;\">\r\n");
      out.write("\t\t\t<div class=\"list-group\">\r\n");
      out.write("\t\t\t\t<a href=\"#\" class=\"list-group-item active\">IT 블로그</a>\r\n");
      out.write("\t\t\t\t<a href=\"#\" class=\"list-group-item\">Dapibus ac facilisis in</a>\r\n");
      out.write("\t\t\t\t<a href=\"#\" class=\"list-group-item\">Dapibus ac facilisis in</a>\r\n");
      out.write("\t\t\t\t<a href=\"#\" class=\"list-group-item\">Morbi leo risus</a> \r\n");
      out.write("\t\t\t\t<a href=\"#\" class=\"list-group-item\">Porta ac consectetur ac</a>\r\n");
      out.write("\t\t\t\t<a href=\"#\" class=\"list-group-item\">Vestibulum at eros</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\t<footer class=\"footer-basic-centered\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<p class=\"footer-company-motto\">The company motto.</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<p class=\"footer-links\">\r\n");
      out.write("\t\t\t\t<a href=\"#\">Home</a>\r\n");
      out.write("\t\t\t\t·\r\n");
      out.write("\t\t\t\t<a href=\"#\">Blog</a>\r\n");
      out.write("\t\t\t\t·\r\n");
      out.write("\t\t\t\t<a href=\"#\">Pricing</a>\r\n");
      out.write("\t\t\t\t·\r\n");
      out.write("\t\t\t\t<a href=\"#\">About</a>\r\n");
      out.write("\t\t\t\t·\r\n");
      out.write("\t\t\t\t<a href=\"#\">Faq</a>\r\n");
      out.write("\t\t\t\t·\r\n");
      out.write("\t\t\t\t<a href=\"#\">Contact</a>\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<p class=\"footer-company-name\">Team 4p &copy; 2016</p>\r\n");
      out.write("\r\n");
      out.write("\t\t</footer>\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://static.nid.naver.com/js/naverLogin_implicit-1.0.2.js\" charset=\"utf-8\"></script>\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"https://player.vimeo.com/api/player.js\"></script>\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js\"></script>\r\n");
      out.write("<!-- naver login api script -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://static.nid.naver.com/js/naverLogin_implicit-1.0.2.js\"></script>\r\n");
      out.write("<!-- custom script -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"/js/hyeon_script.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
