/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","cs",{title:"Instrukce pro p힂챠stupnost",contents:"Obsah n찼pov휎dy. Pro uzav힂en챠 tohoto dialogu stiskn휎te kl찼vesu ESC.",legend:[{name:"Obecn챕",items:[{name:"Panel n찼stroj킁 editoru",legend:"Stiskn휎te${toolbarFocus} k proch찼zen챠 panelu n찼stroj킁. P힂ejd휎te na dal큄챠 a p힂edchoz챠 skupiny pomoc챠 TAB a SHIFT+TAB. P힂echod na dal큄챠 a p힂edchoz챠 tla훾챠tko panelu n찼stroj킁 je pomoc챠 힋IPKA VPRAVO nebo 힋IPKA VLEVO. Stisknut챠m mezern챠ku nebo kl찼vesy ENTER tla훾챠tko aktivujete."},{name:"Dialogov챕 okno editoru",
legend:"Uvnit힂 dialogov챕ho okna stiskn휎te TAB pro p힂esunut챠 na dal큄챠 prvek okna, stiskn휎te SHIFT+TAB pro p힂esun na p힂edchoz챠 prvek okna, stiskn휎te ENTER pro odesl찼n챠 dialogu, stiskn휎te ESC pro jeho zru큄en챠. Pro dialogov찼 okna, kter찼 maj챠 mnoho karet stiskn휎te ALT+F10 pro zam휎힂en챠 seznamu karet, nebo TAB, pro posun podle po힂ad챠 karet.P힂i zam휎힂en챠 seznamu karet se m킁탑ete jimi posouvat pomoc챠 힋IPKY VPRAVO a VLEVO."},{name:"Kontextov챕 menu editoru",legend:"Stiskn휎te ${contextMenu} nebo kl찼vesu APPLICATION k otev힂en챠 kontextov챕ho menu. Pak se p힂esu흫te na dal큄챠 mo탑nost menu pomoc챠 TAB nebo 힋IPKY DOL큽. P힂esu흫te se na p힂edchoz챠 mo탑nost pomoc챠  SHIFT+TAB nebo 힋IPKY NAHORU. Stiskn휎te MEZERN횒K nebo ENTER pro zvolen챠 mo탑nosti menu. Podmenu sou훾asn챕 mo탑nosti otev힂ete pomoc챠 MEZERN횒KU nebo ENTER 훾i 힋IPKY DOLEVA. Kontextov챕 menu uzav힂ete stiskem ESC."},
{name:"R찼me훾ek seznamu editoru",legend:"Uvnit힂 r찼me훾ku seznamu se p힂esunete na dal큄챠 polo탑ku menu pomoc챠 TAB nebo 힋IPKA DOL큽. Na p힂edchoz챠 polo탑ku se p힂esunete SHIFT+TAB nebo 힋IPKA NAHORU. Stiskn휎te MEZERN횒K nebo ENTER pro zvolen챠 mo탑nosti seznamu. Stiskn휎te ESC pro uzav힂en챠 seznamu."},{name:"Li큄ta cesty prvku v editoru",legend:"Stiskn휎te ${elementsPathFocus} pro proch찼zen챠 li큄ty cesty prvku. Na dal큄챠 tla훾챠tko prvku se p힂esunete pomoc챠 TAB nebo 힋IPKA VPRAVO. Na p힂edchoz챠 tla훾챠tko se p힂esunete pomoc챠 SHIFT+TAB nebo 힋IPKA VLEVO. Stiskn휎te MEZERN횒K nebo ENTER pro vybr찼n챠 prvku v editoru."}]},
{name:"P힂챠kazy",items:[{name:" P힂챠kaz Zp휎t",legend:"Stiskn휎te ${undo}"},{name:" P힂챠kaz Znovu",legend:"Stiskn휎te ${redo}"},{name:" P힂챠kaz Tu훾n챕",legend:"Stiskn휎te ${bold}"},{name:" P힂챠kaz Kurz챠va",legend:"Stiskn휎te ${italic}"},{name:" P힂챠kaz Podtr탑en챠",legend:"Stiskn휎te ${underline}"},{name:" P힂챠kaz Odkaz",legend:"Stiskn휎te ${link}"},{name:" P힂챠kaz Skr첵t panel n찼stroj킁",legend:"Stiskn휎te ${toolbarCollapse}"},{name:"P힂챠kaz pro p힂챠stup k p힂edchoz챠mu prostoru zam휎힂en챠",legend:"Stiskn휎te ${accessPreviousSpace} pro p힂챠stup k nejbli탑큄챠mu nedosa탑iteln챕mu prostoru zam휎힂en챠 p힂ed st힂챠큄kou, nap힂챠klad: dva p힂ilehl챕 prvky HR. Pro dosa탑en챠 vzd찼len첵ch prostor킁 zam휎힂en챠 tuto kombinaci kl찼ves opakujte."},
{name:"P힂챠kaz pro p힂챠stup k dal큄챠mu prostoru zam휎힂en챠",legend:"Stiskn휎te ${accessNextSpace} pro p힂챠stup k nejbli탑큄챠mu nedosa탑iteln챕mu prostoru zam휎힂en챠 po st힂챠큄ce, nap힂챠klad: dva p힂ilehl챕 prvky HR. Pro dosa탑en챠 vzd찼len첵ch prostor킁 zam휎힂en챠 tuto kombinaci kl찼ves opakujte."},{name:" N찼pov휎da p힂챠stupnosti",legend:"Stiskn휎te ${a11yHelp}"}]}],backspace:"Backspace",tab:"Tabul찼tor",enter:"Enter",shift:"Shift",ctrl:"Ctrl",alt:"Alt",pause:"Pauza",capslock:"Caps lock",escape:"Escape",pageUp:"Str찼nka nahoru",
pageDown:"Str찼nka dol킁",end:"Konec",home:"Dom킁",leftArrow:"힋ipka vlevo",upArrow:"힋ipka nahoru",rightArrow:"힋ipka vpravo",downArrow:"힋ipka dol킁",insert:"Vlo탑it","delete":"Smazat",leftWindowKey:"Lev찼 kl찼vesa Windows",rightWindowKey:"Prav찼 kl찼vesa Windows",selectKey:"Vyberte kl찼vesu",numpad0:"Numerick찼 kl찼vesa 0",numpad1:"Numerick찼 kl찼vesa 1",numpad2:"Numerick찼 kl찼vesa 2",numpad3:"Numerick찼 kl찼vesa 3",numpad4:"Numerick찼 kl찼vesa 4",numpad5:"Numerick찼 kl찼vesa 5",numpad6:"Numerick찼 kl찼vesa 6",numpad7:"Numerick찼 kl찼vesa 7",
numpad8:"Numerick찼 kl찼vesa 8",numpad9:"Numerick찼 kl찼vesa 9",multiply:"Numerick찼 kl찼vesa n찼soben챠",add:"P힂idat",subtract:"Numerick찼 kl찼vesa ode훾챠t찼n챠",decimalPoint:"Desetinn찼 te훾ka",divide:"Numerick찼 kl찼vesa d휎len챠",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Num lock",scrollLock:"Scroll lock",semiColon:"St힂edn챠k",equalSign:"Rovn챠tko",comma:"훻찼rka",dash:"Poml훾ka",period:"Te훾ka",forwardSlash:"Lom챠tko",graveAccent:"P힂챠zvuk",openBracket:"Otev힂en찼 hranat찼 z찼vorka",
backSlash:"Obr찼cen챕 lom챠tko",closeBracket:"Uzav힂en찼 hranat찼 z찼vorka",singleQuote:"Jednoduch찼 uvozovka"});