/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","fi",{title:"Saavutettavuus ohjeet",contents:"Ohjeen sis채ll철t. Sulkeaksesi t채m채n dialogin paina ESC.",legend:[{name:"Yleinen",items:[{name:"Editorin ty철kalupalkki",legend:"Paina ${toolbarFocus} siirty채ksesi ty철kalupalkkiin. Siirry seuraavaan ja edelliseen ty철kalupalkin ryhm채채n TAB ja SHIFT+TAB n채pp채imill채. Siirry seuraavaan ja edelliseen ty철kalupainikkeeseen k채ytt채m채ll채 NUOLI OIKEALLE tai NUOLI VASEMMALLE n채pp채imill채. Paina V횆LILY횜NTI tai ENTER n채pp채int채 aktivoidaksesi ty철kalupainikkeen."},
{name:"Editorin dialogi",legend:"Inside a dialog, press TAB to navigate to the next dialog element, press SHIFT+TAB to move to the previous dialog element, press ENTER to submit the dialog, press ESC to cancel the dialog. When a dialog has multiple tabs, the tab list can be reached either with ALT+F10 or with TAB as part of the dialog tabbing order. With tab list focused, move to the next and previous tab with RIGHT and LEFT ARROW, respectively."},{name:"Editorin oheisvalikko",legend:"Paina ${contextMenu} tai SOVELLUSPAINIKETTA avataksesi oheisvalikon. Liiku seuraavaan valikon vaihtoehtoon TAB tai NUOLI ALAS n채pp채imill채. Siirry edelliseen vaihtoehtoon SHIFT+TAB tai NUOLI YL횜S n채pp채imill채. Paina V횆LILY횜NTI tai ENTER valitaksesi valikon kohdan. Avataksesi nykyisen kohdan alivalikon paina V횆LILY횜NTI tai ENTER tai NUOLI OIKEALLE painiketta. Siirty채ksesi takaisin valikon ylemm채lle tasolle paina ESC tai NUOLI vasemmalle. Oheisvalikko suljetaan ESC painikkeella."},
{name:"Editorin listalaatikko",legend:"Listalaatikon sis채ll채 siirry seuraavaan listan kohtaan TAB tai NUOLI ALAS painikkeilla. Siirry edelliseen listan kohtaan SHIFT+TAB tai NUOLI YL횜S painikkeilla. Paina V횆LILY횜NTI tai ENTER valitaksesi listan vaihtoehdon. Paina ESC sulkeaksesi listalaatikon."},{name:"Editorin elementtipolun palkki",legend:"Paina ${elementsPathFocus} siirty채ksesi elementtipolun palkkiin. Siirry seuraavaan elementtipainikkeeseen TAB tai NUOLI OIKEALLE painikkeilla. Siirry aiempaan painikkeeseen SHIFT+TAB tai NUOLI VASEMMALLE painikkeilla. Paina V횆LILY횜NTI tai ENTER valitaksesi elementin editorissa."}]},
{name:"Komennot",items:[{name:"Peruuta komento",legend:"Paina ${undo}"},{name:"Tee uudelleen komento",legend:"Paina ${redo}"},{name:"Lihavoi komento",legend:"Paina ${bold}"},{name:"Kursivoi komento",legend:"Paina ${italic}"},{name:"Alleviivaa komento",legend:"Paina ${underline}"},{name:"Linkki komento",legend:"Paina ${link}"},{name:"Pienenn채 ty철kalupalkki komento",legend:"Paina ${toolbarCollapse}"},{name:"Siirry aiempaan fokustilaan komento",legend:"Paina ${accessPreviousSpace} siiry채ksesi l채himp채채n kursorin edell채 olevaan saavuttamattomaan fokustilaan, esimerkiksi: kaksi vierekk채ist채 HR elementti채. Toista n채pp채inyhdistelm채채 p채채st채ksesi kauempana oleviin fokustiloihin."},
{name:"Siirry seuraavaan fokustilaan komento",legend:"Paina ${accessPreviousSpace} siiry채ksesi l채himp채채n kursorin j채lkeen olevaan saavuttamattomaan fokustilaan, esimerkiksi: kaksi vierekk채ist채 HR elementti채. Toista n채pp채inyhdistelm채채 p채채st채ksesi kauempana oleviin fokustiloihin."},{name:"Saavutettavuus ohjeet",legend:"Paina ${a11yHelp}"}]}],backspace:"Backspace",tab:"Tab",enter:"Enter",shift:"Shift",ctrl:"Ctrl",alt:"Alt",pause:"Pause",capslock:"Caps Lock",escape:"Escape",pageUp:"Page Up",pageDown:"Page Down",
end:"End",home:"Home",leftArrow:"Left Arrow",upArrow:"Up Arrow",rightArrow:"Right Arrow",downArrow:"Down Arrow",insert:"Insert","delete":"Delete",leftWindowKey:"Left Windows key",rightWindowKey:"Right Windows key",selectKey:"Select key",numpad0:"Numeron채pp채imist철 0",numpad1:"Numeron채pp채imist철 1",numpad2:"Numeron채pp채imist철 2",numpad3:"Numeron채pp채imist철 3",numpad4:"Numeron채pp채imist철 4",numpad5:"Numeron채pp채imist철 5",numpad6:"Numeron채pp채imist철 6",numpad7:"Numeron채pp채imist철 7",numpad8:"Numeron채pp채imist철 8",
numpad9:"Numeron채pp채imist철 9",multiply:"Multiply",add:"Add",subtract:"Subtract",decimalPoint:"Decimal Point",divide:"Divide",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Num Lock",scrollLock:"Scroll Lock",semiColon:"Puolipiste",equalSign:"Equal Sign",comma:"Pilkku",dash:"Dash",period:"Piste",forwardSlash:"Forward Slash",graveAccent:"Grave Accent",openBracket:"Open Bracket",backSlash:"Backslash",closeBracket:"Close Bracket",singleQuote:"Single Quote"});