/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","he",{title:"�붨뺈ⓚ먚뺈� �졫믕쇬⒦뺈�",contents:"�붨뺈ⓚ먚뺈� �졫믕쇬⒦뺈�. �쑿§믕쇬ⓚ� �쑿쀗� �먚§㎓쇬쇬� (ESC).",legend:[{name:"�쎰쑿쑿�",items:[{name:"遼淚�믕� �붨쎰쑿쇬�",legend:"�쑿쀗� 鬧�� ${toolbarFocus} �쎰볊� �쑿졫뺈뺈� �쑿§ⓚ믕� �붨쎰쑿쇬�. 鬧�뫷뺈� �쑿쎰ㅧぷ뺈� �붨뫷� 鬧�� �왰㎓� �붨샳먚� (TAB) �먚� �쀗� 漏�왰먚쑿�. 鬧�뫷뺈� �쑿쎰ㅧぷ뺈� �붨㎓뺈볊� 鬧�� �왰㎓� �붨⒦쇬ㅧ� (SHIFT) + �샳먚� (TAB) �먚� �쀗� �쇬왰졫�. �쑿쀗� 淚�뺈뺈� �먚� �먚졫샳� (ENTER) �쎰볊� �쑿붨ㅧ↙쇬� �먚� �붨쎰ㅧぷ뺈� �붨졫뫷쀗�."},{name:"�볊쇬먚쑿뺈믕쇬� (�쀗쑿뺈졫뺈� 瘻漏�먚뺈�)",legend:"Inside a dialog, press TAB to navigate to the next dialog element, press SHIFT+TAB to move to the previous dialog element, press ENTER to submit the dialog, press ESC to cancel the dialog. When a dialog has multiple tabs, the tab list can be reached either with ALT+F10 or with TAB as part of the dialog tabbing order. With tab list focused, move to the next and previous tab with RIGHT and LEFT ARROW, respectively."},
{name:"瘻壘淚�쇬� �붨붨㎓⒦� (Context Menu)",legend:"�쑿쀗� ${contextMenu} �먚� APPLICATION KEY�쎰볊� �쑿ㅧぷ뺈� �먚� 瘻壘淚�쇬� �붨붨㎓⒦�. 鬧�뫷뺈� �쑿먚ㅧ⒦ⓚ뺈� �붨뫷먚� 鬧�� �샳먚� (TAB) �먚� �쀗� �쑿왰샳�. 鬧�뫷뺈� �쑿먚ㅧ⒦ⓚ뺈� �붨㎓뺈볊왰� 鬧�� 漏�쇬ㅧ� (SHIFT) + �샳먚� (TAB) �먚� �쀗� �쑿왰↙쑿�. �쑿쀗� 淚�뺈뺈� �먚� �먚졫샳� (ENTER) �쎰볊� �쑿뫷쀗뺈� �먚� �붨먚ㅧ⒦ⓚ뺈�. 壘瘻�� �먚� 瘻瘻 �붨ぷㅧⓚ쇬� (Sub-menu) 漏�� �붨먚ㅧ⒦ⓚ뺈� �붨졫뺈쎰쀗쇬� 鬧�� 淚�뺈뺈� �먚� �먚졫샳� (ENTER) �먚� �쀗� 漏�왰먚쑿�. �쀗뽛뺈� �쑿ぷㅧⓚ쇬� �붨먚� 鬧�� �먚§㎓쇬쇬� (ESC) �먚� �쀗� 漏�왰먚쑿�. 遼�믕뺈� �먚� 瘻壘淚�쇬� �붨붨㎓⒦� 鬧�� �먚§㎓쇬쇬� (ESC)."},{name:"瘻壘淚�쇬샳쇬� 屢壘�쇬� (List boxes)",legend:"Inside a list-box, move to next list item with TAB OR DOWN ARROW. Move to previous list item with SHIFT+TAB or UP ARROW. Press SPACE or ENTER to select the list option. Press ESC to close the list-box."},
{name:"鬧婁 �먚쑿왰졫샳쇬� (Elements Path)",legend:"�쑿쀗� ${elementsPathFocus} �쎰볊� �쑿졫뺈뺈� �쑿↙� �붨먚쑿왰졫샳쇬�. 鬧�뫷뺈� �쑿ㅧⓚ쇬� �붨뫷� 鬧�� �샳먚� (TAB) �먚� �쀗� �쇬왰졫�. 鬧�뫷뺈� �쑿ㅧⓚ쇬� �붨㎓뺈볊� 鬧�� 漏�쇬ㅧ� (SHIFT) + �샳먚� (TAB) �먚� �쀗� 漏�왰먚쑿�. �쑿쀗� 淚�뺈뺈� �먚� �먚졫샳� (ENTER) �쎰볊� �쑿뫷쀗뺈� �먚� �붨먚쑿왰졫� �뫷↙뺈ⓚ�."}]},{name:"壘樓�뺈볊뺈�",items:[{name:" �뫷쇬샳뺈� 屢鬧�� �먚쀗ⓚ뺈�",legend:"�쑿쀗� ${undo}"},{name:" �쀗뽛ⓚ� 鬧�� 屢鬧�� �먚쀗ⓚ뺈�",legend:"�쑿쀗� ${redo}"},{name:" �붨볊믕⒦�",legend:"�쑿쀗� ${bold}"},{name:" �붨샳쇬쇬�",legend:"�쑿쀗� ${italic}"},{name:" �붨뺈§ㅧ� 樓�� 瘻�쀗ぷ뺈�",legend:"�쑿쀗� ${underline}"},{name:" �붨뺈§ㅧ� �쑿쇬졫�",
legend:"�쑿쀗� ${link}"},{name:" �쎰쇬뺈뺈� 遼淚�믕� �붨쎰쑿쇬�",legend:"�쑿쀗� ${toolbarCollapse}"},{name:"�믕쇬⒦� �쑿왰쇬㎓뺈� �붨왰쇬㎓뺈� �붨㎓뺈볊�",legend:"�쑿쀗� ${accessPreviousSpace} �쎰볊� �쑿믕⒦� �쑿왰쇬㎓뺈� �붨왰쇬㎓뺈� �붨쑿�-�졫믕쇬� �붨㎓ⓚ뺈� �쑿ㅧ졫� �붨§왰�, �쑿왰⒦� �뫷쇬� 漏�졫� �먚쑿왰졫샳쇬� 遼�왰뺈쎰쇬� �왰§뺈� HR. �쀗뽛뺈� 鬧�� 屢�쇬ⓚ뺈� �왰㎓⒦쇬� �뽛� �쎰볊� �쑿붨믕쇬� �쑿왰㎓뺈왰뺈� �왰쇬㎓뺈� 淚�쀗뺈㎓쇬� �쇬뺈ぷ�."},{name:"�믕쇬⒦� �쑿왰쇬㎓뺈� �붨왰쇬㎓뺈� �붨뫷�",legend:"�쑿쀗� ${accessNextSpace} �쎰볊� �쑿믕⒦� �쑿왰쇬㎓뺈� �붨왰쇬㎓뺈� �붨쑿�-�졫믕쇬� �붨㎓ⓚ뺈� �먚쀗ⓚ� �붨§왰�, �쑿왰⒦� �뫷쇬� 漏�졫� �먚쑿왰졫샳쇬� 遼�왰뺈쎰쇬� �왰§뺈� HR. �쀗뽛뺈� 鬧�� 屢�쇬ⓚ뺈� �왰㎓⒦쇬� �뽛� �쎰볊� �쑿붨믕쇬� �쑿왰㎓뺈왰뺈� �왰쇬㎓뺈� 淚�쀗뺈㎓쇬� �쇬뺈ぷ�."},
{name:" �붨뺈ⓚ먚뺈� �졫믕쇬⒦뺈�",legend:"�쑿쀗� ${a11yHelp}"}]}],backspace:"Backspace",tab:"Tab",enter:"Enter",shift:"Shift",ctrl:"Ctrl",alt:"Alt",pause:"Pause",capslock:"Caps Lock",escape:"Escape",pageUp:"Page Up",pageDown:"Page Down",end:"End",home:"Home",leftArrow:"�쀗� 漏�왰먚쑿�",upArrow:"�쀗� �쑿왰↙쑿�",rightArrow:"�쀗� �쇬왰쇬졫�",downArrow:"�쀗� �쑿왰샳�",insert:"�붨쎰졫�","delete":"�왰쀗�",leftWindowKey:"Left Windows key",rightWindowKey:"Right Windows key",selectKey:"�뫷쀗� �왰㎓�",numpad0:"Numpad 0",numpad1:"Numpad 1",numpad2:"Numpad 2",
numpad3:"Numpad 3",numpad4:"Numpad 4",numpad5:"Numpad 5",numpad6:"Numpad 6",numpad7:"Numpad 7",numpad8:"Numpad 8",numpad9:"Numpad 9",multiply:"Multiply",add:"�붨뺈§�",subtract:"Subtract",decimalPoint:"Decimal Point",divide:"Divide",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Num Lock",scrollLock:"Scroll Lock",semiColon:"Semicolon",equalSign:"Equal Sign",comma:"Comma",dash:"Dash",period:"Period",forwardSlash:"遼�쑿먚�",graveAccent:"Grave Accent",
openBracket:"Open Bracket",backSlash:"遼�쑿먚� �붨ㅧ뺈�",closeBracket:"Close Bracket",singleQuote:"屢�쇬샳뺈� �쇬쀗쇬�"});