/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","ku",{title:"�뺎롕녪끮㏁� �꾗뺉ⓞ뺉극��뺉넥へ�碼磨�댶댶�",contents:"毛�롖⒨뉃㎔ほ뺎� �뚕㎔근끱뺉ほ�. 沕�꾗뚖� ESC 磨�� 膜碼漠卍魔�녬� 痲�뺊� 膜�뚕Ω꾗녫���.",legend:[{name:"彌娩魔��",items:[{name:"魔�댶댷뒈Ω끮극㎔꾼� 膜�뺉넥べ꺲㎔글뚖꺵뺉�",legend:"沕�꾗뚖� ${toolbarFocus} 磨�� �뺉㎔ⓞ뺉글� 魔�댶댷뒈Ω끮극㎔�. 磨�� 彌�댵㎔넥べ녬뺊댸뺎� 毛�롔다댶� 膜碼�뉃㎔べ댶댸� 彌邈�댶댶앱� 魔�댶댷뒈Ω끮극㎔꾼� 膜碼彌邈魔�녬� 沕�꾗뚖꾗� TAB �꾗뺋��뺋듈�� SHIFT+TAB. 磨�� 彌�댵㎔넥べ녬뺊댸뺎� 毛�롔다댶� 膜碼�뉃㎔べ댶댸� 膜�댶댷��끱뺎� 魔�댶댷뒈Ω끮극㎔꾼� �꾗뺋뺎롗� 沕�꾗뚖꾗� 魔�뚕글� 膜�뺉넥ほ� �뺉㎔넥� �뚕Ω� 沕�꾗뚖꾗� 魔�뚕글� 膜�뺉넥ほ� �녬뺊�. 沕�꾗뚗⒪� 沕�꾗뚖꾗� SPACE �뚕Ω� ENTER 磨�� �녩Ω꾓㏀⒩⒧극��녬� 膜�댶댷��끱뺎� 魔�댶댷뒈Ω끮극㎔�."},{name:"膜�뚕Ω꾗녫��� 膜�뺉넥べ꺲㎔글뚖꺵뺉�",
legend:"Inside a dialog, press TAB to navigate to the next dialog element, press SHIFT+TAB to move to the previous dialog element, press ENTER to submit the dialog, press ESC to cancel the dialog. When a dialog has multiple tabs, the tab list can be reached either with ALT+F10 or with TAB as part of the dialog tabbing order. With tab list focused, move to the next and previous tab with RIGHT and LEFT ARROW, respectively."},{name:"毛�롖뺉넥ほ� 卍�뺉근녪댶댵넴뺉�",legend:"沕�꾗뚖� ${contextMenu} �뚕Ω� 膜�댷��끱뺎� �꾗뚕넥べ뉍��(Menu) 磨�� 沕邈膜�녬뺊댸뺎� �꾗뚕넥ほ뺎� 膜�뺊�. 磨�� �녪댶댶녬� �뉆뺋뒈ⓝ샶㎔극��뺎뚘뺋⒪� 魔邈 �꾔뉍�� �꾗뚕넥べ뉍�� 沕�꾗뚗⒪� 沕�꾗뚖꾗� TAB �뚕Ω� 沕�꾗뚖꾗� 魔�뚕글� �뺊댶� �꾗뺉��댵㎔글뺊댶뉍�� 磨�� �녪댶댶� 磨�� �뉆뺋뒈ⓝ샶㎔극��뺎� 毛�롔다댶� 沕�꾗뚗⒪� 沕�꾗뚖꾗� SHIFT+TAB �뚕Ω� 沕�꾗뚖꾗� 魔�뚕글� �뺊댶� �꾔뉍�� 卍�뺉글뺊댸�. 膜碼彌邈魔�녬� 沕�꾗뚖꾗� SPACE �뚕Ω� ENTER 磨�� �뉆뺋뒈ⓝ샶㎔극��녬� �뉆뺋뒈ⓝ샶㎔극��뺎� �꾗뚕넥べ뉍��. 磨�� 沕邈膜�녬뺊댸뺎� �꾔귎� �샻롔� �꾗뚕넥べ뉍�� �꾗뺊뉆뺋뒈ⓝ샶㎔극��뺎� �꾗뚕넥ほ� 沕�꾗뚗⒪� 沕�꾗뚖꾗� SPACE �뚕Ω� ENTER �뚕Ω� 沕�꾗뚖꾗� 魔�뚕글� 膜�뺉넥ほ� �뺉㎔넥�. 磨�� 彌�뺋뺉Ω녬뺊댶� 磨�� 卍�뺉글뺊댸뺎� �꾗뚕넥べ뉍�� 沕�꾗뚗⒪� 沕�꾗뚖꾗� ESC �뚕Ω� 沕�꾗뚖꾗� 魔�뚕글� 膜�뺉넥ほ� �녬뺊�. 磨�� 膜碼漠卍魔�녬� �꾗뚕넥ほ� 沕�꾗뚖꺵� 沕�꾗뚖꾗� ESC 磨沕��."},
{name:"�꾗뚕넥ほ� 卍�녪댶댶귎� 卍�뺉근녪댶댵넴뺉�",legend:"�꾗뺊녩Ω� 卍�녪댶귎� �꾗뚕넥�, �녬녪� 磨�� �뉆뺋뒝녩ⓝ샶㎔극��뺎� �꾗뚕넥ほ롖⒪� 魔邈 沕�꾗뚗⒪� 沕�꾗뚖꾗� TAB �뚕Ω� 沕�꾗뚖꾗� 魔�뚕글� �뺊댶� �꾗뺉��댵㎔�. �녪댶댶� 磨�� �뉆뺋뒈ⓝ샶㎔극��뺎� �꾗뚕넥ほ� 毛�롔다댶� 沕�꾗뚗⒪� 沕�꾗뚖꾗� SHIFT+TAB �뚕Ω� 沕�꾗뚖꾗� 魔�뚕글� �뺊댶� �꾗뺉넴뺉글뺊댶뉍��. 沕�꾗뚗⒪� 沕�꾗뚖꾗� SPACE �뚕Ω� ENTER 磨�� 膜�뚕㎔글뚗⒧극��녬� �뚖뉆뺋뒈ⓝ샶㎔극��뺎� �꾗뚕넥�. 沕�꾗뚗⒪� 沕�꾗뚖꾗� ESC 磨�� 膜碼漠卍魔�녬� 卍�녪댶귎� �꾗뚕넥�."},{name:"魔�댶댷뒈Ω끮극㎔꾼� 魔�댵���",legend:"沕�꾗뚖� ${elementsPathFocus} 磨�� �뺉㎔ⓞ뺉글� 魔�댶댷뒈Ω끮극㎔꾼� 魔�댵��끱뺋⒧Ω�. �녪댶댶� 磨�� 膜�댷��끱뺎� 魔�댵��끱롖⒪� 魔邈 沕�꾗뚗⒪� 沕�꾗뚖꾗� TAB �뚕Ω� 沕�꾗뚖꾗� 魔�뚕글� 膜�뺉넥ほ� �뺉㎔넥�. �녪댶댶� 磨�� 膜�댷��끱뺎� 魔�댵��끱� 毛�롔다댶� 沕�꾗뚖꾗� SHIFT+TAB �뚕Ω� 沕�꾗뚗⒪� 沕�꾗뚖꾗� 魔�뚕글� 膜�뺉넥ほ� �녬뺊�. 膜碼彌邈魔�녬� 沕�꾗뚖꾗� SPACE �뚕Ω� ENTER 磨�� 膜�뚕㎔글뚗⒧극��녬� 魔�댵��끱뺋⒨뉍�� �꾗뺉넴뺉근녪댶댵넨�."}]},
{name:"�곚뺉근끮Ω녬뺋⒧Ω�",items:[{name:"毛�댶댷녫⒧극��녬뺊댸뺎� �곚뺉근끮Ω�",legend:"沕�꾗뚖� ${undo}"},{name:"�뉆뺋뒤��뺋뺉Ω녬뺊댸뺎� �곚뺉근끮Ω�",legend:"沕�꾗뚖� ${redo}"},{name:"�곚뺉근끮Ω녬� 膜�뺊귎� �귎뺋뒨뺊�",legend:"沕�꾗뚖� ${bold}"},{name:"�곚뺉근끮Ω녬� 膜�뺊귎� �꾓㎔�",legend:"沕�꾗뚖� ${italic}"},{name:"�곚뺉근끮Ω녬� �샻롔근뉆롖�",legend:"沕�꾗뚖� ${underline}"},{name:"�곚뺉근끮Ω녬� 磨�뉍�뚕넥ほ뺉�",legend:"沕�꾗뚖� ${link}"},{name:"娩碼邈膜�뺊녬뺊댸뺎� 魔�댶댷뒈Ω끮극㎔�",legend:"沕�꾗뚖� ${toolbarCollapse}"},{name:"�녪댶댶녬뺊녩Ω� 卍�뺉근녩ж�碼�녬� 毛�롔다댸� �곚뺉근끮Ω녬� 磨�녩닢㏁뚘�",legend:"沕�꾗뚗� ${accessPreviousSpace} to access the closest unreachable focus space before the caret, for example: two adjacent HR elements. Repeat the key combination to reach distant focus spaces."},
{name:"�녪댶댶녬뺊녩Ω� 卍�뺉근녩ж�碼�녬� 膜碼�뉃㎔べ댶댸� �곚뺉근끮Ω녬� 磨�녩닢㏁뚘�",legend:"沕�꾗뚗� ${accessNextSpace} to access the closest unreachable focus space after the caret, for example: two adjacent HR elements. Repeat the key combination to reach distant focus spaces."},{name:"膜�뺉넥べ앱롖��뺎뚕닢べ녬� �뚕㎔근끱뺉ほ�",legend:"沕�꾗뚖� ${a11yHelp}"}]}],backspace:"Backspace",tab:"Tab",enter:"Enter",shift:"Shift",ctrl:"Ctrl",alt:"Alt",pause:"Pause",capslock:"Caps Lock",escape:"Escape",pageUp:"Page Up",pageDown:"Page Down",end:"End",home:"Home",leftArrow:"Left Arrow",
upArrow:"Up Arrow",rightArrow:"Right Arrow",downArrow:"Down Arrow",insert:"Insert","delete":"Delete",leftWindowKey:"毛�뺊녩й뺉글뺎� �녬뺊�",rightWindowKey:"毛�뺊녩й뺉글뺎� �뺉㎔넥�",selectKey:"Select",numpad0:"Numpad 0",numpad1:"1",numpad2:"2",numpad3:"3",numpad4:"4",numpad5:"5",numpad6:"6",numpad7:"7",numpad8:"8",numpad9:"9",multiply:"*",add:"+",subtract:"-",decimalPoint:".",divide:"/",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Num Lock",scrollLock:"Scroll Lock",
semiColon:";",equalSign:"\x3d",comma:",",dash:"-",period:".",forwardSlash:"/",graveAccent:"`",openBracket:"[",backSlash:"\\\\",closeBracket:"}",singleQuote:"'"});