/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","mk",{title:"�샫싼곎귂��꺪붇녡먁� 鈞逵 極�龜�곎궿겆왈싻앗곎�",contents:"鬼棘畇�菌龜戟逵 戟逵 畇筠剋棘�� 鈞逵 極棘劇棘��. �쀐� 畇逵 均棘 鈞逵�궿꽥앗�龜�궿� 棘勻棘�� 畇龜�샫겆뿅압� 極�龜�궿먈곍싻둘궿� ESC.",legend:[{name:"�왧왐댮궿�",items:[{name:"�쑷둔싻� 鈞逵 �꺫�筠畇�꺪꽥겉눺앗�",legend:"Press ${toolbarFocus} to navigate to the toolbar. Move to the next and previous toolbar group with TAB and SHIFT+TAB. Move to the next and previous toolbar button with RIGHT ARROW or LEFT ARROW. Press SPACE or ENTER to activate the toolbar button."},{name:"�붠먈샫겆뿅앗� 鈞逵 筠畇龜�궿앗�棘��",
legend:"Inside a dialog, press TAB to navigate to the next dialog element, press SHIFT+TAB to move to the previous dialog element, press ENTER to submit the dialog, press ESC to cancel the dialog. When a dialog has multiple tabs, the tab list can be reached either with ALT+F10 or with TAB as part of the dialog tabbing order. With tab list focused, move to the next and previous tab with RIGHT and LEFT ARROW, respectively."},{name:"�싍압싼궿둔붇곎�-劇筠戟龜 戟逵 �꺫�筠畇�꺪꽥겉눺앗�",legend:"Press ${contextMenu} or APPLICATION KEY to open context-menu. Then move to next menu option with TAB or DOWN ARROW. Move to previous option with SHIFT+TAB or UP ARROW. Press SPACE or ENTER to select the menu option. Open sub-menu of current option with SPACE or ENTER or RIGHT ARROW. Go back to parent menu item with ESC or LEFT ARROW. Close context menu with ESC."},
{name:"Editor List Box",legend:"Inside a list-box, move to next list item with TAB OR DOWN ARROW. Move to previous list item with SHIFT+TAB or UP ARROW. Press SPACE or ENTER to select the list option. Press ESC to close the list-box."},{name:"Editor Element Path Bar",legend:"Press ${elementsPathFocus} to navigate to the elements path bar. Move to next element button with TAB or RIGHT ARROW. Move to previous button with SHIFT+TAB or LEFT ARROW. Press SPACE or ENTER to select the element in editor."}]},
{name:"�앆겉�筠畇閨龜",items:[{name:" Undo command",legend:"Press ${undo}"},{name:" Redo command",legend:"Press ${redo}"},{name:" Bold command",legend:"Press ${bold}"},{name:" Italic command",legend:"Press ${italic}"},{name:" Underline command",legend:"Press ${underline}"},{name:" Link command",legend:"Press ${link}"},{name:" Toolbar Collapse command",legend:"Press ${toolbarCollapse}"},{name:" Access previous focus space command",legend:"Press ${accessPreviousSpace} to access the closest unreachable focus space before the caret, for example: two adjacent HR elements. Repeat the key combination to reach distant focus spaces."},
{name:" Access next focus space command",legend:"Press ${accessNextSpace} to access the closest unreachable focus space after the caret, for example: two adjacent HR elements. Repeat the key combination to reach distant focus spaces."},{name:" Accessibility Help",legend:"Press ${a11yHelp}"}]}],backspace:"Backspace",tab:"Tab",enter:"Enter",shift:"Shift",ctrl:"Ctrl",alt:"Alt",pause:"�읩겉꺪론�",capslock:"Caps Lock",escape:"Escape",pageUp:"Page Up",pageDown:"Page Up",end:"End",home:"Home",leftArrow:"鬼�귂�筠剋克逵 剋筠勻棘",
upArrow:"鬼�귂�筠剋克逵 均棘�筠",rightArrow:"鬼�귂�筠剋克逵 畇筠�곍싻�",downArrow:"鬼�귂�筠剋克逵 畇棘剋筠",insert:"Insert","delete":"Delete",leftWindowKey:"�쎩둔꽥� Windows 克棘極�눺�",rightWindowKey:"�붠둘곍싻� Windows 克棘極�눺�",selectKey:"Select 克棘極�눺�",numpad0:"�앇꺪�. �궿겉곎�. 0",numpad1:"�앇꺪�. �궿겉곎�. 1",numpad2:"�앇꺪�. �궿겉곎�. 2",numpad3:"�앇꺪�. �궿겉곎�. 3",numpad4:"�앇꺪�. �궿겉곎�. 4",numpad5:"�앇꺪�. �궿겉곎�. 5",numpad6:"�앇꺪�. �궿겉곎�. 6",numpad7:"�앇꺪�. �궿겉곎�. 7",numpad8:"�앇꺪�. �궿겉곎�. 8",numpad9:"�앇꺪�. �궿겉곎�. 9",multiply:"Multiply",add:"Add",subtract:"Subtract",decimalPoint:"Decimal Point",
divide:"Divide",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Num Lock",scrollLock:"Scroll Lock",semiColon:"Semicolon",equalSign:"Equal Sign",comma:"Comma",dash:"Dash",period:"Period",forwardSlash:"Forward Slash",graveAccent:"Grave Accent",openBracket:"Open Bracket",backSlash:"Backslash",closeBracket:"Close Bracket",singleQuote:"Single Quote"});