/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","nb",{title:"Instruksjoner for tilgjengelighet",contents:"Innhold for hjelp. Trykk ESC for 책 lukke denne dialogen.",legend:[{name:"Generelt",items:[{name:"Verkt첩ylinje for editor",legend:"Trykk ${toolbarFocus} for 책 navigere til verkt첩ylinjen. Flytt til neste og forrige verkt첩ylinjegruppe med TAB og SHIFT+TAB. Flytt til neste og forrige verkt첩ylinjeknapp med H횠YRE PILTAST og VENSTRE PILTAST. Trykk MELLOMROM eller ENTER for 책 aktivere verkt첩ylinjeknappen."},{name:"Dialog for editor",
legend:"Mens du er i en dialog, trykk TAB for 책 navigere til neste dialogelement, trykk SHIFT+TAB for 책 flytte til forrige dialogelement, trykk ENTER for 책 akseptere dialogen, trykk ESC for 책 avbryte dialogen. N책r en dialog har flere faner, kan fanelisten n책s med enten ALT+F10 eller med TAB. N책r fanelisten er fokusert, g책r man til neste og forrige fane med henholdsvis H횠YRE og VENSTRE PILTAST."},{name:"Kontekstmeny for editor",legend:"Trykk ${contextMenu} eller MENYKNAPP for 책 책pne kontekstmeny. G책 til neste alternativ i menyen med TAB eller PILTAST NED. G책 til forrige alternativ med SHIFT+TAB eller PILTAST OPP. Trykk MELLOMROM eller ENTER for 책 velge menyalternativet. 횇pne undermenyen p책 valgt alternativ med MELLOMROM eller ENTER eller H횠YRE PILTAST. G책 tilbake til overordnet menyelement med ESC eller VENSTRE PILTAST. Lukk kontekstmenyen med ESC."},
{name:"Listeboks for editor",legend:"I en listeboks, g책 til neste alternativ i listen med TAB eller PILTAST NED. G책 til forrige alternativ i listen med SHIFT+TAB eller PILTAST OPP. Trykk MELLOMROM eller ENTER for 책 velge alternativet i listen. Trykk ESC for 책 lukke listeboksen."},{name:"Verkt첩ylinje for elementsti",legend:"Trykk ${elementsPathFocus} for 책 navigere til verkt첩ylinjen som viser elementsti. G책 til neste elementknapp med TAB eller H횠YRE PILTAST. G책 til forrige elementknapp med SHIFT+TAB eller VENSTRE PILTAST. Trykk MELLOMROM eller ENTER for 책 velge elementet i editoren."}]},
{name:"Hurtigtaster",items:[{name:"Angre",legend:"Trykk ${undo}"},{name:"Gj첩r om",legend:"Trykk ${redo}"},{name:"Fet tekst",legend:"Trykk ${bold}"},{name:"Kursiv tekst",legend:"Trykk ${italic}"},{name:"Understreking",legend:"Trykk ${underline}"},{name:"Lenke",legend:"Trykk ${link}"},{name:"Skjul verkt첩ylinje",legend:"Trykk ${toolbarCollapse}"},{name:"G책 til forrige fokusomr책de",legend:"Trykk ${accessPreviousSpace} for 책 komme til n챈rmeste fokusomr책de f첩r skrivemark첩ren som ikke kan n책s p책 vanlig m책te, for eksempel to tilst첩tende HR-elementer. Gjenta tastekombinasjonen for 책 komme til fokusomr책der lenger unna i dokumentet."},
{name:"G책 til neste fokusomr책de",legend:"Trykk ${accessNextSpace} for 책 komme til n챈rmeste fokusomr책de etter skrivemark첩ren som ikke kan n책s p책 vanlig m책te, for eksempel to tilst첩tende HR-elementer. Gjenta tastekombinasjonen for 책 komme til fokusomr책der lenger unna i dokumentet."},{name:"Hjelp for tilgjengelighet",legend:"Trykk ${a11yHelp}"}]}],backspace:"Backspace",tab:"Tabulator",enter:"Enter",shift:"Shift",ctrl:"Ctrl",alt:"Alt",pause:"Pause",capslock:"Caps Lock",escape:"Escape",pageUp:"Page Up",
pageDown:"Page Down",end:"End",home:"Home",leftArrow:"Venstre piltast",upArrow:"Opp-piltast",rightArrow:"H첩yre piltast",downArrow:"Ned-piltast",insert:"Insert","delete":"Delete",leftWindowKey:"Venstre Windows-tast",rightWindowKey:"H첩yre Windows-tast",selectKey:"Velg n첩kkel",numpad0:"Numerisk tastatur 0",numpad1:"Numerisk tastatur 1",numpad2:"Numerisk tastatur 2",numpad3:"Numerisk tastatur 3",numpad4:"Numerisk tastatur 4",numpad5:"Numerisk tastatur 5",numpad6:"Numerisk tastatur 6",numpad7:"Numerisk tastatur 7",
numpad8:"Numerisk tastatur 8",numpad9:"Numerisk tastatur 9",multiply:"Multipliser",add:"Legg til",subtract:"Trekk fra",decimalPoint:"Desimaltegn",divide:"Divider",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Num Lock",scrollLock:"Scroll Lock",semiColon:"Semikolon",equalSign:"Likhetstegn",comma:"Komma",dash:"Bindestrek",period:"Punktum",forwardSlash:"Forover skr책strek",graveAccent:"Grav aksent",openBracket:"횇pne parentes",backSlash:"Bakover skr책strek",
closeBracket:"Lukk parentes",singleQuote:"Enkelt sitattegn"});