/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","ro",{title:"Instruc�쌻uni de accesibilitate",contents:"Cuprins. Pentru a 챤nchide acest dialog, ap훱sa�쌻 tasta ESC.",legend:[{name:"General",items:[{name:"Editeaz훱 bara instrumente.",legend:"Apas훱 ${toolbarFocus} pentru a naviga prin bara de instrumente. Pentru a te mi�셛a prin grupurile de instrumente folose�셳e tastele TAB �셢 SHIFT+TAB. Pentru a te mi�셛a intre diverse instrumente folose�셳e tastele S훯GEAT훯 DREAPTA sau S훯GEAT훯 ST횂NGA. Apas훱 butonul SPA�숳U sau ENTER pentru activarea instrumentului."},
{name:"Dialog editor",legend:"Inside a dialog, press TAB to navigate to the next dialog element, press SHIFT+TAB to move to the previous dialog element, press ENTER to submit the dialog, press ESC to cancel the dialog. When a dialog has multiple tabs, the tab list can be reached either with ALT+F10 or with TAB as part of the dialog tabbing order. With tab list focused, move to the next and previous tab with RIGHT and LEFT ARROW, respectively."},{name:"Editor meniu contextual",legend:"Apas훱 ${contextMenu} sau TASTA MENIU pentru a deschide meniul contextual. Treci la urm훱toarea op�쌻une din meniu cu TAB sau S훯GEAT훯 JOS. Treci la op�쌻unea anterioar훱 cu  SHIFT+TAB sau S훯GEAT훯 SUS. Apas훱 SPA�숳U sau ENTER pentru a selecta op�쌻unea din meniu. Deschide sub-meniul op�쌻unii curente cu SPA�숳U sau ENTER sau S훯GEAT훯 DREAPTA. Revino la elementul din meniul p훱rinte cu ESC sau S훯GEAT훯 ST횂NGA. 횓nchide meniul de context cu ESC."},
{name:"Editor Caset훱 List훱",legend:"횓n interiorul unei liste, treci la urm훱torull element cu TAB sau S훯GEAT훯 JOS. Treci la elementul anterior din list훱 cu SHIFT+TAB sau S훯GEAT훯 SUS. Apas훱 SPA�숳U sau ENTER pentru a selecta op�쌻unea din list훱. Apas훱 ESC pentru a 챤nchide lista."},{name:"Editor Element Path Bar",legend:"Press ${elementsPathFocus} to navigate to the elements path bar. Move to next element button with TAB or RIGHT ARROW. Move to previous button with SHIFT+TAB or LEFT ARROW. Press SPACE or ENTER to select the element in editor."}]},
{name:"Comenzi",items:[{name:" Undo command",legend:"Apas훱 ${undo}"},{name:"Comanda precedent훱",legend:"Apas훱 ${redo}"},{name:"Comanda 횓ngro�셙t",legend:"Apas훱 ${bold}"},{name:"Comanda Inclinat",legend:"Apas훱 ${italic}"},{name:"Comanda Subliniere",legend:"Apas훱 ${underline}"},{name:"Comanda Legatur훱",legend:"Apas훱 ${link}"},{name:" Toolbar Collapse command",legend:"Press ${toolbarCollapse}"},{name:" Access previous focus space command",legend:"Press ${accessPreviousSpace} to access the closest unreachable focus space before the caret, for example: two adjacent HR elements. Repeat the key combination to reach distant focus spaces."},
{name:" Access next focus space command",legend:"Press ${accessNextSpace} to access the closest unreachable focus space after the caret, for example: two adjacent HR elements. Repeat the key combination to reach distant focus spaces."},{name:" Accessibility Help",legend:"Press ${a11yHelp}"}]}],backspace:"Backspace",tab:"Tab",enter:"Enter",shift:"Shift",ctrl:"Ctrl",alt:"Alt",pause:"Pause",capslock:"Caps Lock",escape:"Escape",pageUp:"Page Up",pageDown:"Page Down",end:"End",home:"Home",leftArrow:"Left Arrow",
upArrow:"Up Arrow",rightArrow:"Right Arrow",downArrow:"Down Arrow",insert:"Insert","delete":"Delete",leftWindowKey:"Left Windows key",rightWindowKey:"Right Windows key",selectKey:"Select key",numpad0:"Numpad 0",numpad1:"Numpad 1",numpad2:"Numpad 2",numpad3:"Numpad 3",numpad4:"Numpad 4",numpad5:"Numpad 5",numpad6:"Numpad 6",numpad7:"Numpad 7",numpad8:"Numpad 8",numpad9:"Numpad 9",multiply:"Multiply",add:"Add",subtract:"Subtract",decimalPoint:"Decimal Point",divide:"Divide",f1:"F1",f2:"F2",f3:"F3",
f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Num Lock",scrollLock:"Scroll Lock",semiColon:"Semicolon",equalSign:"Equal Sign",comma:"Comma",dash:"Dash",period:"Period",forwardSlash:"Forward Slash",graveAccent:"Grave Accent",openBracket:"Open Bracket",backSlash:"Backslash",closeBracket:"Close Bracket",singleQuote:"Single Quote"});