/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","si",{title:"釋끶텫釋� 釋�釋믞떵釋꾝톾蓆싟퇁 ",contents:"蓆뗠땡釋�釋� 釋꺺떨釋꾝톽 蓆끶떡釋듺땟蓆삑톶蓆쒉땟蓆�.蓆긍퇁蓆싟톶蓆멘떵釋쇸떳蓆� ESC 蓆뜩퇋蓆�釋듺땟蓆� 蓆붲떰蓆긍톶蓆�",legend:[{name:"蓆닮퇋蓆�釋� 蓆싟떻釋붲땜釋�",items:[{name:"釋꺺텂釋꺺톶蓆싟떻蓆� 蓆멘퇈釋�蓆썅떳釋� ",legend:"蓆붲떰蓆긍톶蓆� ${蓆멘퇈釋�蓆썅떳釋� 蓆�釋볙떻釋� 蓆끶�蓆겯톽蓆긍떵} 蓆멘퇈釋�蓆썅떳釋� 蓆�釋볙떻釋붲�釋� 蓆묂톬釋� 蓆멘퇈釋꾝톽 蓆뷕톿蓆멘때.蓆됢땡釋믞떻釋믞떵蓆� 蓆뷕톿蓆멘때 釋꾝톽 蓆녱떪釋꺺퇃 蓆뷕톿蓆멘때 蓆멘퇈釋�蓆썅떳釋� 蓆�釋볙떻釋붲텥釋뤲땜釋듺땐蓆� 釋꾝톽 TAB 釋꾝톽 SHIFT+TAB .蓆됢땡釋믞떻釋믞떵蓆� 蓆뷕톿蓆멘때 釋꾝톽 蓆녱떪釋꺺퇃 蓆뷕톿蓆멘때 蓆멘퇈釋�蓆썅떳釋� 蓆�釋볙떻釋� 蓆뜩퇋蓆�釋듺땟蓆� 釋꺺떳蓆� RIGHT ARROW 釋꾝퇌 LEFT ARROW.蓆멘퇈釋�蓆썅떳釋� 蓆�釋볙떻釋� 蓆뜩퇋蓆�釋듺땟蓆� 釋꺺텥釋듼�띭떻釋믞떵 蓆싟떻 蓆쒉톾蓆긍퇂蓆멘때 SPACE 釋꾝퇌 ENTER 蓆뜩퇋蓆�釋듺땟蓆� 蓆붲떰蓆긍톶蓆�."},{name:"釋꺺텂釋꺺톶蓆싟떻蓆� ",legend:"Inside a dialog, press TAB to navigate to the next dialog element, press SHIFT+TAB to move to the previous dialog element, press ENTER to submit the dialog, press ESC to cancel the dialog. When a dialog has multiple tabs, the tab list can be reached either with ALT+F10 or with TAB as part of the dialog tabbing order. With tab list focused, move to the next and previous tab with RIGHT and LEFT ARROW, respectively."},
{name:"釋꺺텂釋꺺톶蓆싟떻蓆� 蓆끶땐蓆귖텧釋붲�蓆� ",legend:"蓆붲떰蓆긍톶蓆� ${蓆끶떡釋듺땟蓆삑톶蓆쒉땟 蓆멘퇈蓆긍퇃釋�} 釋꾝퇌  APPLICATION KEY  蓆끶떡釋듺땟蓆삑톶蓆쒉땟-蓆멘퇈蓆긍퇃釋� 釋�釋믞�釋붲떻蓆�蓆싟퇁蓆삑퇂蓆멘때. 蓆듺톭蓆� 蓆멘퇈蓆긍퇃釋�-釋�釋듺텥蓆썅톶蓆닮떵蓆긍톶蓆� 蓆뷕톿蓆멘때 TAB 釋꾝퇌 DOWN ARROW 蓆뜩퇋蓆�釋듺땟蓆� 蓆�, 蓆닮퇈蓆� 釋�釋믞텥蓆썅톶蓆닮떵蓆긍톶蓆㏅떵釋묂떳蓆� SHIFT+TAB 釋꾝퇌  UP ARROW 蓆뜩퇋蓆�釋듺땟蓆� 蓆�, 蓆멘퇈蓆긍퇃釋�-釋�釋듺텥蓆썅톶蓆닮떵蓆긍톶 蓆�釋싟떻釋볙떳蓆� SPACE 釋꾝퇌 ENTER 蓆뜩퇋蓆�釋듺땟蓆� 蓆�,  蓆�釋먣떡蓆� 釋�釋믞�釋붲떻釋듺땟釋� 蓆뉋땟釋� 蓆뗠떪-蓆멘퇈蓆긍퇃釋�蓆� 釋�釋볙텥蓆썅톶蓆� 蓆�釋싟떻釋볙떳蓆� SPACE 釋꾝퇌 ENTER 釋꾝퇌 RIGHT ARROW 蓆�, 蓆긍톾釋�蓆� 蓆닮퇈蓆� 蓆닮톶�띭떻蓆겯톽蓆� 蓆멘퇈蓆긍퇃釋�蓆� 蓆뷕톿蓆멘때  ESC 釋꾝퇌 LEFT ARROW 蓆뜩퇋蓆�釋듺땟蓆� 蓆�.  蓆끶떡釋듺땟蓆삑톶蓆쒉땟-蓆멘퇈蓆긍퇃釋� 釋�釋먣톫釋볙떳蓆�  ESC 蓆뜩퇋蓆�釋듺땟蓆� 蓆� 蓆붲떰蓆긍톶蓆�."},{name:"釋꺺텂釋꺺톶蓆싟떻蓆� 蓆�釋싟떻釋붲떳釋� ",legend:"蓆�釋싟떻釋붲떳釋� 蓆싟퇋蓆㏅퇃釋� 蓆�釋붲톭 , 蓆듺톭蓆� 蓆끶떵釋믞땟蓆멘떵蓆� 蓆뷕톿蓆멘때 TAB 釋꾝퇌 DOWN ARROW , 蓆닮퇈蓆� 蓆끶떵釋믞땟蓆멘떵蓆� 蓆뷕톿蓆멘때 SHIFT+TAB 釋꾝퇌 UP ARROW . 蓆끶떵釋믞땟蓆� 釋�釋믞텥蓆썅톶蓆닮떵蓆긍톶 蓆�釋싟떻釋볙떳蓆� SPACE 釋꾝퇌 ENTER ,蓆�釋싟떻釋붲떳釋� 蓆싟퇋蓆㏅퇃釋� 釋�釋먣톫釋볙떳蓆� ESC 蓆뜩퇋蓆�釋듺땟蓆멘톶 蓆� 蓆붲떰蓆긍톶蓆�."},
{name:"釋꺺텂釋꺺톶蓆싟떻蓆� 蓆끶텂蓆� 釋꺺톬釋믞땟 ",legend:"蓆붲떰蓆긍톶蓆� ${蓆멘퇈釋�蓆썅떳釋� 蓆�釋볙떻釋� 蓆끶�蓆겯톽蓆긍떵} 蓆멘퇈釋�蓆썅떳釋� 蓆�釋볙떻釋붲�釋� 蓆묂톬釋� 蓆멘퇈釋꾝톽 蓆뷕톿蓆멘때.蓆됢땡釋믞떻釋믞떵蓆� 蓆뷕톿蓆멘때 釋꾝톽 蓆녱떪釋꺺퇃 蓆뷕톿蓆멘때 蓆멘퇈釋�蓆썅떳釋� 蓆�釋볙떻釋붲텥釋뤲땜釋듺땐蓆� 釋꾝톽 TAB 釋꾝톽 SHIFT+TAB .蓆됢땡釋믞떻釋믞떵蓆� 蓆뷕톿蓆멘때 釋꾝톽 蓆녱떪釋꺺퇃 蓆뷕톿蓆멘때 蓆멘퇈釋�蓆썅떳釋� 蓆�釋볙떻釋� 蓆뜩퇋蓆�釋듺땟蓆� 釋꺺떳蓆� RIGHT ARROW 釋꾝퇌 LEFT ARROW.蓆멘퇈釋�蓆썅떳釋� 蓆�釋볙떻釋� 蓆뜩퇋蓆�釋듺땟蓆� 釋꺺텥釋듼�띭떻釋믞떵 蓆싟떻 蓆쒉톾蓆긍퇂蓆멘때 SPACE 釋꾝퇌 ENTER 蓆뜩퇋蓆�釋듺땟蓆� 蓆붲떰蓆긍톶蓆�."}]},{name:"釋�釋믞떠釋뤲떡",items:[{name:"釋�釋믞떠釋뤲떡蓆� 釋�釋쇸떡釋꺺톶 ",legend:"蓆붲떰蓆긍톶蓆� ${釋�釋쇸떡釋꺺톶 蓆싟퇁蓆삑퇂蓆�}"},{name:"釋�釋믞떠釋뤲떡 蓆긍톾釋�蓆�釋� 蓆닮퇈蓆� 蓆닮떻釋믞땡釋믞떳 釋�釋쇸떡釋꺺톶蓆싟떻 蓆쒉톾蓆긍퇂蓆�.",legend:"蓆붲떰蓆긍톶蓆� ${蓆긍톾釋�蓆�釋� 蓆닮퇈蓆� 蓆닮떻釋믞땡釋믞떳 釋�釋쇸떡釋꺺톶蓆싟떻 蓆쒉톾蓆긍퇂蓆�}"},{name:"蓆�蓆� 蓆끶텥釋붲떻釋믞떡釋� 釋�釋믞떠釋뤲떡",legend:"蓆붲떰蓆긍톶蓆� ${蓆�蓆� }"},
{name:"蓆뜩톾蓆겯퇂 蓆끶텥釋붲떻釋� 釋�釋믞떠釋뤲떡",legend:"蓆붲떰蓆긍톶蓆� ${蓆뜩톾蓆겯퇂 蓆끶텥釋붲떻釋� }"},{name:"蓆뷕때釋믞떡釋� 蓆됢떻釋� 蓆뉋땡 蓆뉋땟釋� 釋�釋믞떠釋뤲떡.",legend:"蓆붲떰蓆긍톶蓆� ${蓆뷕때釋믞떡釋� 蓆됢떻釋� 蓆뉋땡 蓆뉋땟釋�}"},{name:"釋꺺떳釋듺떰蓆긍톶蓆겯퇁蓆� 釋�釋믞떠釋뤲떡",legend:"蓆붲떰蓆긍톶蓆� ${釋꺺떳釋듺떰蓆긍톶蓆� }"},{name:"蓆멘퇈釋�蓆썅떳釋� 蓆�釋볙떻釋� 釋꾝톾蓆싟퇃蓆썅퇃蓆멘톶 釋�釋믞떠釋뤲떡",legend:"蓆붲떰蓆긍톶蓆� ${蓆멘퇈釋�蓆썅떳釋� 蓆�釋볙떻釋� 釋꾝톾蓆싟퇃蓆썅퇃蓆멘톶 }"},{name:"蓆뷕퇋蓆멘퇃釋�釋볙떳蓆� 蓆닮퇈蓆�  釋�釋먣땡蓆쒉땟釋�  釋�釋믞떠釋뤲떡",legend:"蓆붲떰蓆긍톶蓆� ${蓆뷕퇋蓆멘퇃釋�釋볙떳蓆� 蓆듺톭蓆� }"},{name:"蓆뷕퇋蓆멘퇃釋�釋볙떳蓆� 蓆듺톭蓆� 釋�釋먣땡蓆쒉땟釋�  釋�釋믞떠釋뤲떡",legend:"蓆붲떰蓆긍톶蓆� ${蓆뷕퇋蓆멘퇃釋�釋볙떳蓆� 蓆듺톭蓆� }"},{name:"蓆닮톶�띭떻釋�釋싟톩 ",legend:"蓆붲떰蓆긍톶蓆�  ${a11y }"}]}],backspace:"Backspace",tab:"Tab",enter:"Enter",shift:"Shift",ctrl:"Ctrl",
alt:"Alt",pause:"Pause",capslock:"Caps Lock",escape:"Escape",pageUp:"Page Up",pageDown:"Page Down",end:"End",home:"Home",leftArrow:"Left Arrow",upArrow:"Up Arrow",rightArrow:"Right Arrow",downArrow:"Down Arrow",insert:"Insert","delete":"Delete",leftWindowKey:"Left Windows key",rightWindowKey:"Right Windows key",selectKey:"Select key",numpad0:"Numpad 0",numpad1:"Numpad 1",numpad2:"Numpad 2",numpad3:"Numpad 3",numpad4:"Numpad 4",numpad5:"Numpad 5",numpad6:"Numpad 6",numpad7:"Numpad 7",numpad8:"Numpad 8",
numpad9:"Numpad 9",multiply:"Multiply",add:"Add",subtract:"Subtract",decimalPoint:"Decimal Point",divide:"Divide",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Num Lock",scrollLock:"Scroll Lock",semiColon:"Semicolon",equalSign:"Equal Sign",comma:"Comma",dash:"Dash",period:"Period",forwardSlash:"Forward Slash",graveAccent:"Grave Accent",openBracket:"Open Bracket",backSlash:"Backslash",closeBracket:"Close Bracket",singleQuote:"Single Quote"});