/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","sl",{title:"Navodila Dostopnosti",contents:"Vsebina Pomo훾i. 훻e 탑elite zapreti to pogovorno okno pritisnite ESC.",legend:[{name:"Splo큄no",items:[{name:"Urejevalna Orodna Vrstica",legend:"Pritisnite ${toolbarFocus} za pomik v orodno vrstico. Z TAB in SHIFT+TAB se pomikate na naslednjo in prej큄njo skupino orodne vrstice. Z DESNO PU힋훻ICO ali LEVO PU힋훻ICO se pomikate na naslednji in prej큄nji gumb orodne vrstice. Pritisnite SPACE ali ENTER, da aktivirate gumb orodne vrstice."},
{name:"Urejevalno Pogovorno Okno",legend:"Inside a dialog, press TAB to navigate to the next dialog element, press SHIFT+TAB to move to the previous dialog element, press ENTER to submit the dialog, press ESC to cancel the dialog. When a dialog has multiple tabs, the tab list can be reached either with ALT+F10 or with TAB as part of the dialog tabbing order. With tab list focused, move to the next and previous tab with RIGHT and LEFT ARROW, respectively."},{name:"Urejevalni Kontekstni Meni",legend:"Pritisnite ${contextMenu} ali APPLICATION KEY, da odprete kontekstni meni. Nato se premaknite na naslednjo mo탑nost menija s tipko TAB ali PU힋훻ICA DOL. Premakniti se na prej큄njo mo탑nost z SHIFT + TAB ali PU힋훻ICA GOR. Pritisnite SPACE ali ENTER za izbiro mo탑nosti menija. Odprite podmeni trenutne mo탑nosti menija s tipko SPACE ali ENTER ali DESNA PU힋훻ICA. Vrnite se na mati훾ni element menija s tipko ESC ali LEVA PU힋훻ICA. Zaprite kontekstni meni z ESC."},
{name:"Urejevalno Seznamsko Polje",legend:"Znotraj seznama, se premaknete na naslednji element seznama s tipko TAB ali PU힋훻ICO DOL. Z SHIFT+TAB ali PU힋훻ICO GOR se premaknete na prej큄nji element seznama. Pritisnite tipko SPACE ali ENTER za izbiro elementa. Pritisnite tipko ESC, da zaprete seznam."},{name:"Urejevalna vrstica poti elementa",legend:"Pritisnite ${elementsPathFocus} za pomikanje po vrstici elementnih poti. S TAB ali DESNA PU힋훻ICA se premaknete na naslednji gumb elementa. Z SHIFT+TAB ali LEVO PU힋훻ICO se premaknete na prej큄nji gumb elementa. Pritisnite SPACE ali ENTER za izbiro elementa v urejevalniku."}]},
{name:"Ukazi",items:[{name:"Razveljavi ukaz",legend:"Pritisnite ${undo}"},{name:"Ponovi ukaz",legend:"Pritisnite ${redo}"},{name:"Krepki ukaz",legend:"Pritisnite ${bold}"},{name:"Le탑e훾i ukaz",legend:"Pritisnite ${italic}"},{name:"Poudarni ukaz",legend:"Pritisnite ${underline}"},{name:"Ukaz povezave",legend:"Pritisnite ${link}"},{name:"Skr훾i Orodno Vrstico Ukaz",legend:"Pritisnite ${toolbarCollapse}"},{name:"Dostop do prej큄njega ukaza ostrenja",legend:"Pritisnite ${accessPreviousSpace} za dostop do najbli탑jega nedosegljivega osredoto훾enega prostora pred stre큄ico, npr.: dva sosednja HR elementa. Ponovite kombinacijo tipk, da dose탑ete oddaljene osredoto훾ene prostore."},
{name:"Dostop do naslednjega ukaza ostrenja",legend:"Pritisnite ${accessNextSpace} za dostop do najbli탑jega nedosegljivega osredoto훾enega prostora po stre큄ici, npr.: dva sosednja HR elementa. Ponovite kombinacijo tipk, da dose탑ete oddaljene osredoto훾ene prostore."},{name:"Pomo훾 Dostopnosti",legend:"Pritisnite ${a11yHelp}"}]}],backspace:"Backspace",tab:"Tab",enter:"Enter",shift:"Shift",ctrl:"Ctrl",alt:"Alt",pause:"Pause",capslock:"Caps Lock",escape:"Escape",pageUp:"Page Up",pageDown:"Page Down",end:"End",
home:"Home",leftArrow:"Levo pu큄훾ica",upArrow:"Gor pu큄훾ica",rightArrow:"Desno pu큄훾ica",downArrow:"Dol pu큄훾ica",insert:"Insert","delete":"Delete",leftWindowKey:"Leva Windows tipka",rightWindowKey:"Desna Windows tipka",selectKey:"Select tipka",numpad0:"Numpad 0",numpad1:"Numpad 1",numpad2:"Numpad 2",numpad3:"Numpad 3",numpad4:"Numpad 4",numpad5:"Numpad 5",numpad6:"Numpad 6",numpad7:"Numpad 7",numpad8:"Numpad 8",numpad9:"Numpad 9",multiply:"Zmno탑i",add:"Dodaj",subtract:"Od큄tej",decimalPoint:"Decimalna vejica",
divide:"Deli",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Num Lock",scrollLock:"Scroll Lock",semiColon:"Podpi훾je",equalSign:"ena훾aj",comma:"Vejica",dash:"Vezaj",period:"Pika",forwardSlash:"Desna po큄evnica",graveAccent:"Krativec",openBracket:"Oklepaj",backSlash:"Leva po큄evnica",closeBracket:"Oklepaj",singleQuote:"Opu큄훾aj"});