/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","tt",{title:"Accessibility Instructions",contents:"Help Contents. To close this dialog press ESC.",legend:[{name:"�볂압솅꺪셸�",items:[{name:"Editor Toolbar",legend:"Press ${toolbarFocus} to navigate to the toolbar. Move to the next and previous toolbar group with TAB and SHIFT+TAB. Move to the next and previous toolbar button with RIGHT ARROW or LEFT ARROW. Press SPACE or ENTER to activate the toolbar button."},{name:"Editor Dialog",legend:"Inside a dialog, press TAB to navigate to the next dialog element, press SHIFT+TAB to move to the previous dialog element, press ENTER to submit the dialog, press ESC to cancel the dialog. When a dialog has multiple tabs, the tab list can be reached either with ALT+F10 or with TAB as part of the dialog tabbing order. With tab list focused, move to the next and previous tab with RIGHT and LEFT ARROW, respectively."},
{name:"Editor Context Menu",legend:"Press ${contextMenu} or APPLICATION KEY to open context-menu. Then move to next menu option with TAB or DOWN ARROW. Move to previous option with SHIFT+TAB or UP ARROW. Press SPACE or ENTER to select the menu option. Open sub-menu of current option with SPACE or ENTER or RIGHT ARROW. Go back to parent menu item with ESC or LEFT ARROW. Close context menu with ESC."},{name:"Editor List Box",legend:"Inside a list-box, move to next list item with TAB OR DOWN ARROW. Move to previous list item with SHIFT+TAB or UP ARROW. Press SPACE or ENTER to select the list option. Press ESC to close the list-box."},
{name:"Editor Element Path Bar",legend:"Press ${elementsPathFocus} to navigate to the elements path bar. Move to next element button with TAB or RIGHT ARROW. Move to previous button with SHIFT+TAB or LEFT ARROW. Press SPACE or ENTER to select the element in editor."}]},{name:"�싍압셸겆싻닉겆뿅겉�",items:[{name:"�싍겆밂궿겉���",legend:"${undo} 閨逵�곎뗊넘뗊�"},{name:"�싍겆귈겉궿뿅겉�",legend:"${redo} 閨逵�곎뗊넘뗊�"},{name:"�싍겆뿌뗊�",legend:"${bold} 閨逵�곎뗊넘뗊�"},{name:"�싎꺫��곍먁�",legend:"${italic} 閨逵�곎뗊넘뗊�"},{name:"�먓곎귂뗊싻� �곎뗊롤뗊뿅넓겆�",legend:"${underline} 閨逵�곎뗊넘뗊�"},
{name:"鬼�뗊뿌궿겆뿅겆셸�",legend:"${link} 閨逵�곎뗊넘뗊�"},{name:" Toolbar Collapse command",legend:"${toolbarCollapse} 閨逵�곎뗊넘뗊�"},{name:" Access previous focus space command",legend:"Press ${accessPreviousSpace} to access the closest unreachable focus space before the caret, for example: two adjacent HR elements. Repeat the key combination to reach distant focus spaces."},{name:" Access next focus space command",legend:"Press ${accessNextSpace} to access the closest unreachable focus space after the caret, for example: two adjacent HR elements. Repeat the key combination to reach distant focus spaces."},
{name:" Accessibility Help",legend:"${a11yHelp} 閨逵�곎뗊넘뗊�"}]}],backspace:"�싍겆밂궿겉���",tab:"Tab",enter:"Enter",shift:"Shift",ctrl:"Ctrl",alt:"Alt",pause:"龜�뗊싼뗋�",capslock:"Caps Lock",escape:"Escape",pageUp:"Page Up",pageDown:"Page Down",end:"End",home:"Home",leftArrow:"鬼�꺪� �뤢분분� �꺪�",upArrow:"斷�곍붉� �궿겆귈� �꺪�",rightArrow:"叫蠟 �뤢분분� �꺪�",downArrow:"�먓곍분� �궿겆귈� �꺪�",insert:"斷�곎귅쇦�","delete":"�뫰둘궿둘�奈",leftWindowKey:"鬼�꺪� Windows �귅⒟밀셤쇥곍�",rightWindowKey:"叫蠟 Windows �귅⒟밀셤쇥곍�",selectKey:"Select �귅⒟밀셤쇥곍�",numpad0:"Numpad 0",numpad1:"Numpad 1",
numpad2:"Numpad 2",numpad3:"Numpad 3",numpad4:"Numpad 4",numpad5:"Numpad 5",numpad6:"Numpad 6",numpad7:"Numpad 7",numpad8:"Numpad 8",numpad9:"Numpad 9",multiply:"龜逵極克�뗋�剋逵��",add:"�싎꺫댮�",subtract:"�먒뿌�",decimalPoint:"叫戟逵�剋�� 戟棘克�궿�",divide:"�뫲�剋奈",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Num Lock",scrollLock:"Scroll Lock",semiColon:"�앆압붇궿겆뿌� 旦�궿둘�",equalSign:"龜龜均筠鈞剋筠克 閨龜剋均筠�곍�",comma:"斷�궿둘�",dash:"鬼�뗊롤뗊�",period:"�붣쇥��쇦쀓�",forwardSlash:"�싎뗊둔� �곎뗊롤뗊�",
graveAccent:"�볃�逵勻龜��",openBracket:"�뽗쇥� 逵�눻�",backSlash:"�싍먈�筠 克�뗊둔� �곎뗊롤뗊�",closeBracket:"�뽗쇥� �뤢귐�",singleQuote:"�뫰둘� 龜蠟剋筠 克�꺫댮귂뗋�戟逵克剋逵�"});