/*
 Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.plugins.setLang("a11yhelp","vi",{title:"H튼沼썀g d梳쳌 tr沼� n훱ng",contents:"N沼셢 dung H沼� tr沼�. Nh梳쩸 ESC 휃沼� 휃처ng h沼셮 tho梳죍.",legend:[{name:"Chung",items:[{name:"Thanh c척ng c沼� so梳죒 th梳즣",legend:"Nh梳쩸 ${toolbarFocus} 휃沼� 휃i沼걏 h튼沼썀g 휃梳퓆 thanh c척ng c沼�. Nh梳쩸 TAB v횪 SHIFT+TAB 휃沼� chuy沼긪 휃梳퓆 nh처m thanh c척ng c沼� kh찼c. Nh梳쩸 M큠I T횎N PH梳줚 ho梳톍 M큠I T횎N TR횁I 휃沼� chuy沼긪 sang n첬t kh찼c tr챗n thanh c척ng c沼�. Nh梳쩸 PH횒M C횁CH ho梳톍 ENTER 휃沼� k챠ch ho梳죜 n첬t tr챗n thanh c척ng c沼�."},{name:"H沼셮 tho梳죍 Bi챗n t",legend:"Inside a dialog, press TAB to navigate to the next dialog element, press SHIFT+TAB to move to the previous dialog element, press ENTER to submit the dialog, press ESC to cancel the dialog. When a dialog has multiple tabs, the tab list can be reached either with ALT+F10 or with TAB as part of the dialog tabbing order. With tab list focused, move to the next and previous tab with RIGHT and LEFT ARROW, respectively."},
{name:"Tr챙nh 휃퉤n Ng沼� c梳즢h cB沼� so梳죒 th梳즣",legend:"Nh梳쩸 ${contextMenu} ho梳톍 PH횒M 沼쭼G D沼짴G 휃沼� m沼� th沼켧 휃퉤n ng沼� c梳즢h. Sau 휃처 nh梳쩸 TAB ho梳톍 M큠I T횎N XU沼륬G 휃沼� di chuy沼긪 휃梳퓆 tu沼� ch沼뛫 ti梳퓈 theo c沼쬪 th沼켧 휃퉤n. Nh梳쩸 SHIFT+TAB ho梳톍 M큠I T횎N L횎N 휃沼� quay l梳죍 tu沼� ch沼뛫 tr튼沼쌵. Nh梳쩸 D梳짾 C횁CH ho梳톍 ENTER 휃沼� ch沼뛫 tu沼� ch沼뛫 c沼쬪 th沼켧 휃퉤n. Nh梳쩸 D梳짾 C횁CH ho梳톍 ENTER ho梳톍 M큠I T횎N SANG PH梳줚 휃沼� m沼� th沼켧 휃퉤n con c沼쬪 tu沼� ch沼뛫 hi沼뇆 t梳죍. Nh梳쩸 ESC ho梳톍 M큠I T횎N SANG TR횁I 휃沼� quay tr沼� l梳죍 th沼켧 휃퉤n g沼멵. Nh梳쩸 ESC 휃沼� 휃처ng th沼켧 휃퉤n ng沼� c梳즢h."},
{name:"H沼셮 danh s찼ch tr챙nh bi챗n t梳춑",legend:"Trong m沼셳 danh s찼ch ch沼뛫, di chuy沼긪 휃沼멼 t튼沼즢g ti梳퓈 theo v沼쌻 ph챠m TAB ho梳톍 ph챠m m크i t챗n h튼沼썀g xu沼몁g. Di chuy沼긪 휃梳퓆 휃沼멼 t튼沼즢g tr튼沼쌵 휃처 b梳켷g c찼ch nh梳쩸 t沼� h沼즤 ph챠m SHIFT+TAB ho梳톍 m크i t챗n h튼沼썀g l챗n. Ph챠m kho梳즢g c찼ch ho梳톍 ph챠m ENTER 휃沼� ch沼뛫 c찼c t첫y ch沼뛫 trong danh s찼ch. Nh梳쩸 ph챠m ESC 휃沼� 휃처ng l梳죍 danh s찼ch ch沼뛫."},{name:"Thanh 휃튼沼쓓g d梳쳌 c찼c 휃沼멼 t튼沼즢g",legend:"Nh梳쩸 ${elementsPathFocus} 휃沼� 휃i沼걏 h튼沼썀g c찼c 휃沼멼 t튼沼즢g trong thanh 휃튼沼쓓g d梳쳌. Di chuy沼긪 휃梳퓆 휃沼멼 t튼沼즢g ti梳퓈 theo b梳켷g ph챠m TAB ho梳톍 ph챠m m크i t챗n b챗n ph梳즜. Di chuy沼긪 휃梳퓆 휃沼멼 t튼沼즢g tr튼沼쌵 휃처 b梳켷g t沼� h沼즤 ph챠m SHIFT+TAB ho梳톍 ph챠m m크i t챗n b챗n tr찼i. Nh梳쩸 ph챠m kho梳즢g c찼ch ho梳톍 ENTER 휃沼� ch沼뛫 휃沼멼 t튼沼즢g trong tr챙nh so梳죒 th梳즣."}]},
{name:"L沼뇆h",items:[{name:"L횪m l梳죍 l沼뇆",legend:"梳쨙 ${undo}"},{name:"L횪m l梳죍 l沼뇆h",legend:"梳쨙 ${redo}"},{name:"L沼뇆h in 휃梳춎",legend:"梳쨙 ${bold}"},{name:"L沼뇆h in nghi챗ng",legend:"梳쨙 ${italic}"},{name:"L沼뇆h g梳죅h d튼沼쌻",legend:"梳쨙 ${underline}"},{name:"L沼뇆h li챗n k梳퓍",legend:"Nh梳쩸 ${link}"},{name:"L沼뇆h hi沼긪 th沼� thanh c척ng c沼�",legend:"Nh梳쩸${toolbarCollapse}"},{name:"Truy c梳춑 휃梳퓆 l沼뇆h t梳춑 trung v횪o kho梳즢g c찼ch tr튼沼쌵 휃처",legend:"梳쨙 ${accessPreviousSpace} 휃沼� truy c梳춑 휃梳퓆 ph梳쬷 t梳춑 trung kho梳즢g c찼ch sau ph梳쬷 c챵n s처t l梳죍 c沼쬪 kho梳즢g c찼ch g梳쬷 nh梳쩿 v沼몁 kh척ng t찼c 휃沼셬g 휃梳퓆 휃튼沼즓 , th챠 d沼�: hai y梳퓎 t沼� 휃i沼걏 ch沼뎝h HR. L梳톚 l梳죍 c찼c ph챠m k梳퓍 h沼뛢p n횪y 휃沼� v튼퉤n 휃梳퓆 ph梳쬷 kho梳즢g c찼ch."},
{name:"Truy c梳춑 ph梳쬷 휃沼멼 t튼沼즢g l沼뇆h kho梳즢g tr沼몁g",legend:"梳쨙 ${accessNextSpace} 휃沼� truy c梳춑 휃梳퓆 ph梳쬷 t梳춑 trung kho梳즢g c찼ch sau ph梳쬷 c챵n s처t l梳죍 c沼쬪 kho梳즢g c찼ch g梳쬷 nh梳쩿 v沼몁 kh척ng t찼c 휃沼셬g 휃梳퓆 휃튼沼즓 , th챠 d沼�: hai y梳퓎 t沼� 휃i沼걏 ch沼뎝h HR. L梳톚 l梳죍 c찼c ph챠m k梳퓍 h沼뛢p n횪y 휃沼� v튼퉤n 휃梳퓆 ph梳쬷 kho梳즢g c찼ch."},{name:"Tr沼� gi첬p li챗n quan",legend:"Nh梳쩸 ${a11yHelp}"}]}],backspace:"Ph챠m Backspace",tab:"Ph챠m Tab",enter:"Ph챠m Tab",shift:"Ph챠m Shift",ctrl:"Ph챠m Ctrl",alt:"Ph챠m Alt",pause:"Ph챠m Pause",capslock:"Ph챠m Caps Lock",
escape:"Ph챠m Escape",pageUp:"Ph챠m Page Up",pageDown:"Ph챠m Page Down",end:"Ph챠m End",home:"Ph챠m Home",leftArrow:"Ph챠m Left Arrow",upArrow:"Ph챠m Up Arrow",rightArrow:"Ph챠m Right Arrow",downArrow:"Ph챠m Down Arrow",insert:"Ch챔n","delete":"X처a",leftWindowKey:"Ph챠m Left Windows",rightWindowKey:"Ph챠m Right Windows ",selectKey:"Ch沼뛫 ph챠m",numpad0:"Ph챠m 0",numpad1:"Ph챠m 1",numpad2:"Ph챠m 2",numpad3:"Ph챠m 3",numpad4:"Ph챠m 4",numpad5:"Ph챠m 5",numpad6:"Ph챠m 6",numpad7:"Ph챠m 7",numpad8:"Ph챠m 8",numpad9:"Ph챠m 9",
multiply:"Nh창n",add:"Th챗m",subtract:"Tr沼�",decimalPoint:"휂i沼긩 s沼� th梳춑 ph창n",divide:"Chia",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Num Lock",scrollLock:"Scroll Lock",semiColon:"D梳쪀 ch梳쩷 ph梳쯻",equalSign:"휂훱ng nh梳춑 b梳켷g",comma:"D梳쪀 ph梳쯻",dash:"D梳쪀 g梳죅h ngang",period:"Ph챠m .",forwardSlash:"Ph챠m /",graveAccent:"Ph챠m `",openBracket:"Open Bracket",backSlash:"D梳쪀 g梳죅h ch챕o ng튼沼즓",closeBracket:"G梳쬷 gi찼 휃沼�",singleQuote:"Tr챠ch d梳쳌"});